aurelia/aurelia

.gitignore
.vscode/launch.json
README.md
karma.conf.ts
package-scripts.js

Unit testing things

---

src/runtime/binding/array-observer.ts
src/runtime/binding/collection-observer.ts
src/runtime/binding/map-observer.ts
src/runtime/binding/observation.ts
src/runtime/binding/set-observer.ts
test/runtime/binding/array-observer.spec.ts
test/runtime/util.ts
tsconfig.json

First step towards getting the new repeater in

feat(observation): add improved collection observers

---

packages/runtime/src/templating/custom-attribute.ts
packages/runtime/src/templating/custom-element.ts
packages/runtime/src/templating/render-context.ts
packages/runtime/src/templating/resources/repeat.ts
packages/runtime/src/templating/resources/replaceable.ts
packages/runtime/src/templating/view.ts
packages/runtime/test/unit/templating/fakes/view-owner-fake.ts
packages/runtime/test/unit/templating/fakes/visual-factory-fake.ts
packages/runtime/test/unit/templating/fakes/visual-fake.ts
packages/runtime/test/unit/templating/resources/repeater.spec.ts
packages/runtime/test/unit/templating/resources/replaceable.spec.ts

feat(templating): convert replaceable to use render location

---

lerna.json
package-lock.json
package.json

Lerna is now on 3.x, let's follow suit

chore(all): update lerna to 3.x non-rc

---

packages/jit/test/unit/templating/template-compiler.integration.spec.ts
packages/runtime/src/dom.ts

This one silly little thing took me **so** long to track down.. but it's finally working now :)

fix(dom): append nodes to the correct thing (doh)

---

packages/jit/test/unit/templating/template-compiler.integration.spec.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/binding.ts
packages/runtime/src/binding/resources/debounce-binding-behavior.ts

Bringing in more binding and templating resources with unit tests

resource-tests

---

.circleci/config.yml
packages/examples/jit-aurelia-cli/.gitignore
packages/examples/jit-aurelia-cli/aurelia_project/aurelia.json
packages/examples/jit-aurelia-cli/aurelia_project/tasks/build.ts
packages/examples/jit-aurelia-cli/aurelia_project/tasks/process-markup.ts
packages/examples/jit-aurelia-cli/aurelia_project/tasks/run.ts
packages/examples/jit-aurelia-cli/aurelia_project/tasks/transpile.ts
packages/examples/jit-aurelia-cli/aurelia_project/tasks/watch.ts
packages/examples/jit-aurelia-cli/e2e/common/browser.ts
packages/examples/jit-aurelia-cli/e2e/page-objects/app.constants.ts
packages/examples/jit-aurelia-cli/e2e/page-objects/app.page.ts
packages/examples/jit-aurelia-cli/e2e/test.spec.ts
packages/examples/jit-aurelia-cli/index.html
packages/examples/jit-aurelia-cli/main.ts
packages/examples/jit-aurelia-cli/package-lock.json
packages/examples/jit-aurelia-cli/package.json
packages/examples/jit-aurelia-cli/src/app.html
packages/examples/jit-aurelia-cli/src/app.ts
packages/examples/jit-aurelia-cli/src/html.d.ts
packages/examples/jit-aurelia-cli/src/startup.ts
packages/examples/jit-aurelia-cli/tsconfig.json

@huochunpeng I tried to use `github:huochunpeng/cli#at31` for this one because the auto-tracing seems very convenient. It errors out though:
```
INFO [Bundler] Tracing files ...
commonJs.convert: COULD NOT CONVERT: (...)\jit-aurelia-cli\dist\src\app.d.ts, so skipping it. Error was: Error: Line 1: Unexpected token
ERROR [Bundler] Failed to do transforms
INFO [Bundler] Error: Line 1: Unexpected token
```
I think this is due to how the new typescript 3 project reference thing works. The references go to .d.ts files and find the originals via the mappings. I couldn't get it to work with the "normal" version of aurelia-cli either though. But that's because I didn't feel like adding 100 files mappings by hand :)
Any thoughts?

chore(examples): initial setup for aurelia-cli

---

packages/runtime/src/binding/ast.ts

Just a general cleanup with lint fixes and a few small tweaks
@EisenbergEffect  @bigopon

ast improvements

---

packages/jit/test/unit/templating/template-compiler.integration.spec.ts
packages/runtime/src/binding/event-manager.ts
packages/runtime/src/binding/listener.ts
packages/runtime/test/unit/binding/event-manager.spec.ts

- Fixes the `.delegate` and `.capture` handlers
- Adds a whole bunch of unit tests (and a few integration tests) to bring the coverage for event-manager to 100%
- Some more unit tests

Event manager

---

packages/jit/src/templating/binding-command.ts
packages/jit/src/templating/template-compiler.ts
packages/jit/test/unit/templating/instruction-compiler.spec.ts
packages/jit/test/unit/templating/template-compiler.integration.spec.ts
packages/jit/test/unit/templating/template-compiler.spec.ts
packages/runtime/src/templating/custom-attribute.ts
packages/runtime/src/templating/custom-element.ts

refactor(template-compiler): move stuff around / fix various edge cases

---

.circleci/config.yml
scripts/publish-nightly.ts

Not 100% sure if this fixes it (depends on 2FA settings) but a few problems are ruled out:
- .npmrc should be in the home directory
- append to the .npmrc instead of overwriting it (in case it already initialized, keep whatever's in there)
- use same casing for the env variable

chore(ci): fix oauth

---

packages/runtime/src/binding/collection-observer.ts
packages/runtime/src/binding/observation.ts
packages/runtime/src/binding/observer-locator.ts
packages/runtime/test/unit/binding/observer-locator.spec.ts

fix(observer-locator): add collection length back in, fix precedence, add tests

---

packages/kernel/src/platform.ts
packages/kernel/test/unit/platform.spec.ts
packages/runtime/src/dom.ts
packages/runtime/src/templating/custom-element.ts
packages/runtime/src/templating/rendering-engine.ts

Also reworks `camelCase` and `kebabCase` to take less code and correctly handle more edge cases while keeping roughly same perf

test(kernel): add toArray() and unit tests

---

docs/engineering/README.md
package-lock.json
package.json

@EisenbergEffect @bigopon 
May come in handy after doing a big rebase/merge or generally when the directories have clogged up with whatever or the project folder is just messed up.
Explained what it does in engineering docs

chore(all): add refresh convenience script

---

README.md
package-lock.json
package.json

fix #127
Commit messages are automatically validated via husky hook.
Use `npm run commit` to get an interactive CLI for building a properly formatted commit message

chore(all): add validate-commit-msg hook and commitizen script

---

packages/examples/e2e-benchmark/tsconfig.json

Fixes an oversight that breaks vcurrent benchmark

chore(benchmark): fix tsconfig tslib issue

---

.circleci/config.yml
docs/CHANGELOG.md

fix the tags workflow

---

examples/bundlers/jit-aurelia-cli-ts/README.md
examples/bundlers/jit-aurelia-cli-ts/package.json
examples/bundlers/jit-browserify-ts/README.md
examples/bundlers/jit-fuse-box-ts/.gitignore
examples/bundlers/jit-fuse-box-ts/.npmrc
examples/bundlers/jit-fuse-box-ts/README.md
examples/bundlers/jit-fuse-box-ts/fuse.js
examples/bundlers/jit-fuse-box-ts/index.html
examples/bundlers/jit-fuse-box-ts/package.json
examples/bundlers/jit-fuse-box-ts/src/app.html
examples/bundlers/jit-fuse-box-ts/src/app.ts
examples/bundlers/jit-fuse-box-ts/src/html.d.ts
examples/bundlers/jit-fuse-box-ts/src/startup.ts
examples/bundlers/jit-fuse-box-ts/src/tsconfig.json
examples/bundlers/jit-parcel-ts/README.md
examples/bundlers/jit-webpack-ts/README.md

Hi @EisenbergEffect @fkleuver 
I have added fuse-box example, keeping jit-webpack-ts as reference.
Thanks,
Praveen.

examples: jit-fuse-box-ts

---

.circleci/config.yml

@EisenbergEffect These are the fixes to make the publish job work

ci: add fixes for the publish workflow

---

packages/jit/src/element-parser.ts
packages/runtime/src/dom.ts
packages/runtime/src/templating/custom-element.ts
packages/runtime/src/templating/lifecycle.ts
packages/runtime/src/templating/renderable.ts
tslint.json

This PR contains for the most part improvements to the precision of types, and some preliminary API documentation for what tends to be the most misunderstood part of the framework: the lifecycle hooks.

typings and api docs

---

lerna.json
packages/tsconfig.json
packages/validation/LICENSE
packages/validation/README.md
packages/validation/package-lock.json
packages/validation/package.json
packages/validation/src/index.ts
packages/validation/test/setup.ts
packages/validation/test/tsconfig.json
packages/validation/test/unit/index.spec.ts
packages/validation/tsconfig-test.json
packages/validation/tsconfig.json

This add the basic boilerplate for the `@aurelia/validation` package
@jdanyow :)

chore(validation): add validation package boilerplate

---

lerna.json
packages/testing/LICENSE
packages/testing/README.md
packages/testing/package-lock.json
packages/testing/package.json
packages/testing/src/index.ts
packages/testing/test/setup.ts
packages/testing/test/tsconfig.json
packages/testing/test/unit/index.spec.ts
packages/testing/tsconfig-test.json
packages/testing/tsconfig.json
packages/tsconfig.json

@EisenbergEffect 
This add the basic boilerplate for the `@aurelia/testing` package.
In the process of cleaning up the tests and in preparation for further work on e2e tests and CI, I'd like to have this package present so that I can easily put stuff in it that needs to be reused across packages/examples.
Clean up tests :)

chore(testing): add testing package boilerplate

---

lerna.json
packages/plugin-parcel/LICENSE
packages/plugin-parcel/README.md
packages/plugin-parcel/package-lock.json
packages/plugin-parcel/package.json
packages/plugin-parcel/src/index.ts
packages/plugin-parcel/test/setup.ts
packages/plugin-parcel/test/tsconfig.json
packages/plugin-parcel/test/unit/index.spec.ts
packages/plugin-parcel/tsconfig-test.json
packages/plugin-parcel/tsconfig.json
packages/plugin-webpack/LICENSE
packages/plugin-webpack/README.md
packages/plugin-webpack/package-lock.json
packages/plugin-webpack/package.json
packages/plugin-webpack/src/index.ts
packages/plugin-webpack/test/setup.ts
packages/plugin-webpack/test/tsconfig.json
packages/plugin-webpack/test/unit/index.spec.ts
packages/plugin-webpack/tsconfig-test.json
packages/plugin-webpack/tsconfig.json
packages/tsconfig.json

Add the package boilerplate for parcel and webpack bundler plugins

chore(plugin-parcel/plugin-webpack): add bundler plugin boilerplate for parcel and webpack

---

docs/engineering/release-procedure.md
scripts/bump-version.ts
scripts/generate-changelog.ts
scripts/package.json.ts
scripts/project.ts

This PR includes some small fixes to the bump-version and generate-changelog scripts and describes the release process
N/A
Follow the steps and see how it goes :)
There is a rework of the circleci configuration in the making, and a few changes will be made to the underlying process but this shouldn't affect the overall process too much.

chore(all): fix and describe the release steps

---

.circleci/config.yml

This change should never really be needed apart from this sort of silly exceptional scenario where a change was pushed to a tag and to master separately, but since we can assume master is "the latest and the greatest", this is a viable tweak to fix both the current issue and to keep the release process just that little bit more robust in the fiture

ci: use Xtheirs merge strategy for merge conflicts in release

---

docs/engineering/release-procedure.md

docs: add error recovery steps to release process

---

package.json

Add nodejs and npm semver compatibility ranges to package.json for contributors

chore(all): add engines fields to root package.json

---

.circleci/config.yml

Fix publish to npm after pushing to develop or release (forgot the checkout step in one of the refactor cycles)
Also moved things around a bit to improve cohesiveness and added some clarifying comments
Small difference in workflow: the publish to `@dev` is now actually triggered by the push to the develop branch, rather than chained behind it in the same workflow. This effectively turns the nightly into two workflows, similar to the release workflow.

ci: fix publish job and tidy up the yml a bit

---

.circleci/config.yml

dev publish restore cache isn't working, so doing a regular npm install instead

ci: fix dev publish

---

docs/SUPPORT.md

doc: Tiny typo

---

packages/kernel/src/di.ts
packages/kernel/src/interfaces.ts
packages/kernel/src/platform.ts
packages/kernel/src/reporter.ts

Initial round of fixing lining warnings in `@aurelia/kernel`.
There are still warnings left, but they require a more intimate knowledge of the code that I don't yet have, so I'll pick those up once I have the feeling I'm ready for that.
Related to #249

style(kernel): fix some linting warnings

---

packages/jit/src/binding-command.ts
packages/jit/src/element-parser.ts
packages/jit/src/expression-parser.ts
packages/jit/src/semantic-model.ts
packages/jit/src/template-compiler.ts

Initial round of fixing lining warnings in `@aurelia/jit`.
There are still warnings left, but they require a more intimate knowledge of the code that I don't yet have, so I'll pick those up once I have the feeling I'm ready for that.
Related to #249

style(jit): fix some linting warnings

---

.circleci/config.yml
examples/jit-parcel-ts/.babelrc
examples/jit-parcel-ts/package.json
test/wdio/cases/dev/jit-parcel-ts/.babelrc
test/wdio/cases/dev/jit-parcel-ts/package.json
test/wdio/cases/latest/jit-parcel-ts/.babelrc
test/wdio/cases/latest/jit-parcel-ts/package.json
test/wdio/cases/local/jit-parcel-ts/.babelrc
test/wdio/cases/local/jit-parcel-ts/package.json

So much for "zero config" huh :)

chore(examples): fix jit-parcel-ts

---

packages/plugin-svg/src/svg-analyzer.ts

Initial round of fixing lining warnings in `@aurelia/plugin-svg`.
Related to #249
Manually imported the fixes from #257 (not included in the final PR).
Executed without errors:
- lerna run lint --scope=@aurelia/plugin-svg
- lerna run build
- lerna run test

style(plugin-svg): fix linting warnings

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md
docs/CONTRIBUTING.md

Minor fixes for language problems I happened across.

docs: minor fixes

---

test/browserstack/package-lock.json

This PR only syncs the package-lock.json dependencies under test/browserstack with the recent dev dep updates, so that browserstack ci build will work again
We kind of need to get rid of this package-lock.json to begin with, but that'll come next time I work on the e2e tests again

chore(browserstack): update package-lock.json

---

packages/jit/src/attribute-parser.ts
packages/jit/src/binding-command.ts
packages/jit/src/element-parser.ts
packages/jit/src/semantic-model.ts
packages/jit/src/template-compiler.ts
packages/kernel/src/di.ts

This PR is an initial step in preparation for turning on the tsconfig.json options `strictPropertyInitialization` and `strictNullChecks` (the latter must be turned on in conjunction with the former).
Principles I applied:
1. No constructor short-hands; all properties are declared on class level (not required by strict property rule)
2. No declaration short-hands; properties are exclusively assigned inside the constructor (not required by strict property rule)
3. All properties are assigned a value during construction (required by strict property rule)
4. Similar properties on similar classes are declared and assigned in the same order as much as possible (not required by strict property rule)
5. Properties that are assigned conditionally and are difficult to keep in the same order per …

Strict properties

---

packages/runtime/src/aurelia.ts
packages/runtime/src/binding/ast.ts

Follow up to #282, with a focus on AST.
Extends #282.
Tried to adhere to the principles of #282. Also snuck in a few typing/linting fixes.
Ran:
- `npm run lint` and no new linting warnings were reported.
- `npm run build` and no errors occured.
- `npm run test` and no tests failed.
See #282

refactor: changes to AST to help enable strictPropertyInitialization

---

.circleci/config.yml

9PM pacific for @EisenbergEffect  to get the merges in at better times :)

ci: move the nightly build 5 hours back

---

packages/runtime/src/binding/binding-context.ts
packages/runtime/src/binding/binding.ts
packages/runtime/src/binding/call.ts
packages/runtime/src/binding/collection-observer.ts
packages/runtime/src/binding/computed-observer.ts
packages/runtime/src/binding/dirty-checker.ts
packages/runtime/src/binding/element-observation.ts
packages/runtime/src/binding/event-manager.ts
packages/runtime/src/binding/expression-parser.ts
packages/runtime/src/binding/interpolation-binding.ts
packages/runtime/src/binding/let-binding.ts
packages/runtime/src/binding/listener.ts
packages/runtime/src/binding/observer-locator.ts
packages/runtime/src/binding/ref.ts
packages/runtime/src/binding/resources/binding-mode-behaviors.ts
packages/runtime/src/binding/resources/sanitize.ts
packages/runtime/src/binding/resources/signals.ts
packages/runtime/src/binding/resources/update-trigger-binding-behavior.ts
packages/runtime/src/binding/target-accessors.ts

Follow up to #282, with a focus on Binding.
Extends #282.
Tried to adhere to the principles of #282. Also snuck in a few typing/linting fixes.
n/a
See #282.

refactor(runtime): changes to Binding for strictPropertyInitialization

---

packages/runtime/src/dom.ts
packages/runtime/src/instructions.ts
packages/runtime/src/lifecycle.ts
packages/runtime/src/resource.ts
packages/runtime/src/templating/create-element.ts
packages/runtime/src/templating/lifecycle-render.ts
packages/runtime/src/templating/resources/compose.ts
packages/runtime/src/templating/resources/if.ts
packages/runtime/src/templating/resources/repeat.ts
packages/runtime/src/templating/resources/replaceable.ts
packages/runtime/src/templating/resources/with.ts
packages/runtime/src/templating/view.ts

Follow up to #282, with a focus on Templating.
Extends #282.
Tried to adhere to the principles of #282.
n/a
See #282.

refactor(runtime): changes to Templating for strictPropertyInitialization

---

packages/kernel/src/di.ts

Refactoring `kernel` to adhere to `strictNullChecks`.
Part of #254.
n/a.
Trust in CircleCI.
Do the other packages and turn the options on by default in the `tsconfig` files.

refactor(kernel): strictNullChecks fixes

---

packages/plugin-requirejs/src/processing.ts

Refactoring `plugin-requirejs` to adhere to `strictNullChecks`.
Part of #254.
n/a.
Trust in CircleCI.
Do the other packages and turn the options on by default in the `tsconfig` files.

refactor(plugin-requirejs): strictNullChecks fixes

---

packages/plugin-svg/src/svg-analyzer.ts

Refactoring `plugin-svg` to adhere to `strictNullChecks`.
Part of #254.
n/a.
Trust in CircleCI.
Do the other packages and turn the options on by default in the `tsconfig` files.

refactor(plugin-svg): strictNullChecks fixes

---

.circleci/config.yml

ci: do not include nonexisting top-level dist folder

---

.circleci/config.yml

Fixes a small typo in the CI job that merges to dev/release

ci: fix commit-dist script ref

---

.circleci/config.yml

Runs the exhaustive tests and merges the master branch (with built/bundled artifacts) to `dev` after every merge to master, instead of during the nightly. The nightly then only checks out `dev` and publishes that immediately to npm.
N/A
N/A
We will know if it works after merging this to master.. :)
N/A

ci: run merge_dist to dev job on merge to master

---

test/browserstack/package-lock.json
test/browserstack/package.json
test/browserstack/src/select/startup.ts
test/browserstack/src/todos/startup.ts

Fixes (or should fix) browserstack tests
CI failed on merge to master
See CircleCI after merge 😆 
Perhaps run browserstack again on every commit

chore(e2e): fix browserstack tests

---

packages/aot/test/setup.ts
packages/debug/test/setup.ts
packages/jit-html-browser/test/setup.ts
packages/jit-html-jsdom/test/setup-node.ts
packages/jit-pixi/test/setup.ts
packages/jit/test/setup-node.ts
packages/jit/test/setup.ts
packages/kernel/test/setup-node.ts
packages/kernel/test/setup.ts
packages/plugin-parcel/test/setup.ts
packages/plugin-requirejs/test/setup.ts
packages/plugin-svg/test/setup.ts
packages/plugin-webpack/test/setup.ts
packages/router/test/setup.ts
packages/runtime-html-browser/test/setup.ts
packages/runtime-html-jsdom/test/setup-node.ts
packages/runtime-pixi/test/setup.ts
packages/runtime/test/setup-node.ts
packages/runtime/test/setup.ts
packages/testing/test/setup.ts
packages/validation/test/setup.ts

Fixes up a few inconsistencies and removes things that were unnecessary in the test setup files
N/A
N/A
Existing tests must pass
N/A, standalone cleanup step

chore(all): cleanup/normalize setup files

---

packages/jit-html/test/integration/di-registrations.spec.ts

@jwx I can't seem to reproduce the problem you had with locally registered deps. Can you help me out here?
Just a couple of DI local dependency tests to get to the bottom of a router related issue

test(di): test local registrations

---

packages/jit-html/test/generated/template-compiler.mutations.basic.spec.ts
packages/jit-html/test/generated/template-compiler.static.if-else.double.spec.ts
packages/jit-html/test/generated/template-compiler.static.if-else.repeat.double.spec.ts
packages/jit-html/test/generated/template-compiler.static.if-else.repeat.spec.ts
packages/jit-html/test/generated/template-compiler.static.if-else.spec.ts
packages/jit-html/test/generated/template-compiler.static.spec.ts
packages/jit-html/test/integration/template-compiler.kitchen-sink.spec.ts
scripts/generate-tests/template-compiler.mutations.ts
scripts/generate-tests/util.ts

A couple of small linting fixes through the test generation scripts that slipped through the cracks in #382.
Follow up to #382.
n/a
CircleCI
n/a

refactor(jit-html): more linting fixes through test generation scripts

---

.circleci/config.yml
package.json
scripts/bump-version.ts
scripts/publish.ts

Update the versions before merging to the channel branch to keep the channel-specific branches in sync with what's published to npm, and also fix the nightly

ci: update package versions before merging

---

packages/kernel/src/index.ts
packages/kernel/src/path.ts
packages/kernel/test/path.spec.ts
packages/router/src/index.ts
packages/router/src/route-recognizer.ts
packages/router/test/unit/route-recognizer.spec.ts
packages/router/test/util.ts

This is an "as-is" port of `aurelia-path` and `route-recognizer`. Just to get the ball rolling. There is no integration yet.
- I added all `aurelia-path` functions even though only 2 of them are needed by `route-recognizer`. I added them as loose functions to the kernel so anything can use them, and they'll be tree-shaken if not used.
- Made an attempt to strongly type the `QueryParams` object from `aurelia-path` which proved to be a challenge.. @EisenbergEffect might want to chime in here as I believe you wrote them originally?
- `route-recognizer` is functionally still the same, which means it's not *entirely* ripe for use by vNext just yet (see next steps). The changes are:
- Replaced interfaces with classes (and objects with constructor calls) to make it all a bit more explicit
- …

Route recognizer

---

package-lock.json
package.json

@Vheissu FYI I'm removing cypress from the root package.json right now as it adds a significant amount of time to the install of the repo, which is a productivity killer in refactors when you need the occasional reinstall. Please add it somewhere underneath the `cypress` folder :)

chore(all): remove cypress from root package.json

---

packages/router/src/instruction-resolver.ts
packages/router/src/nav-route.ts
packages/router/src/nav.ts
packages/router/src/router.ts
packages/router/src/scope.ts
packages/router/src/viewport-content.ts
packages/router/src/viewport-instruction.ts
packages/router/src/viewport.ts
packages/router/test/e2e/doc-example/src/app.ts
packages/router/test/e2e/doc-example/src/components/authors/author.ts
packages/router/test/e2e/doc-example/src/components/books/book.ts
packages/router/test/unit/instruction-resolver.spec.ts
packages/router/test/unit/link-handler.spec.ts
packages/router/test/unit/nav.spec.ts
packages/router/test/unit/router.spec.ts

This PR contains the first part of the refactor towards viewport instruction and instruction resolver.
More work to be done, but what's done works. Except for running the linter, which doesn't work, but @fkleuver said he'd take a look at it.
- Continue refactor with part 2 (out of probably no more than 3)

Dynamic routing: refactor viewport instruction, part 1

---

packages/fetch-client/src/http-client.ts
packages/jit-html/src/template-compiler.ts
packages/jit-html/src/template-element-factory.ts
packages/jit-html/test/integration/di-registrations.spec.ts
packages/jit/src/attribute-parser.ts
packages/router/src/resources/viewport.ts
packages/router/src/router.ts
packages/runtime-html-browser/src/index.ts
packages/runtime-html-jsdom/src/index.ts
packages/runtime-html/src/dom.ts
packages/runtime-html/src/html-renderer.ts
packages/runtime-html/src/observation/observer-locator.ts
packages/runtime-html/src/resources/binding-behaviors/update-trigger.ts
packages/runtime-html/src/resources/custom-elements/compose.ts
packages/runtime-pixi/src/resources/custom-elements/pixi-app.ts
packages/runtime/src/lifecycle.ts
packages/runtime/src/observation/observer-locator.ts
packages/runtime/src/renderer.ts
packages/runtime/src/rendering-engine.ts
packages/runtime/src/resources/binding-behaviors/signals.ts
packages/runtime/src/resources/custom-attributes/if.ts
packages/runtime/src/resources/custom-attributes/repeat.ts
packages/runtime/src/resources/custom-attributes/replaceable.ts
packages/runtime/src/resources/custom-attributes/with.ts
packages/runtime/src/resources/value-converters/sanitize.ts
packages/runtime/test/au-dom.ts

Switch to using the recently introduced `InjectArray` for typing `public static readonly inject`.
This is part of #425, which had too many moving parts, so I'm splitting it up.
Self explanatory imho.
CircleCI
n/a

Use InjectArray

---

packages/jit-html/test/integration/repeat_weird.spec.tsx
packages/jit-html/test/integration/replaceable_yielding_replacement.spec.tsx
packages/jit-html/test/integration/replacement_yielding_replaceable.spec.tsx
packages/jit-html/test/integration/util.ts

More tricky usage of replaceable
N/A
N/A
N/A
More tests

chore(tests): add more replaceable tests

---

packages/router/src/configuration.ts
packages/router/src/index.ts
packages/router/src/router.ts
packages/router/test/e2e/doc-example/app/src/startup.ts

This PR adds basic configuration to the router.
Ignore everything in packages/router/test/e2e/** since they are just my own test applications while working.
- Re-visit scoped viewports

Dynamic routing: add configuration

---

test/cypress/README.md
test/cypress/package.json

add e2eci headless script option

---

packages/__tests__/jit-html/replaceable_repeat.spec.tsx
packages/__tests__/jit-html/replaceable_with.spec.tsx
packages/__tests__/jit-html/replaceable_yielding_replacement.spec.tsx
packages/jit-html/src/template-binder.ts
packages/jit/src/semantic-model.ts
packages/runtime/src/observation/binding-context.ts
packages/runtime/src/resources/custom-attributes/repeat.ts
packages/runtime/src/templating/controller.ts

fix(replaceable): more scoping fixes, enable most of bigopon's tests

---

packages/__tests__/router/e2e/navigation-skeleton/app/index.ejs
packages/__tests__/router/e2e/navigation-skeleton/app/package.json
packages/__tests__/router/e2e/navigation-skeleton/app/src/app.html
packages/__tests__/router/e2e/navigation-skeleton/app/src/app.ts
packages/__tests__/router/e2e/navigation-skeleton/app/src/utils.ts
packages/__tests__/router/e2e/navigation-skeleton/app/webpack.config.js

This PR contains the interim css edition of the (not yet fully functional) navigation skeleton. Basically, it just adds css to the navigation skeleton.
Ignore everything in `packages/router/test/e2e/**` since they are just my own test applications while working. In fact, the interim nature of this PR means there's probably not that much to actually review.

Dynamic routing: Navigation skeleton, interim css edition

---

packages/router/src/nav.ts
packages/router/src/resources/nav.ts
packages/router/src/router.ts

This PR makes it possible to customize classes used by au-nav.
Ignore everything in `packages/router/test/e2e/**` since they are just my own test applications while working. _I need to add tests_, but am submitting this now anyway since there are developers urgently waiting for it. 

Dynamic routing: customizeable au-nav classes

---

packages/__tests__/router/e2e/doc-example/app/src/app.ts
packages/__tests__/router/e2e/doc-example/app/src/components/authors/author.ts
packages/router/src/resources/nav.ts

This PR makes the title for nav use innerhtml.
Ignore everything in `packages/router/test/e2e/**` since they are just my own test applications while working. _I need to add tests_, but am submitting this now anyway since there are developers urgently waiting for it. 

Dynamic routing: use innerhtml in nav title

---

packages/__tests__/plugin-conventions/preprocess.spec.ts
packages/__tests__/plugin-gulp/index.spec.ts
packages/__tests__/webpack-loader/loader.spec.ts
packages/plugin-conventions/src/index.ts
packages/plugin-conventions/src/preprocess-html-template.ts
packages/plugin-conventions/src/preprocess.ts
packages/plugin-conventions/tsconfig.json
packages/plugin-gulp/package.json
packages/plugin-gulp/src/index.ts
packages/webpack-loader/package.json
packages/webpack-loader/src/index.ts

Push down common logic to base package plugin-conventions.

refactor conventions implementation to avoid duplicated code

---

packages/__tests__/plugin-conventions/preprocess.spec.ts
packages/plugin-conventions/src/preprocess.ts
packages/plugin-gulp/src/index.ts

It's caused by vinyl file.relative is not relative to current working dir.

fix(plugin-gulp): fix html pair checking in plugin-gulp

---

packages/__tests__/runtime-html/target-observers.spec.ts
packages/runtime-html/src/observation/class-attribute-accessor.ts

- Add the ability to bind an object to class and check value of each property and if true then add
the property name to the class list.
- Fixed an issue when binding a class list with an empty string at the end by changing the regex to match instead of string split. (Minor perf improvement as well)
N/A
N/A
Added additional tests to cover different scenarios when binding an object.
E2E tests need added.

feat(observer): Add the ability to bind an object to class

---

docs/user-docs/1. getting-started/2. building-a-todo-app.md

Another simple (but funny) typo

---

docs/user-docs/1. getting-started/14. building-a-dashboard-app.md

Simple (but funny) typo

---

README.md

docs(readme): Aurelia 2

---

docs/user-docs/5. examples/2.bind-to-element-size.md

Add some example doc for creating an attribute to observe element sizing.
N/A
N/A
N/A
N/A

chore(example): doc: add element size binding example

---

packages/__tests__/package.json
packages/__tests__/router/configuration.spec.ts
packages/router/src/configuration.ts
packages/router/src/instruction-resolver.ts

This PR implements configuration customization. While not pretty, it works pending a better implementation.
Ignore everything in `packages/router/test/e2e/**` since they are just my own test applications while working. 
- Make sure new as well as existing tests pass.

Dynamic routing: configuration customization

---

docs/user-docs/1. getting-started/3. displaying-basic-data.md
packages/__tests__/jit-html/blur.integration.spec.ts
packages/__tests__/jit-html/blur.spec.ts
packages/__tests__/jit-html/blur.unit.spec.ts
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/resources/custom-attributes/blur.ts

Add blur custom attribute as an official attribute resource
N/A
Timing in redundant check guard debounce behavior
Cover all combination of bindables of blur custom attribute
More tests with focus/blur combined

feat(blur): blur attribute

---

packages/__tests__/e2e/src/plugins/sut-i18n.ts
packages/__tests__/i18n/i18n.spec.ts
packages/i18n/src/i18n-configuration-options.ts
packages/i18n/src/i18n.ts

- Disabled relative time formatting test for single week
- Corrected e2e tests. Missed changed during last minute changes in
PR #563

fix(i18n): fixed i18n related CI issues

---

docs/user-docs/2. app-basics/20. internationalization.md

docs(i18n): bunch of fixes

---

packages/__tests__/router/e2e/doc-example/app/src/app.ts
packages/__tests__/router/e2e/doc-example/app/src/components/authors/author.ts
packages/__tests__/router/e2e/doc-example/app/src/components/books/book.ts
packages/__tests__/router/e2e/doc-example/app/src/components/chat/chat.ts
packages/__tests__/router/e2e/doc-example/app/src/components/main.ts
packages/__tests__/router/instruction-resolver.spec.ts
packages/__tests__/setup-browser-router.ts
packages/router/src/guard.ts
packages/router/src/instruction-resolver.ts
packages/router/src/scope.ts
packages/router/src/viewport-instruction.ts
packages/router/src/viewport.ts

This PR fills most of the (intentionally ignored) holes in the viewport instruction resolver.
- Add new tests with more complex instructions.

refactor(router): improve viewport instruction resolver

---

packages/__tests__/jit-html/template-compiler.primary-bindable.spec.ts
packages/jit-html/src/template-binder.ts
packages/jit/src/resource-model.ts
packages/runtime/src/definitions.ts

Add `primary` to `@bindable`
At the moment, `@bindable` on custom attribute does not respect `primary` configuration, making it sometimes tedious to write complex attributes.
Number of test cases does not seem enough, but I feel it's good for now.
N/A
Incorporate real world usage of complex attributes into tests

fix(bindable-primary): cleanup debug code, add more tests

---

packages/__tests__/runtime-html/styles.spec.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/projectors.ts
packages/runtime-html/src/styles/shadow-dom-styles.ts
packages/runtime-html/src/styles/style-configuration.ts

I made a booboo when I implemented shadow dom shared styles. This PR fixes both the tests and the implementation.
This is an urgent fix for real apps that are broken without this.

fix(styles): proper local vs. global style resolution

---

package-lock.json
package.json
packages/__tests__/plugin-conventions/preprocess-resource.spec.ts
packages/plugin-conventions/package.json

@EisenbergEffect pls merge this fix.

fix(plugin-conventions): upgrade modify-code to fix a preprocess bug

---

packages/__tests__/runtime-html/target-observers.spec.ts
packages/runtime-html/src/observation/style-attribute-accessor.ts

Kebab case property names ✅
Allow arrays of string, objects, or arrays nested n levels ✅
```html
<div style='display:block;' style.bind="styles"></div>
```
Examples
```ts
get styles(){
return { backgroundColor:'red'}
}
get styles(){
return { backgroundColor:'red', height: '35px'}
}
get styles(){
return [{ backgroundColor:'red', height: '35px'}, 'border-color:black']
}
get styles(){
return [{ ['background-color']:'red', height: '35px'}, 'border-color:black']
}
get styles(){
return [{ backgroundColor:'red', height: '35px'},
'border-color:black',
['padding-left:10px', {paddingRight: '10px' }]
]
}
```
This allows more open ended instructions to be passed along to the style binding which results in more capabilities especially when style.bind from the parent needs to be concatenated with …

feat(runtime-html): Enhance the style accessor

---

packages/__tests__/kernel/platform.spec.ts
packages/__tests__/plugin-conventions/name-convention.spec.ts
packages/__tests__/plugin-conventions/preprocess-html-template.spec.ts
packages/__tests__/plugin-conventions/strip-meta-data.spec.ts
packages/kernel/src/functions.ts

Update camel/kebabCase to cover more edge cases.
This new camel/kebabCase ensures we can map UAFoo.html and class UAFoo to `<ua-foo>`.

fix(kernel): cover more edge cases in camel/kebabCase

---

packages/__tests__/runtime/array-observer.spec.ts
packages/runtime/src/index.ts
packages/runtime/src/observation/array-observer.ts
packages/runtime/src/resources/custom-attributes/repeat.ts

Fixes cases where 0 or 1 arguments are passed into `splice` would not be observed properly.

fix(array-observer): fix splice edge case

---

docs/user-docs/getting-started/displaying-basic-data.md

Fix: Text and code example did not match.

Fix documentation error

---

packages/__tests__/kernel/eventaggregator.spec.ts
packages/__tests__/router/browser-navigator.spec.ts
packages/kernel/src/eventaggregator.ts

Change the signature of the interface to match the implementation.
Change the tests to use the interface
Change the implementation to use the interface
]
Tapped on to existing tests by updating them to use the interface.

refactor(event-agg): Change interface signature

---

docs/user-docs/app-basics/internationalization.md

fix(docs-i18n): removed file name from code block

---

docs/user-docs/app-basics/internationalization.md

Missed one code block earlier.

fix(i18n-docs): removed last code-block file name

---

packages/__tests__/jit-html/template-compiler.convention.spec.ts
packages/jit-html/src/html-attribute-syntax-transformer.ts

Add `inputmode` -> `inputMode` mapping
N/A
N/A
N/A
N/A

fix(convention): map inputmode -> inputMode

---

examples/jit-pixi-webpack-ts/src/app.html
packages/__tests__/jit-html/generated/template-compiler.static.if-else.double.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.if-else.repeat.double.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.if-else.repeat.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.if-else.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.spec.ts
packages/__tests__/jit-html/replaceable.spec.ts
packages/__tests__/jit-html/replaceable_repeat.spec.tsx
packages/__tests__/jit-html/replaceable_with.spec.tsx
packages/__tests__/jit-html/replaceable_yielding_replacement.spec.tsx
packages/__tests__/jit-html/template-compiler.spec.ts
packages/__tests__/jit-html/tracing.spec.ts
packages/__tests__/runtime/controller.spec.ts
packages/jit-html/src/template-binder.ts
packages/jit/src/semantic-model.ts
packages/plugin-pixi/src/resources/custom-elements/pixi-app.ts
scripts/generate-tests/template-compiler.static.ts
test/realworld/src/resources/elements/article-preview.html
test/realworld/src/shared/buttons/favorite-button.html

Fixes https://github.com/aurelia/aurelia/issues/631

refactor(replaceable): rename 'replace-part' to 'replace' and 'replaceable part' to 'replaceable'

---

README.md

Found and corrected a typo in the first paragraph.
Just a minor typo correction to the first paragraph of the readme.
- N/A

Corrected a typo in the readme documentation

---

packages/__tests__/jit-html/template-compiler.ce_and_surrogate.spec.ts
packages/__tests__/jit-html/template-compiler.spec.ts
packages/jit-html/src/template-compiler.ts
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/definitions.ts
packages/runtime-html/src/html-renderer.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/instructions.ts

At the moment, class/style on surrogate always override their existing corresponding attrs on host, add in more harmony manner
N/A
N/A
N/A
N/A

Fix surrogate instruction

---

.eslintrc.js
test/browserstack/browserstack.conf.ts
test/js-framework-benchmark/build.js
test/js-framework-benchmark/cleanup.js
test/js-framework-benchmark/configureStyles.js
test/js-framework-benchmark/copy.js
test/js-framework-benchmark/frameworks/keyed/aurelia/aurelia_project/generators/component.ts
test/js-framework-benchmark/frameworks/keyed/aurelia/src/app.ts
test/js-framework-benchmark/frameworks/keyed/aurelia/src/aurelia-polyfills.js
test/js-framework-benchmark/frameworks/keyed/aurelia/src/store.ts
test/js-framework-benchmark/frameworks/keyed/aurelia/types/system.d.ts
test/js-framework-benchmark/frameworks/keyed/aurelia2-local/src/app.ts
test/js-framework-benchmark/frameworks/keyed/aurelia2-local/src/source.ts
test/js-framework-benchmark/frameworks/keyed/aurelia2-npm/src/app.ts
test/js-framework-benchmark/frameworks/keyed/aurelia2-npm/src/source.ts
test/js-framework-benchmark/frameworks/keyed/vanillajs/src/Main.js
test/js-framework-benchmark/frameworks/keyed/vanillajs/webpack.config.js
test/js-framework-benchmark/results-ui/src/build.js
test/js-framework-benchmark/results-ui/src/ui.js
test/js-framework-benchmark/webdriver-ts-results/webpack.config.js
test/js-framework-benchmark/webdriver-ts/src/buildDockerFrameworks.ts
test/js-framework-benchmark/webdriver-ts/src/forkedBenchmarkRunner.ts
test/js-framework-benchmark/webdriver-ts/src/isKeyed.ts
test/js-framework-benchmark/webdriver-ts/src/rebuild.ts
test/js-framework-benchmark/webdriver-ts/src/updateFrameworks.ts
test/js-framework-benchmark/webdriver-ts/src/webdriverAccess.ts

Switch on the `no-var` rule and fixed violations
n/a
Done automatically through `eslint --fix` and I did a spot check afterwards.
CircleCI
More linting

chore: lint no-var

---

examples/jit-pixi-webpack-ts/webpack.config.js
packages/__tests__/jit-html/focus.spec.ts
packages/__tests__/karma.conf.js
packages/__tests__/router/e2e/layouts/gulpfile.js
packages/__tests__/router/e2e/modules/gulpfile.js
packages/examples/dbmonster-b/lib/memory-stats.js
packages/examples/requirejs/view.js
packages/jit/src/expression-parser.ts
packages/testing/src/h.ts
packages/testing/src/specialized-assertions.ts
test/1kcomponents/app-double.js
test/1kcomponents/app.js
test/js-framework-benchmark/webdriver-ts-results/webpack.config.js
test/js-framework-benchmark/webdriver-ts/src/common.ts

Fixes a bunch of issues as reported by [Deepscan](https://deepscan.io/dashboard/#view=project&tid=3446&pid=5117&bid=39795&subview=issues)
n/a
Minor fixes all over the place. I think they're self explanatory, but feel free to ask (or look at the Deepscan overview) for details.
CircleCI
More linting

chore: fix Deepscan issues

---

packages/__tests__/tasks/copy-html.js

fix(tests): build issue correction

---

packages/aurelia/src/index.ts

@fkleuver please especially review the exports of Scheduler/TaskQueue.

chore(aurelia): update re-exports list to match latest code

---

package.json
scripts/bump-version.ts
scripts/change-package-refs.ts
scripts/change-tsconfigs.ts
scripts/generate-changelog.ts
scripts/project.ts
test/grid/package.json
test/js-framework-benchmark/webdriver-ts/src/createIndex.ts
test/js-framework-benchmark/webdriver-ts/src/webdriverAccess.ts
test/kitchen-sink/src/app.ts

chore: fix function-call-argument-newline violations

---

package-lock.json
package.json
packages/__tests__/package.json
scripts/logger.ts
test/browserstack/package.json
test/browserstack/specs/logger.ts

Partially fixes the issues in #756, by manually doing the update to `chalk@^3.0.0`
* #756
Update to `chalk@^3.0.0` and tweak the code to accommodate for the breaking changes in that update.
CircleCI
n/a

chore: update chalk to 3.0.0

---

packages/runtime/src/resources/custom-attributes/repeat.ts

Fixes a memory leak discovered by @brandonseydel

fix(repeat): unsubscribe from array observer when unbinding

---

packages/__tests__/5-jit-html/injectable.spec.ts
packages/__tests__/5-jit-html/template-compiler.spec.ts
packages/runtime/src/render-context.ts
packages/runtime/src/rendering-engine.ts
packages/runtime/src/resources/custom-element.ts
packages/runtime/src/templating/controller.ts

Adds a new api that allows you to create an injection token for custom element instances so that you can inject the parent instance into a child, even recursively into itself.
This works by telling the rendering engine to not cache anything when the `injectable` property is specified, which may incur a large performance penalty on large components that require compilation because it will cause it to be re-compiled on every render. So, use with care.
However, for cheap-to-compile components (or those that don't have a template at all, such as `au-viewport` and `au-compose`), this should be fine.
Usage:
```ts
export const IMyElement = CustomElement.createInjectable();
@customElement({
name: 'my-element',
template: '<my-element-child></my-element-child>'
injectable: IMyElement
})
export …
```

feat(runtime): add CustomElement.createInjectable api

---

packages/i18n/src/t/translation-binding.ts
packages/runtime-html/src/binding/attribute.ts
packages/runtime-html/src/binding/listener.ts
packages/runtime-html/src/html-renderer.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/call-binding.ts
packages/runtime/src/binding/interpolation-binding.ts
packages/runtime/src/binding/let-binding.ts
packages/runtime/src/binding/property-binding.ts
packages/runtime/src/binding/ref-binding.ts
packages/runtime/src/index.ts
packages/runtime/src/lifecycle.ts
packages/runtime/src/renderer.ts
packages/runtime/src/resources/binding-behavior.ts
packages/runtime/src/resources/binding-behaviors/debounce.ts
packages/runtime/src/resources/binding-behaviors/throttle.ts
packages/testing/src/mocks.ts

POC for formalizing the BindingBehavior api to avoid monkey patching.

Binding behavior api improvements

---

lerna.json
packages/au/.npmrc
packages/au/CHANGELOG.md
packages/au/LICENSE
packages/au/README.md
packages/au/bin/au.js
packages/au/package.json
packages/au/src/index.ts
packages/au/tsconfig.json
packages/tsconfig.json

add 'au' cli package boilerplate

---

packages/__tests__/5-jit-html/template-compiler.ref.spec.ts
packages/runtime/src/templating/controller.ts

fix(controller): correct the timing of beforeBind hook

---

lerna.json
packages/__tests__/package.json
packages/__tests__/setup-browser.ts
packages/__tests__/web-components/index.spec.ts
packages/tsconfig.json
packages/web-components/.npmrc
packages/web-components/CHANGELOG.md
packages/web-components/LICENSE
packages/web-components/README.md
packages/web-components/package.json
packages/web-components/src/index.ts
packages/web-components/tsconfig.json

Per @EisenbergEffect's request

Add @aurelia/web-components package

---

packages/__tests__/i18n/i18n.spec.ts
packages/i18n/src/i18n.ts

fix(i18n): bypassed tests for February

---

docs/user-docs/app-basics/cross-component-communication.md

Adding docs as per @EisenbergEffect's comment in this [discourse](https://discourse.aurelia.io/t/how-to-use-event-aggregator-as-transient-with-custom-element/3181/42?u=ghiscoding) post.

docs(eventAggregator): add doc for Cross-Component Communication page

---

docs/user-docs/app-basics/internationalization.md
packages/__tests__/i18n/df/date-format-value-converter.spec.ts
packages/__tests__/i18n/i18n.spec.ts
packages/__tests__/i18n/t/translation-integration.spec.ts
packages/__tests__/package.json
packages/i18n/src/t/translation-binding.ts

related PR from v1 https://github.com/aurelia/i18n/pull/314

I18n zero undefined null

---

docs/user-docs/app-basics/app-configuration-and-startup.md

Try to fix few Markdown syntax errors

---

lerna.json
packages/kernel/src/di.ts
packages/kernel/src/index.ts
packages/kernel/src/resource.ts
packages/metadata/.npmrc
packages/metadata/CHANGELOG.md
packages/metadata/LICENSE
packages/metadata/README.md
packages/metadata/package.json
packages/metadata/src/index.ts
packages/metadata/tsconfig.json
packages/tsconfig.json
scripts/project.ts

Metadata itself has no dependencies and could easily be useful as a standalone package, so for this reason as well as to maintain some degree of consistency with v1, it'll go back to its own package now.

move metadata to separate package

---

packages/babel-jest/package.json
packages/ts-jest/package.json
packages/validation-html/package.json

@fkleuver few out of synced deps due to PRs created before you upgrade typescript.

chore(babel-jest,ts-jest,validation-html): update out of synced deps

---

.vscode/launch.json
packages/__tests__/validation-html/subscribers/validation-container-custom-element.spec.ts
packages/__tests__/validation-html/subscribers/validation-errors-custom-attribute.spec.ts
packages/__tests__/validation-html/validate-binding-behavior.spec.ts
packages/validation-html/src/validate-binding-behavior.ts

In `validate` BB, made the scoped IValidationController optional.

fix(validation): optional IValidationController

---

packages/kernel/src/di.ts
packages/runtime/src/templating/render-context.ts
packages/validation-html/src/configuration.ts

fix(di): registerFactory #822

---

packages/router/src/browser-navigator.ts
packages/router/src/browser-viewer-store.ts
packages/router/src/collection.ts
packages/router/src/found-route.ts
packages/router/src/hook-manager.ts
packages/router/src/hook.ts
packages/router/src/lifecycle-logger.ts
packages/router/src/link-handler.ts
packages/router/src/nav-route.ts
packages/router/src/nav.ts
packages/router/src/navigator.ts
packages/router/src/parser.ts
packages/router/src/queue.ts
packages/router/src/router.ts
packages/router/src/scope.ts
packages/router/src/task-queue.ts
packages/router/src/utils.ts
packages/router/src/viewport-content.ts
packages/router/src/viewport-instruction-collection.ts
packages/router/src/viewport-instruction.ts
test/navigation-skeleton/app/src/app.html

This PR adds triage comments.
- Continue with configuration api
- Fully implement guards/hooks
- Fully implement unknown routes/components
- Add navigation events
- Make `goto` listen to navigation events instead of observing
- Fix `realworld`
- Fix proper sync/async for lifecycle hooks
- Add tests for the new `au-nav` options
- Review controller parent …

docs(router): add triage comments

---

docs/user-docs/app-basics/components-revisited.md

Added in the documentation for HTML custom elements, including how to specify bindable properties and change the binding mode.

docs(app-basics): html only custom elements

---

README.md

Add a badge for discord to make it easier to prompt folks to join the chat room.

chore(doc): add discord badge

---

docs/user-docs/routing/router-hooks.md

Change wording of whitelist to allow list and blacklist to deny list.

docs(router): change wording

---

.github/workflows/main.yml

@bigopon would prefer to not have github actions run twice on a pull request.

remove pull_request

---

packages/__tests__/2-runtime/binding-mode-behaviors.spec.ts
packages/__tests__/2-runtime/signaler.spec.ts
packages/__tests__/3-runtime-html/kitchen-sink.spec.ts
packages/__tests__/3-runtime-html/signaler.integration.spec.ts
packages/runtime/src/index.ts
packages/runtime/src/observation/signaler.ts
packages/runtime/src/resources/binding-behaviors/binding-mode.ts
packages/runtime/src/resources/binding-behaviors/signals.ts

Signal binding behavior some how wasn't updated during au slot PR. This pr fixes it.

fix(signal): update host scope, add interface to guard refactoring

---

docs/user-docs/getting-started/conditional-rendering.md

Fixed some oddities in the switch doc.

docs(switch): corrections

---

packages/__tests__/babel-jest/index.spec.ts
packages/__tests__/plugin-conventions/preprocess-html-template.spec.ts
packages/__tests__/plugin-conventions/preprocess-resource.spec.ts
packages/__tests__/plugin-conventions/preprocess.spec.ts
packages/__tests__/ts-jest/index.spec.ts
packages/plugin-conventions/src/preprocess-html-template.ts
packages/plugin-conventions/src/preprocess-resource.ts

Fix conventions

---

packages/platform-browser/src/index.ts
packages/platform/src/index.ts

Instead of eagerly crashing when some globals are missing (such as `fetch` and `queueMicroTask`), fall back to using a function that only throws when it's actually used.
@3cp will verify this in the jest setup.
We'll be working to bring more e2e test setups into this repo as part of finalizing the testing package.

Platform fix

---

packages/platform-browser/src/index.ts
packages/platform/src/index.ts

fix(platform): remove dom-specific type deps

---

packages/__tests__/3-runtime-html/template-binder.au-slot.spec.ts
packages/runtime-html/src/binding/attribute.ts
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/observation/attribute-ns-accessor.ts
packages/runtime-html/src/observation/checked-observer.ts
packages/runtime-html/src/observation/class-attribute-accessor.ts
packages/runtime-html/src/observation/data-attribute-accessor.ts
packages/runtime-html/src/observation/element-attribute-observer.ts
packages/runtime-html/src/observation/element-property-accessor.ts
packages/runtime-html/src/observation/select-value-observer.ts
packages/runtime-html/src/observation/style-attribute-accessor.ts
packages/runtime-html/src/observation/value-attribute-observer.ts
packages/runtime-html/src/resources/template-controllers/flags.ts
packages/runtime/src/binding/interpolation-binding.ts
packages/runtime/src/binding/property-binding.ts
packages/runtime/src/observation.ts
packages/runtime/src/observation/array-observer.ts
packages/runtime/src/observation/collection-length-observer.ts
packages/runtime/src/observation/collection-size-observer.ts
packages/runtime/src/observation/map-observer.ts
packages/runtime/src/observation/primitive-observer.ts
packages/runtime/src/observation/property-accessor.ts
packages/runtime/src/observation/set-observer.ts
packages/runtime/src/observation/setter-observer.ts

Continue my cleanup effort to remove some cruft.

Refactor/cleanup accessors + observers

---

packages/runtime-html/src/resources/template-controllers/switch.ts

To have more synchronous determinism.

chore(switch): got rid of the async case change handler

---

packages/__tests__/3-runtime-html/attr-binding-behavior.spec.ts
packages/__tests__/3-runtime-html/checked-observer.spec.ts
packages/__tests__/3-runtime-html/target-observers.spec.ts
packages/i18n/src/t/translation-binding.ts
packages/runtime-html/src/binding/attribute.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/observation/attribute-ns-accessor.ts
packages/runtime-html/src/observation/checked-observer.ts
packages/runtime-html/src/observation/data-attribute-accessor.ts
packages/runtime-html/src/observation/element-property-accessor.ts
packages/runtime-html/src/observation/observer-locator.ts
packages/runtime-html/src/resources/binding-behaviors/attr.ts
packages/runtime/src/binding/interpolation-binding.ts
packages/runtime/src/binding/property-binding.ts
packages/runtime/src/index.ts
packages/runtime/src/observation.ts

Continue the refactoring for observation, making most of the accessors static.

Refactor/el observation: more static accessors

---

packages/__tests__/3-runtime-html/controller.hook-timings.integration.spec.ts

This PR adds additional log detail to make the controller test assertions more precise.
Also adds a few high-level smoke tests that should make it a bit easier for folks to see what's going on (without having to reverse-engineer the generated specs etc).
The assertions in those smoke tests may be useful for advanced docs that go into more detail on how the lifecycle hooks interact.
@jwx the parallel swap test you asked for can be found here: https://github.com/aurelia/aurelia/compare/controller-tests?expand=1#diff-ac7303ff9a1cd358311d54ef1b3716510a3ffbda18c94a03a0ca7c2cdd591377R1618

Add more controller tests

---

packages/__tests__/3-runtime-html/interpolation.spec.ts
packages/runtime-html/src/observation/observer-locator.ts

checking properties to override accessor with observer should always be based on element tag names

fix(observer-loc): new api for overriding accessors

---

docs/user-docs/examples/integration/ms-fast.md

Try fix cross section link for doc

docs(integration): try fix lint between sections

---

docs/user-docs/getting-started/components/watching-data.md

Corrected some typos on the watch decorator docs page

docs(watching-data): Fixed typos

---

packages/__tests__/3-runtime-html/controller.hook-timings.integration.spec.ts
packages/__tests__/router/router.spec.ts
packages/router/src/viewport-content.ts
packages/runtime-html/src/templating/controller.ts

This PR improves the way lifecycle hook invocations are connected. Now uses a synchronous stack mechanism that completely eliminates additional overhead incurred from having async hooks. This improves performance with async hooks and also makes it much easier to deeply verify hook invocation order in complex integration tests internally (the difficulty of which is what triggered this change in the first place).

Controller async optimizations

---

docs/user-docs/examples/integration/ms-fast.md

In order to properly observe FAST elements, we must also listen to `input` events

docs(integration-fast): also listen to input event

---

packages/aurelia/src/index.ts
packages/fetch-client/src/http-client.ts
packages/fetch-client/src/index.ts

For the `@IHttpClient` parameter decorator

Add missing IHttpClient interface to fetch-client package

---

packages/__tests__/router/__route-recognizer.spec.ts
packages/route-recognizer/package.json
packages/route-recognizer/src/index.ts

- Fix empty path `''` routes (allow them to be added as well as recognized)
- Fix the negative match tests
- Add a recognize result cache for better perf (cache is invalidated whenever new routes are added, for safety)
- Remove the responsibilities w.r.t. query strings - stripping off the query string becomes the responsibility of the router.

Route recognizer fixes

---

packages/aurelia/src/index.ts
packages/runtime-html/src/index.ts

The `watch` decorator was previously only exported on the`@aurelia/runtime` package. It is now reexported to the top level `aurelia` package.
--
--
--
--
Appropriately check exports with tests

refactor(runtime): reexport watch on aurelia package

---

test/benchmarking-apps/runner/src/run-benchmarks.ts
test/benchmarking-apps/runner/src/shared.ts
test/benchmarking-apps/viewer/client/.npmrc
test/benchmarking-apps/viewer/client/package.json
test/benchmarking-apps/viewer/client/src/components/app-shell.css
test/benchmarking-apps/viewer/client/src/components/app-shell.html
test/benchmarking-apps/viewer/client/src/components/app-shell.ts
test/benchmarking-apps/viewer/client/src/components/left-sidebar.css
test/benchmarking-apps/viewer/client/src/components/left-sidebar.html
test/benchmarking-apps/viewer/client/src/components/left-sidebar.ts
test/benchmarking-apps/viewer/client/src/index.html
test/benchmarking-apps/viewer/client/src/index.ts
test/benchmarking-apps/viewer/client/src/pages/measurements/data.ts
test/benchmarking-apps/viewer/client/src/pages/measurements/index.css
test/benchmarking-apps/viewer/client/src/pages/measurements/index.html
test/benchmarking-apps/viewer/client/src/pages/measurements/index.ts
test/benchmarking-apps/viewer/client/src/resources.d.ts
test/benchmarking-apps/viewer/client/tsconfig.json
test/benchmarking-apps/viewer/client/webpack.config.js
test/benchmarking-apps/viewer/server/.eslintignore
test/benchmarking-apps/viewer/server/.eslintrc.js
test/benchmarking-apps/viewer/server/.npmrc
test/benchmarking-apps/viewer/server/package.json
test/benchmarking-apps/viewer/server/src/index.ts
test/benchmarking-apps/viewer/server/tsconfig.json

Adds the branch name and commit hash as metadata to the measurements.
Adds a simple data viewer server + client app as an initial effort to make the benchmark results presentable. This app is publicly available at https://au2-bench-viewer.azurewebsites.net/
The source code for the server & client is located under `test/benchmark-apps/viewer`.
At this stage I did not want to put any more time/effort into this than to strictly get the bare minimum working, so for example deployment still needs to be done manually by me. The client can be developed locally without the server, by pointing the fetch client config to `https://au2-bench-viewer.azurewebsites.net/api/`
FYI @bigopon @Sayan751

benchmark updates

---

.circleci/config.yml
package.json
scripts/change-package-refs.ts

Fix the dev release

---

packages/__tests__/router/ast.spec.ts
packages/router/src/instructions.ts
packages/router/src/route-expression.ts
packages/router/src/route-tree.ts
packages/router/src/router.ts

fix(router): querystring

---

packages-cjs/__tests__/plugin-conventions/strip-meta-data.spec.ts
packages-cjs/plugin-conventions/src/strip-meta-data.ts

fix(conventions): skip local template, leave it to runtime

---

docs/user-docs/examples/integration/ms-fast.md

Related to https://github.com/microsoft/fast/issues/4182

Fix FAST integration doc

---

docs/user-docs/app-basics/custom-attributes.md

Small grammar and flow improvements to **docs/user-docs/app-basics/custom-attributes.md**.
Part of a series of first PR to aurelia, for this author.

docs: Improves grammar and small flow changes for custom-attributes.md

---

docs/user-docs/app-basics/securing-an-app.md

Small grammar and flow improvements to **docs/user-docs/app-basics/securing-an-app.md**.
Part of a series of first PR to aurelia, for this author.

docs: Improves grammar and small flow changes for securing-an-app.md

---

docs/user-docs/app-basics/internationalization.md

Small grammar and flow improvements to **docs/user-docs/app-basics/securing-an-app.md**.
Part of a series of first PR to aurelia, for this author.
Linking #1111 to be completed after this is approved. 
Please, see related issue. This may be only the first of a series of updates for this topic. 
And, apologies for the rather large diff. I couldn't think of an obvious way to split this up, other than arbitrarily cutting this off at the middle and splintering the review, which is probably less than optimal. So...here we are 😅

docs: Improves grammar and small flow changes for internationalization.md

---

docs/user-docs/routing/component-configured-routing.md

syntax error

---

docs/user-docs/getting-started/template-syntax.md

Missing equal signs in code blocks for docs

Missing equal signs in code blocks docs

---

docs/user-docs/getting-started/components/README.md

Components revisited link was broken

Fixed broken link

---

packages-cjs/__tests__/plugin-conventions/name-convention.spec.ts
packages-cjs/__tests__/plugin-conventions/preprocess-resource.spec.ts
packages-cjs/plugin-conventions/src/name-convention.ts

fix(plugin-conventions): accept class FooBarCustomElement convention

---

packages/__tests__/3-runtime-html/binding-resources.spec.ts
packages/runtime-html/src/binding-behaviors/debounce.ts
packages/runtime-html/src/binding-behaviors/throttle.ts

use 200ms delay for debounce and throttle when no parameter is provided
fixes aurelia#1150

fix(debounce): respect default delay

---

packages/runtime/src/binding/connectable.ts

In a previous refactor, open observer slot number were merged into observer count, and causing inaccuracy in marking empty slot. This PR fixes this.
A repro of this is at https://github.com/markusrut/aurelia-example/tree/1bedcbaf2a0c9b7c72043df3e0ae578145023f77
thanks to @markusrut : Clicking reload 100 times + select an item shouldn't cause increasing time required for each selected item computation.
Probably should just use a Map instead of this. Though it would lead to higher mem usage & possibly worse perf in simpler scenarios

fix(obs-record): separate count & slot number

---

docs/user-docs/app-basics/internationalization.md

Hi! I updated the docs so it works with latest version of copy-webpack-plugin (8.1.1).
example:
https://github.com/webpack-contrib/copy-webpack-plugin

docs(internationalization.md): fix config for copy-webpack-plugin

---

docs/user-docs/app-basics/working-with-form-elements.md

Add a small section for some standard handling with `<form/>` element. Thanks @akircher
@akircher : Please help create PR to add whatever missing, or inaccurate.

chore(doc): add working-with-form/submission section

---

docs/user-docs/examples/integration/ms-fast.md

Fixed the url for extending templating syntax to point to: https://docs.aurelia.io/app-basics/extending-templating-syntax

Update to ms-fast.md - fixed url for extending templating syntax

---

docs/user-docs/plugins/dialog/README.md
packages/runtime-html/src/templating/dialog/dialog-configuration.ts

Fixes a typo in previous PR related to export name. Thanks @pkozul

chore(dialog): fix doc for Default configuration

---

docs/user-docs/getting-started/observation.md

closes #1163
add observable properties docs
#1163

chore(docs): add observable properties docs

---

packages/__tests__/3-runtime-html/interpolation.spec.ts
packages/runtime-html/src/binding/interpolation-binding.ts

In an earlier PR, the array observation & update wasn't done correctly and there wasn't dedicated test for this. Fix both.

fix(content): fix content array auto observation

---

docs/user-docs/getting-started/conditional-rendering.md

docs(promise): tabs syntax correction

---

test/benchmarking-apps/runner/src/bench.spec.ts

Remove excessive amount of logs in bench marking app.

feat(build): try aggregate logs

---

packages/__tests__/3-runtime-html/children-observer.spec.ts
packages/runtime-html/src/templating/children.ts
packages/runtime-html/src/templating/controller.ts

At the moment, children observation does not stop. Also, it's working using similar mechanic as other observers: start observing when there's a subscriber. This is bad related timing wise, since a subscriber can be added at any time.
Change the timing to: start observing the child list after binding, and before bound, (~$bind phase of bindings), so that changes can be accurately observed, and the owning controller will be in charge of starting/stopping the observers.

refactor(children): make children observer a controlled observer

---

packages/__tests__/router/external.spec.ts
packages/router/src/resources/href.ts

fix(router): ensure href recognize external

---

docs/user-docs/developer-guides/the-template-compiler.md

Fix a doc issue that makes it not rendered nicely with Gitbook.

chore(doc): fix template compiler doc

---

docs/user-docs/tutorials/create-a-dashboard-using-dynamic-composition.md

Fixed some typos and link pointing to `promise.bind`
No issues were listed for this, just came across these while reading the tutorial.

FIxed some typos

---

docs/user-docs/tutorials/building-a-realtime-cryptocurrency-price-tracker.md

the priceUpdate function has is not automatically called, so just added it to binding function and the currency value converter file create description
No issues, just added some details, on which I got stuck for a while. Thank you.

call priceUpdate and create file for value converter

---

docs/user-docs/resources/migrating-to-aurelia-2.md
packages/__tests__/3-runtime-html/binding-command.call.spec.ts
packages/__tests__/karma.conf.cjs
packages/aurelia/package.json
packages/fetch-client/package.json
packages/i18n/package.json
packages/kernel/package.json
packages/metadata/package.json
packages/platform-browser/package.json
packages/platform/package.json
packages/route-recognizer/package.json
packages/router/package.json
packages/runtime-html/package.json
packages/runtime-html/src/binding/call-binding.ts
packages/runtime/package.json
packages/store-v1/package.json
packages/testing/package.json
packages/validation-html/package.json
packages/validation-i18n/package.json
packages/validation/package.json

closes #1231 thanks @rzasinets
Also remove the magical property in `.call` binding, and start populating breaking change doc.

fix(call-binding): assign args to $event property

---

README.md

The Visual Studio Code batch appended in https://github.com/aurelia/aurelia/pull/1240 has the wrong url. Fix that
Visual Studio Code not openable from Visual Studio Code batch

Visual Studio Code batch update

---

docs/user-docs/resources/migrating-to-aurelia-2.md
packages/__tests__/2-runtime/ast.spec.ts
packages/__tests__/2-runtime/binding.spec.ts
packages/__tests__/2-runtime/connectable-switcher.spec.ts
packages/__tests__/2-runtime/subscriber-collection.spec.ts
packages/__tests__/3-runtime-html/decorator-watch.unit.spec.ts
packages/runtime-html/src/binding/call-binding.ts
packages/runtime-html/src/binding/listener.ts
packages/runtime-html/src/binding/ref-binding.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-attribute.ts
packages/runtime-html/src/resources/custom-element.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime/src/binding-behavior.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/connectable.ts
packages/runtime/src/observation.ts
packages/runtime/src/observation/proxy-observation.ts
packages/runtime/src/observation/subscriber-collection.ts
packages/testing/src/mocks.ts

Shorter prop names & avoid block creation.

refactor: multiple small cleanups

---

packages/__tests__/1-kernel/di.get.spec.ts
packages/kernel/src/functions.ts
packages/runtime-html/src/create-element.ts
packages/runtime-html/src/dom.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/template-element-factory.ts

More small cleanups & test enhancements before refactoring & new features

chore: cleanup & more test enhancements

---

docs/user-docs/getting-to-know-aurelia/introduction/value-converters.md

I have added import tag to import data value converter and changed the file name to date-value-converter.ts
I think import tag belongs to this part of the docs

import value converter info missing

---

docs/user-docs/reference/error-messages.md
packages/__tests__/2-runtime/ast.spec.ts
packages/__tests__/2-runtime/binding.spec.ts
packages/__tests__/3-runtime-html/decorator-watch.computed.spec.ts
packages/__tests__/3-runtime-html/dialog/dialog-service.spec.ts
packages/__tests__/3-runtime-html/select-value-observer.spec.ts
packages/runtime-html/src/aurelia.ts
packages/runtime-html/src/binding-behaviors/signals.ts
packages/runtime-html/src/binding/attribute.ts
packages/runtime-html/src/observation/attribute-ns-accessor.ts
packages/runtime-html/src/observation/bindable-observer.ts
packages/runtime-html/src/observation/checked-observer.ts
packages/runtime-html/src/observation/class-attribute-accessor.ts
packages/runtime-html/src/observation/data-attribute-accessor.ts
packages/runtime-html/src/observation/element-attribute-observer.ts
packages/runtime-html/src/observation/observer-locator.ts
packages/runtime-html/src/observation/select-value-observer.ts
packages/runtime-html/src/observation/style-attribute-accessor.ts
packages/runtime-html/src/observation/value-attribute-observer.ts
packages/runtime-html/src/resources/custom-element.ts
packages/runtime-html/src/templating/children.ts
packages/runtime-html/src/templating/dialog/dialog-configuration.ts
packages/runtime-html/src/templating/dialog/dialog-default-impl.ts
packages/runtime-html/src/templating/dialog/dialog-service.ts
packages/runtime-html/src/templating/rendering.ts
packages/runtime-html/src/watch.ts
packages/runtime/src/binding/ast.ts

Continue the work on getting error coded.

refactor(runtime): more error coded

---

packages-cjs/__tests__/plugin-conventions/preprocess-html-template.spec.ts
packages-cjs/__tests__/plugin-conventions/preprocess.spec.ts
packages-cjs/plugin-conventions/src/preprocess-html-template.ts

fix(plugin-conventions): fix compatibility with webpack css extraction

---

docs/user-docs/reference/error-messages.md
packages/__tests__/3-runtime-html/decorator-watch.computed.spec.ts
packages/aurelia/rollup.config.js
packages/fetch-client/rollup.config.js
packages/i18n/rollup.config.js
packages/kernel/rollup.config.js
packages/metadata/rollup.config.js
packages/platform-browser/rollup.config.js
packages/platform/rollup.config.js
packages/platform/src/index.ts
packages/route-recognizer/rollup.config.js
packages/router/rollup.config.js
packages/runtime-html/rollup.config.js
packages/runtime-html/src/aurelia.ts
packages/runtime-html/src/resources/binding-command.ts
packages/runtime-html/src/resources/custom-attribute.ts
packages/runtime-html/src/resources/custom-element.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/watch.ts
packages/runtime/rollup.config.js
packages/store-v1/rollup.config.js
packages/testing/rollup.config.js
packages/testing/src/assert.ts
packages/validation-html/rollup.config.js
packages/validation-i18n/rollup.config.js
packages/validation/rollup.config.js

- Fix CJS build minification so that it doesn't minify __esModule Closes #1267 
- Removing debugging code out of controller in non-dev build

chore: fix error code overlapping, fix build

---

packages/__tests__/3-runtime-html/if.integration.spec.ts
packages/__tests__/i18n/t/translation-parameters-renderer.spec.ts
packages/__tests__/i18n/t/translation-renderer.spec.ts
packages/i18n/src/t/translation-parameters-renderer.ts
packages/i18n/src/t/translation-renderer.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/aurelia.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/runtime-html/src/resources/custom-elements/au-render.ts
packages/runtime-html/src/resources/template-controllers/if.ts
packages/runtime-html/src/resources/template-controllers/promise.ts
packages/runtime-html/src/resources/template-controllers/repeat.ts
packages/runtime-html/src/resources/template-controllers/switch.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/templating/dialog/dialog-controller.ts
packages/runtime-html/src/templating/rendering.ts
packages/runtime-html/src/templating/view.ts

Ongoing work related to API cleanup.

refactor(all): remove lifecycle flags from various APIs

---

docs/user-docs/developer-guides/web-components.md
docs/user-docs/resources/migrating-to-aurelia-2.md
packages/__tests__/3-runtime-html/web-components.spec.ts
packages/aurelia/src/index.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/plugins/web-components.ts

Port https://github.com/aurelia/web-components to v2
* Remove automatic `au-` prefix
* Remove auto-conversion of Aurelia element -> WC element. Applications need to explicitly define this. This should make mix-matching & controlling things easier.

feat(wc): add web-component plugin

---

docs/user-docs/TOC.md
packages/testing/src/util.ts

chore(doc): add WC doc to TOC

---

README.md

"pre-alpha" is not longer correct in my opinion.

change pre-alpha to alpha

---

packages/__tests__/3-runtime-html/repeat.vc.bb.spec.ts
packages/__tests__/3-runtime-html/repeater-custom-element.spec.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/template-controllers/promise.ts
packages/runtime-html/src/resources/template-controllers/repeat.ts
packages/runtime-html/src/resources/template-controllers/switch.ts

The Iterator AST isn't handled correctly in the renderer. This PR fixes this.

fix(repeat): ensure binding behavior works with .for binding

---

docs/user-docs/getting-to-know-aurelia/introduction/attributes-transferring.md

docs(attr): add note about spread vs explicit order

---

examples/realworld-advanced/package.json
examples/realworld/package.json
package-lock.json
packages/__tests__/3-runtime-html/template-compiler.spec.ts
packages/aurelia/src/index.ts
packages/runtime-html/src/resources/attribute-pattern.ts
packages/runtime-html/src/template-compiler.ts

- upgrade `marked` dependency
- re-export `ITemplateCompiler` in `aurelia` package
- fix an issue where an event command on a bindable prop won't be captured
- add more lower level tests for capturing compilation

chore: minor fixes

---

packages/__tests__/router/smoke-tests.spec.ts
packages/router/src/instructions.ts
packages/router/src/route-expression.ts
packages/router/src/route-tree.ts
packages/router/src/router.ts
packages/router/tsconfig.build.json
packages/router/tsconfig.json

fix(router): router query string issue #1284

---

docs/user-docs/developer-guides/store/configuration-and-setup.md

Fix spelling of initialstate.ts filename in docs

Fix name of initialstate.ts file

---

docs/user-docs/getting-to-know-aurelia/components/bindable-properties/the-basics.md

docs(bindable): minor changes

---

docs/user-docs/getting-to-know-aurelia/components/creating-components/README.md
docs/user-docs/getting-to-know-aurelia/components/creating-components/consuming-a-custom-element.md

In order to reduce the amount of confusion around create a new custom element and having it be consumable I believe a dedicated page around registering the component would be useful.
N/A

chore(docs): add registering a custom element documentation

---

packages/aurelia/src/index.ts

@bigopon This PR necessitated from this discourse post: https://discourse.aurelia.io/t/resolved-v2-no-exported-member-observable/4655?u=sayan751. I think it is better when it is re-exported from the `aurelia` package as well.

chore: re-exported observable from aurelia package

---

.github/workflows/main.yml

Tweak GH action workflow to let it run more extensively to prepare the migration from circleci to gh.

chore: prepare gh action migration

---

packages-cjs/parcel-transformer/src/index.ts

I only tested ts project locally, missed this issue on js project.

fix(parcel-transformer): fix html->js transformer path

---

.circleci/config.yml
.github/workflows/main.yml
packages/__tests__/3-runtime-html/styles.integration.spec.ts
packages/__tests__/karma.conf.cjs
packages/runtime-html/src/templating/styles.ts

fix(css-module): colon in class names'

---

packages/runtime-html/src/resources/attribute-pattern.ts
packages/runtime-html/src/templating/watchers.ts

chore(types): remove internals so exported definitions are correct

---

packages-cjs/plugin-conventions/.eslintrc.cjs
packages-cjs/plugin-conventions/src/hmr.ts
packages-cjs/plugin-conventions/src/preprocess-html-template.ts
packages-cjs/plugin-conventions/src/preprocess-resource.ts

fix(hmr): fix a couple of issues related to HMR

---

.circleci/config.yml
package-lock.json
package.json
packages/__tests__/importmap.js
packages/__tests__/karma.conf.cjs
packages/addons/.eslintignore
packages/addons/.eslintrc.cjs
packages/addons/CHANGELOG.md
packages/addons/LICENSE
packages/addons/README.md
packages/addons/package.json
packages/addons/rollup.config.js
packages/addons/src/index.ts
packages/addons/tsconfig.build.json
packages/addons/tsconfig.json
packages/tsconfig.json

Prepare an addons package to host all the extra goodies.

feat: add an addons package

---

packages/__tests__/integration/app/startup.ts
packages/aurelia/src/index.ts
packages/kernel/src/di.ts
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/template-controllers/flags.ts
packages/runtime/src/observation.ts
packages/runtime/src/observation/binding-context.ts
packages/testing/src/startup.ts
scripts/project.ts

- refactor: cleanup unused flags
https://discord.com/channels/448698263508615178/605163904544538674/974403173932482590

build: work around parcel minification issue

---

packages/kernel/src/functions.ts

fix(kernel) alter copypasted comments

---

examples/lazy-loading-config/package.json
packages/__tests__/3-runtime-html/lifecycle-hooks.created.spec.ts
packages/__tests__/3-runtime-html/lifecycle-hooks.resolve.spec.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/templating/lifecycle-hooks.ts
packages/testing/src/startup.ts
packages/testing/src/test-context.ts

Add support for `created` lifecycle in `@lifecyclehooks`, part of #1044

feat: lifecyclehooks created

---

packages/__tests__/2-runtime/array-observer.spec.ts
packages/__tests__/3-runtime-html/repeater.multi-list-single-array.spec.ts
packages/runtime-html/src/resources/template-controllers/repeat.ts
packages/runtime-html/src/utilities.ts
packages/runtime/src/observation/array-observer.ts
packages/testing/src/startup.ts

fix(array-observer): don't mutate incoming indexmap

---

packages/state/package.json
packages/testing/src/startup.ts

Start releasing state plugin into dev version.

chore(plugin): make state plugin public

---

packages/__tests__/state/state.spec.ts
packages/runtime/src/binding-behavior.ts
packages/state/src/state-binding-behavior.ts

`& state` binding behavior should also update the binding on state change.

fix(state): binding behavior observe

---

packages/router/src/endpoints/viewport.ts
packages/router/src/instructions/routing-instruction.ts
packages/router/src/router-options.ts
packages/router/src/router.ts
packages/router/src/routing-scope.ts

feat(router): add default route to child viewports

---

tsconfig.json

build(dist): change dist target to 2020

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/router.ts

refactor(router-lite): isNavigating flag

---

packages-tooling/__tests__/plugin-conventions/preprocess-html-template.spec.ts
packages-tooling/plugin-conventions/src/preprocess-html-template.ts

fix(plugin-conventions): skip ShadowDOM tag name check, leave it to runtime

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/configuration.ts
packages/router-lite/src/index.ts
packages/router-lite/src/location-manager.ts
packages/router-lite/src/router.ts

This is a parallel to the v1's router's `options.root`. This PR makes it possible to set a custom routing root. By default, the routing root is derived from the `<base>` element's `href`. Although the default should work for most of the case, for some cases, it might not. 
For example, in an app `foo-bar` you may have the following `<base>` element.
```html
<base href="/foo-bar/"></base>
```
If your hosting service is also serving the static files (images, JS files etc.) from under the `foo-bar` directory (naive assumption here is that the `base#href` maps to a physical directory), then it works fine.
However, there are cases, where you want to change the location URL in such a  way that it changes the routing root. A typical example is to add tenant/customer name to the location URL; …

feat(router-lite): custom root provider

---

packages/__tests__/validation-html/validate-binding-behavior.spec.ts
packages/validation-html/src/validate-binding-behavior.ts

fix(validation-html): validate BB trigger

---

packages/__tests__/3-runtime-html/containerless.spec.ts
packages/runtime-html/src/resources/custom-element.ts

fix(runtime-html): containerless #1474

---

packages-tooling/plugin-conventions/src/hmr.ts

fix(hmr): add some more ignores for strict mode TS

---

docs/user-docs/TOC.md
docs/user-docs/getting-to-know-aurelia/templates/built-in-template-features.md
docs/user-docs/getting-to-know-aurelia/templates/repeats-and-list-rendering.md

adds repeator `repeat.for` documentation that I have copied and updated from the previous documentation site.

docs(repeat): adds repeator documentation

---

docs/user-docs/getting-to-know-aurelia/templates/attribute-and-property-bindings.md

added documentation for binding examples
The previous docs had a place to find this documentation but it was always a little tricky to find. I thought having the binding keywords specified more immediately would be better for a quick reference.

docs(binding): adds binding syntax help to attribute bindings page

---

.circleci/config.yml
examples/hmr-webpack-e2e/.gitignore
examples/hmr-webpack-e2e/README.md
examples/hmr-webpack-e2e/au.conf.js
examples/hmr-webpack-e2e/index.ejs
examples/hmr-webpack-e2e/package.json
examples/hmr-webpack-e2e/playwright/app.spec.ts
examples/hmr-webpack-e2e/src/app.html
examples/hmr-webpack-e2e/src/app.ts
examples/hmr-webpack-e2e/src/identity.ts
examples/hmr-webpack-e2e/src/resource.d.ts
examples/hmr-webpack-e2e/src/startup.ts
examples/hmr-webpack-e2e/tsconfig.json
examples/hmr-webpack-e2e/webpack.config.js
package-lock.json
package.json
packages/__e2e__/router-configured-basic/package.json
packages/__e2e__/router-direct-routing-basic/package.json

Add tests for hmr so it'll be easier to develop & verify.

build(tests): add e2e test for hmr

---

packages/__tests__/3-runtime-html/spread.spec.ts
packages/runtime-html/src/resources/custom-element.ts
packages/runtime-html/src/template-compiler.ts

At the moment, attribute capturing is all or nothing. Add the ability for `capture` to accept a function to filter what attribute to accept.
closes #1471

feat(capture): attr filtering

---

packages/__tests__/router/viewport-content.spec.ts
packages/__tests__/router/viewport.spec.ts
packages/router/src/endpoints/viewport-content.ts
packages/router/src/instructions/instruction-component.ts

This PR contains an update of the router's custom element creation since changes in the core made the old one not create the custom element's container properly.
Related to https://github.com/aurelia/aurelia/issues/307, https://github.com/aurelia/aurelia/issues/369, https://github.com/aurelia/aurelia/issues/367 and https://github.com/jwx/aurelia-direct-router/issues/35. 
- Create passing test for the issue
- Resolve remaining issues/requests from Aurelia Direct Router
- Ensure v1 feature parity
- Continue with comments
- Add tests covering …

fix(router): update component creation

---

packages/__e2e__/router-direct-routing-basic/.eslintrc.cjs
packages/__e2e__/router-direct-routing-basic/src/router-configured.spec.ts
packages/__e2e__/router-direct-routing-basic/tsconfig.json
packages/i18n/.eslintrc.cjs
packages/i18n/src/i18n.ts
packages/i18n/src/t/translation-binding.ts

The parameter binding is calling handle change during its unbinding phase, even after its been unbound.

fix: param binding

---

examples/router-animation/src/my-app.ts
packages/router/src/instructions/instruction-component.ts
packages/router/src/navigation-coordinator.ts
packages/router/src/navigator.ts
packages/router/src/router.ts
packages/router/src/routing-scope.ts

This PR contains a fix for the issue with refresh with a default route (https://github.com/aurelia/aurelia/issues/1491) and a fix for a possible race condition bug when using multiple level deep links.
Related to https://github.com/aurelia/aurelia/issues/307, https://github.com/aurelia/aurelia/issues/369, https://github.com/aurelia/aurelia/issues/367 and https://github.com/jwx/aurelia-direct-router/issues/35. 
- Resolve remaining issues/requests from Aurelia Direct Router
- Ensure v1 feature parity
- Continue with comments
- Add tests covering …

fix(router): fix default on refresh issue

---

packages/router-lite/src/instructions.ts
packages/router-lite/src/route-context.ts

Resolve #1508 thanks @3cp 
cc @Sayan751

fix(router-lite): temporarily expose internal typings

---

packages/__tests__/2-runtime/expression-parser.spec.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/expression-parser.ts
packages/runtime/src/index.ts

optional chaining & nullish coalescing

---

packages/__e2e__/router/src/app.html
packages/__e2e__/router/src/app.ts
packages/__e2e__/router/src/pages/one.ts
packages/__e2e__/router/src/pages/two.ts
packages/__e2e__/router/src/router-configured.spec.ts
packages/router/src/instructions/routing-instruction.ts

This PR fixes an issue with `import`ed components in configured routes in release alpha.39.
Resolves https://github.com/aurelia/aurelia/issues/1532.
- Make new e2e tests for `import`ed components

fix(router): fix route import component issue

---

packages/router-lite/src/route-context.ts

fix(router-lite): nav-model promise handling

---

packages/__e2e__/router-lite/src/app.ts
packages/__e2e__/router-lite/src/pages/auth.ts
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/route-context.ts

fix(router-lite): specific module import

---

packages/__e2e__/router/src/app.html
packages/__e2e__/router/src/app.ts
packages/__e2e__/router/src/router-configured.spec.ts
packages/router/src/endpoints/viewport.ts
packages/router/src/routing-scope.ts

This PR contains a fix for the previously missing use case for the issue with refresh with a default route.
Resolves https://github.com/aurelia/aurelia/issues/1491.
- Add an e2e test for the missing use case

fix(router): fix default refresh issue

---

examples/validation-with-router/src/login/index.ts
packages/__tests__/router-lite/_shared/hook-invocation-tracker.ts
packages/__tests__/router-lite/_shared/hook-spec.ts
packages/__tests__/router-lite/_shared/view-models.ts
packages/__tests__/router-lite/config-tests.spec.ts
packages/__tests__/router-lite/hook-tests.spec.ts
packages/__tests__/router-lite/lifecycle-hooks.spec.ts
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/component-agent.ts
packages/router-lite/src/route.ts
packages/router-lite/src/router.ts
packages/router-lite/src/viewport-agent.ts

BREAKING CHANGE chore(router-lite): rename to loading & unloading

---

packages/__tests__/2-runtime/expression-parser.spec.ts
packages/runtime/src/binding/expression-parser.ts

Seems that https://github.com/aurelia/aurelia/issues/808 was already fixed at some point @bigopon

Add regression test for #808

---

.circleci/config.yml
packages/__tests__/2-runtime/ast.spec.ts
packages/__tests__/3-runtime-html/signaler.integration.spec.ts
packages/__tests__/karma.conf.cjs
packages/runtime/src/binding/ast.ts

More cleanup for the ASTs:
- moving the signals evaluation of value converter to `bind`
- prevent image loading error when running tests with karma
- add some tests for multiple vc with signals chaining

refactor: ast 

---

packages/__tests__/router/router.spec.ts
packages/router/src/routing-scope.ts

This PR fixes an occasional issue with location path not being updated when redirecting.
- Make tests for location path check

fix(router): fix path issue when redirecting

---

.circleci/config.yml
benchmarks/latest/package.json
benchmarks/latest/rollup.config.js
benchmarks/latest/webpack.config.js
benchmarks/local/package.json
benchmarks/local/rollup.config.js
benchmarks/rerender-1k.json
benchmarks/startup-1k.json
benchmarks/update-1k.json
examples/rainbow-spiral/app.js
package-lock.json
package.json
packages/__tests__/2-runtime/expression-parser.spec.ts
packages/__tests__/3-runtime-html/repeat.keyed.array.spec.ts
packages/__tests__/3-runtime-html/repeat.keyed.map.spec.ts
packages/__tests__/3-runtime-html/repeat.keyed.set.spec.ts
packages/__tests__/3-runtime-html/repeater-custom-element.spec.ts
packages/__tests__/3-runtime-html/repeater.unit.spec.ts
packages/__tests__/3-runtime-html/template-compiler.spec.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/binding-command.ts
packages/runtime-html/src/resources/template-controllers/repeat.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime/src/binding/ast.eval.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/expression-parser.ts
packages/ui-virtualization/src/virtual-repeat.ts
packages/validation/src/ast-serialization.ts

feat(repeat): add keyed mode (#1583)

---

packages/__tests__/2-runtime/ast.integration.spec.ts
packages/__tests__/2-runtime/ast.spec.ts
packages/__tests__/3-runtime-html/array-index-observer.spec.ts
packages/__tests__/3-runtime-html/array-length-observer.spec.ts
packages/runtime-html/src/app-task.ts
packages/runtime-html/src/bindable.ts
packages/runtime-html/src/observation/observer-locator.ts
packages/runtime-html/src/observation/svg-analyzer.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/attribute-pattern.ts
packages/runtime-html/src/resources/binding-behavior.ts
packages/runtime-html/src/resources/binding-command.ts
packages/runtime-html/src/resources/custom-attribute.ts
packages/runtime-html/src/resources/custom-element.ts
packages/runtime-html/src/resources/template-controllers/repeat.ts
packages/runtime-html/src/resources/value-converter.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/templating/children.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/templating/lifecycle-hooks.ts
packages/runtime-html/src/templating/styles.ts
packages/runtime-html/src/utilities.ts
packages/runtime-html/src/watch.ts
packages/runtime/src/binding/ast.eval.ts
packages/runtime/src/observation/observer-locator.ts
packages/runtime/src/observation/proxy-observation.ts
packages/runtime/src/utilities-objects.ts
packages/testing/src/startup.ts

- implement notify changes on assignment in `AccessKey` / `AccessMember` Closes #1262 
- cleanup/optimize for bundle size

feat: key assignment notify changes

---

examples/router-animation/src/one.html
packages/__e2e__/router/src/app.html
packages/__e2e__/router/src/pages/child.html
packages/__e2e__/router/src/router-configured.spec.ts
packages/router/src/endpoints/viewport-content.ts
packages/router/src/instructions/routing-instruction.ts
packages/router/src/resources/load.ts
packages/router/src/router.ts
packages/router/src/routing-scope.ts

This PR improves the creation of the `href` attribute by the `load` attribute by adding scope path. It also lets the router avoid to catch the wrong errors when a component can't be created.
- Add an e2e test with several `href` checks

feat(router): improve href creation

---

packages/router-lite/src/resources/viewport.ts
packages/router-lite/src/viewport-agent.ts

The stateful feature was not fully implemented for viewport. Therefore, the code is cleaned up, and the stateful feature is removed in favour of actual state handling solutions like `@aurelia/state`.

chore(router-lite): removed stateful from viewport

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/resources/href.ts
packages/router-lite/src/router.ts

fix(router-lite): support ../ prefix for load CA

---

packages/__e2e__/router-lite/src/app.ts
packages/aurelia/package.json
packages/aurelia/src/index.ts

The `router` and `router-lite` packages are dropped from the (umbrella) `aurelia` package to avoid confusion among devs. This reduces confusion as the choice of router needs to be made explicitly.

chore: dropped routers as deps from aurelia

---

docs/user-docs/TOC.md
docs/user-docs/templates/advanced-attribute-binding.md

Added docs to explain how attribute binding works and advanced attribute binding cases. 
https://github.com/aurelia/aurelia/issues/1297
I'm not sure how to document implementing an extended attribute mapper. Could someone provide a quick example of how this would work so I can test it out?

docs: added attribute binding docs

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/instructions.ts

fix(router-lite): fragment to URL

---

packages-tooling/plugin-conventions/src/hmr.ts

fix(hmr): no invalidate on parcel

---

packages/__tests__/router-lite/lifecycle-hooks.spec.ts
packages/router-lite/src/router.ts

This PR fixes an edge case (however, maybe not so edge case).
Previously, it was such that when a `canUnload` returned `false` for an attempt to load `some/path`, another repeat attempt to load the same `some/path` was no-operational. This was due to the fact that even before the `canUnload` is invoked, the route tree was updated. Therefore, on the next attempt, the children node for the current tree and the nodes from the (retry) instruction matched, which instructs the router not to process the instruction.
This commit fixes that by marking unsuccessful unload and thereby enabling processing of the same routing instruction.

fix(router-lite): routeTree adjustment - canUnload

---

packages/__e2e__/router-lite/src/app.html
packages/__e2e__/router-lite/src/app.ts
packages/__e2e__/router-lite/src/index.ts
packages/__e2e__/router-lite/src/router-event-logger-service.ts
packages/__e2e__/router-lite/src/router-lite.spec.ts
packages/__tests__/router-lite/_shared/configuration.ts
packages/__tests__/router-lite/events.spec.ts
packages/kernel/src/di.container.ts
packages/router-lite/src/router.ts
packages/router-lite/src/viewport-agent.ts

This PR primarily adds tests for the router events. It also adds the missing rmit of error event.

test(router-lite): events

---

.husky/commit-msg
.husky/pre-commit
package.json

fix: husky 8 migration

---

docs/user-docs/getting-to-know-aurelia/enhance.md

fix(docs): fix enhance example code

---

packages/__tests__/router-lite/config-tests.spec.ts
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/component-agent.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route-definition.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/router.ts
packages/router-lite/src/viewport-agent.ts

feat(router-lite): async getRouteConfig

---

docs/user-docs/templates/conditional-rendering.md
docs/user-docs/templates/template-syntax.md

Restored the misplaced docs, as necessitated by #1646.
Also refactored an example for the promise.bind. Refer: #1670.

docs: restored the docs for switch

---

docs/user-docs/router-lite/configuring-routes.md

docs(router-lite): async getRouteConfig

---

docs/user-docs/developer-guides/migrating-to-aurelia-2/README.md
packages/__tests__/2-runtime/ast.spec.ts
packages/__tests__/compat-v1/binding-engine.spec.ts
packages/compat-v1/src/compat-binding-engine.ts
packages/compat-v1/src/index.ts
packages/runtime-html/src/compiler/template-compiler.ts
packages/runtime/src/binding/ast.eval.ts

Add the popular utility `BindingEngine` for ease of v1 migration.

feat(compat): add binding engine

---

docs/user-docs/router-lite/navigation-model.md
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/options.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/router.ts

This primarily fixes the issues as reported by [discourse](https://discourse.aurelia.io/t/redirectto-and-canload-of-lifecyclehooks/5055/6?u=sayan751).
Additionally, it adds a router configuration option to deactivate the navigation model.

refactor(router-lite): navigation model enhancement

---

docs/user-docs/router-lite/navigating.md
docs/user-docs/router-lite/router-configuration.md
packages/__tests__/router-lite/_shared/configuration.ts
packages/__tests__/router-lite/location-manager.spec.ts
packages/__tests__/router-lite/smoke-tests.spec.ts

chore(router-lite): tests and docs for historyStrategy as nav opt

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/index.ts
packages/router-lite/src/resources/viewport.ts
packages/router-lite/src/route-definition.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/route.ts
packages/router-lite/src/validation.ts

This change adds similar capabilities of `mapUnknownRoutes` function in Aurelia1, as reported via [discourse](https://discourse.aurelia.io/t/dynamically-mapunknownroutes-in-router-lite/5101?u=sayan751).

feat(router-lite): function for fallback

---

docs/user-docs/router-lite/configuring-routes.md
docs/user-docs/router-lite/viewports.md

docs(router-lite): fallback function

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/router.ts

The `shouldProcess`-logic caused more problem than solving. Hence, it is removed completely, instead of adding one more condition to the ladder and thereby making it even more flimsy.
Fixes #1701

fix(router-lite): removed pre-mature optimization

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route.ts

chore(router-lite): residual changes from #1714

---

docs/user-docs/router-lite/configuring-routes.md
packages/router-lite/src/route.ts

docs(router-lite): distributed configurations

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/options.ts
packages/router-lite/src/viewport-agent.ts

This is reported here: https://discourse.aurelia.io/t/router-lite-navigate-to-optional-param-within-same-route/5115
cc: @elitastic 
Docs and demo.

feat(router-lite): transitionplan as nav opt

---

docs/user-docs/router-lite/navigating.md

docs(router-lite): transition plan as nav opt

---

packages/__tests__/3-runtime-html/select-value-observer.spec.ts
packages/__tests__/esbuild.dev.cjs
packages/runtime-html/src/compiler/template-compiler.ts
packages/runtime-html/src/observation/select-value-observer.ts

fix(select): insensitive multiple.bind order

---

packages/__tests__/3-runtime-html/repeat.keyed.array.spec.ts
packages/runtime-html/src/resources/template-controllers/repeat.ts

fixes https://github.com/aurelia/aurelia/issues/1720

fix(repeat): fix mismatchedLengthError on assigning an array with duplicate primitive values

---

packages/compat-v1/README.md

The readme text was wrong in compat-v1 package

fix compat package readme (minor)

---

packages/ui-virtualization/README.md

Fix readme (minor)

---

package-lock.json
package.json

chore: deps update

---

packages/router-lite/src/component-agent.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/router.ts

Some of unnecessary object creations are avoided.

refactor(router-lite): optimize object creation

---

.circleci/config.yml
package-lock.json
package.json
packages/__tests__/router-lite/ast.spec.ts
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/route-recognizer/src/index.ts
packages/router-lite/src/index.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route-expression.ts

fix(router-lite): handling slash in parameter value

---

.gitignore
package-lock.json
packages-tooling/__tests__/package.json
packages/__tests__/package.json
packages/__tests__/src/3-runtime-html/dialog/dialog-service.spec.ts
packages/__tests__/src/compat-v1/au-compose.spec.ts
packages/dialog/src/plugins/dialog/dialog-default-impl.ts
packages/testing/package.json
packages/testing/src/startup.ts

This is kinda a bug report and a PR in one...ish
Whilst building app, I've noticed that startingZIndex doesn't appear to be used in the `@aurelia/dialog` package.
I've had a crack at trying to use it, but not entirely sure if I'm holding it correctly.

fix(dialog): use startingZIndex

---

.circleci/config.yml
packages/__tests__/src/router-lite/smoke-tests.spec.ts
packages/router-lite/src/viewport-agent.ts

fix(router-lite): invoke-lifecycles transition plan

---

docs/user-docs/router-lite/transition-plans.md

docs(router-lite): updated transitionPlan examples

---

packages/kernel/src/di.container.ts
packages/kernel/src/di.ts

chore(kernel): exposed parent container

---

.circleci/config.yml
package-lock.json
package.json
packages/__tests__/src/3-runtime-html/if.integration.spec.ts
packages/runtime-html/src/resources/template-controllers/if.ts

refactor(runtime-html): if TC

---

.eslintrc.cjs
packages/__tests__/src/3-runtime-html/au-slot.slotted.spec.ts
packages/runtime-html/src/compiler/template-compiler.ts
packages/runtime-html/src/templating/children.ts
packages/runtime-html/src/templating/controller.projection.ts
packages/runtime-html/src/utilities-dom.ts
packages/testing/src/startup.ts

Fix an issue where both shadow dom and au-slot are used together. Currently shadow dom is suppressing some au-slot detection.
closes #1825 
Add a few more tests for shadow + au-slot

fix(au-slot): ensure work with shadow dom

---

docs/user-docs/getting-to-know-aurelia/enhance.md

Working on improving the enhance docs.

feat(docs): updating enhance docs

---

docs/user-docs/templates/template-syntax.md

This improves the grammar and layout of template syntax docs.

feat(docs): update template syntax

---

docs/user-docs/templates/value-converters.md

Adds in some fun examples, fixes up grammar and other parts of the value converters docs.

feat(docs): expanding value converters docs

---

docs/user-docs/templates/globals.md

The global docs were lacking examples and text.

feat(docs): expand globals docs

---

docs/user-docs/templates/lambda-expressions.md

Adds many examples and some improvements to the lambda expressions docs.

feat(docs): improvements to lambda expressions and examples

---

docs/user-docs/tutorials/synthetic-view.md

Synthetic views docs were missing an introduction and expanding upon concepts.

feat(docs): expand and improve synthetic views docs

---

docs/user-docs/aurelia-packages/fetch-client.md

This greatly expands the fetch client docs, adds more examples on common tasks and uses.

feat(docs): expand and improve fetch docs

---

docs/user-docs/README.md

The introduction didn't espouse some of the benefits of Aurelia properly, it also didn't address community size or lack of virtual DOM.

feat(docs): expand and improve introduction

---

.circleci/config.yml
examples/realworld-vanilla/index.html

Fix generative module step, tweak the corresponding example.

fix(build): fix generative native modules, examples

---

docs/user-docs/developer-guides/scenarios/attributemapper.md

Corrected a residual change from https://github.com/aurelia/aurelia/pull/1864.

docs(attr-mapping): corrected typo

---

docs/user-docs/TOC.md
docs/user-docs/developer-guides/scenarios/process-content.md

Additionally, grouped template compilation docs in TOC.

docs: added back the misplaced processContent docs

---

packages/__tests__/src/i18n/t/translation-integration.spec.ts
packages/i18n/src/t/translation-binding.ts

fix(i18n): handle change of key in t.bind

---

packages/__tests__/src/validation/rule-provider.spec.ts
packages/validation/src/rule-provider.ts

fix(validation): property parsing with lambda and istanbul

---

packages/__tests__/src/compat-v1/delegate.spec.ts
packages/compat-v1/src/compat-ast.ts
packages/compat-v1/src/compat-delegate.ts
packages/i18n/src/t/translation-binding.ts
packages/kernel/src/di.container.ts
packages/kernel/src/di.ts
packages/kernel/src/index.ts
packages/platform/src/index.ts
packages/runtime-html/src/resources/custom-elements/au-slot.ts
packages/runtime-html/src/utilities-di.ts

refactor: some small cleanup

---

packages/__tests__/src/2-runtime/ast.spec.ts
packages/__tests__/src/2-runtime/expression-parser.spec.ts
packages/__tests__/src/3-runtime-html/access-boundary.spec.ts
packages/__tests__/src/state/state.spec.ts
packages/__tests__/src/validation/expression-serialization.spec.ts
packages/runtime/src/binding/ast.eval.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/ast.visitor.ts
packages/runtime/src/binding/expression-parser.ts
packages/runtime/src/index.ts
packages/validation/src/ast-serialization.ts

Implements `this` to access the boundary scope.

feat(runtime): impl 'this' / AccessBoundary

---

packages/__tests__/src/3-runtime-html/dialog/dialog-service.spec.ts
packages/__tests__/src/3-runtime-html/enhance.spec.ts
packages/__tests__/src/integration/app/molecules/random-generator/random-generator.ts
packages/i18n/src/i18n.ts
packages/i18n/src/t/translation-binding.ts
packages/runtime-html/src/templating/controller.ts

The define lifecycle hook is unnecessary and may come with potential issue, this PR removes it
resolve #1898 
- Fix an issue where i18n bindings do unsubscribe from locale change.

refactor(controller): remove define lifecycle hook

---

packages/__tests__/src/3-runtime-html/di-resolutions.spec.ts
packages/kernel/src/di.container.ts
packages/router/src/endpoints/viewport-content.ts
packages/router/src/errors.ts
packages/router/src/instructions/routing-instruction.ts
packages/router/src/resources/href.ts
packages/router/src/resources/link-handler.ts
packages/router/src/resources/load.ts
packages/router/src/resources/viewport-scope.ts
packages/router/src/resources/viewport.ts
packages/router/src/route.ts
packages/router/src/router.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/resources/custom-element.ts

Some routine cleanup between features/fixes

refactor: cleanup

---

packages/runtime/src/observation/array-observer.ts

Hyra iQ / ProcurePro is using a unique configuration of Aurelia in that we have a large codebase in Aurelia 1 that we are in the process of migration to Aurelia 2. Part of our strategy to migrate, is that we can have Aurelia 1 boot Aurelia 2 and use .enhance to bring new functionality built in Aurelia 2 within our Aurelia application.
An example is we have a page built in Aurelia 1, there's a button which opens a drawer/modal which is actually an Aurelia 2 drawer/modal that we have opened using `enhance()`.
The unique issue we ran into, is that Aurelia 2 dependencies were loading first, which invoked `array-observer.ts` to capture the `Array.prototype.push` etc methods at that point in time and store them in a variable. It didn't actually override the Array.prototype methods at that …

feat(runtime): delay overriding array prototypes

---

packages/__tests__/src/3-runtime-html/enhance.spec.ts
packages/runtime-html/src/app-root.ts

It's a surprise when app tasks from the main application start to get called again whenever `.enhance` was called. This PR fixes this.

fix(enhance): dont call app tasks from parent container

---

packages-tooling/ts-jest/src/index.ts

chore: default options for internal ts-jest instance

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

chore: update issue template with repro link

---

packages/__tests__/src/router-lite/lifecycle-hooks.spec.ts
packages/router-lite/src/component-agent.ts
packages/router-lite/src/route-context.ts

chore(router-lite): avoided duplicate CE defn reg to same container

---

.eslintrc.cjs
package-lock.json
packages-tooling/http-server/src/server-options.ts
packages/fetch-client/src/http-client.ts
packages/kernel/package.json
packages/kernel/src/di.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/ast.eval.ts
packages/runtime-html/src/bindable.ts
packages/template-compiler/src/instructions.ts
packages/ui-virtualization/src/utilities-dom.ts
packages/validation/src/serialization.ts
packages/web-components/src/web-components.ts

Earlier because of the metadata override the kernel package was marked as side-effectful but we can have a better way to do it with `@__PURE__` + IIFE. This PRs implements that.

refactor(kernel): mark side effect free

---

packages/__tests__/src/3-runtime-html/spread.spec.ts
packages/runtime-html/src/binding/spread-binding.ts
packages/template-compiler/src/template-compiler.ts

refactor: resolve previous PR comments

---

package-lock.json
package.json
packages/__tests__/src/3-runtime-html/dialog/dialog-service.spec.ts
packages/__tests__/src/fetch-client/fetch-client.spec.ts
packages/dialog/src/dialog-configuration.ts
packages/dialog/src/dialog-controller.ts
packages/dialog/src/dialog-default-impl.ts
packages/dialog/src/dialog-interfaces.ts
packages/dialog/src/dialog-service.ts
packages/dialog/src/errors.ts
packages/dialog/src/index.ts
packages/expression-parser/src/errors.ts
packages/fetch-client/src/errors.ts
packages/fetch-client/src/http-client.ts
packages/fetch-client/src/interceptors/retry-interceptor.ts
packages/i18n/src/errors.ts
packages/kernel/src/errors.ts
packages/kernel/src/functions.ts
packages/validation/src/errors.ts

Few final error related cleanup to prepare for RC.

refactor: extract error codes and cleanup

---

docs/user-docs/router-lite/configuring-routes.md
packages/__tests__/src/router-lite/current-route.spec.ts

Additionally, added a test for current route with optional constrained parameter.

docs: constrained route parameter

---

docs/user-docs/TOC.md
docs/user-docs/getting-to-know-aurelia/synchronous-binding-system.md

Adds in documentation around Aurelia 2's synchronous binding system and describes the state tearing problem and how to work around it using `batch`
https://github.com/aurelia/aurelia/issues/1957

docs(getting-to-know-aurelia): understanding synchronous binding

---

.vscode/launch.json
docs/user-docs/aurelia-packages/validation/defining-rules.md
packages/__tests__/src/validation-i18n/localization.spec.ts
packages/__tests__/src/validation/rule-provider.spec.ts
packages/validation-i18n/src/localization.ts
packages/validation/src/rule-interfaces.ts
packages/validation/src/rule-provider.ts
packages/validation/src/rules.ts

chore(validation): state rule cleanup

---

packages/__tests__/src/router-lite/external.spec.ts
packages/router-lite/src/resources/href.ts

fix(router-lite): external attribute for href

---

package-lock.json
package.json
packages/runtime-html/src/bindable.ts

Closes the issue reported [here](https://discourse.aurelia.io/t/new-release-au-v2-beta-20/5491/4?u=sayan751).

fix: bindable definitions

---

package-lock.json
package.json

fix broken e2e benchmarking tests

fix(chromedriver): upgrade to 126.0.5 from 125

---

docs/user-docs/router-lite/navigation-model.md

Added docs in response to the issue reported here: https://discourse.aurelia.io/t/cannot-resolve-iroutercontext-for-router-lite/5503/2

docs(router-lite): route-context injection in app-root

---

docs/user-docs/router-lite/router-configuration.md

Reported by @ekzobrain in Discord.

docs(router-lite): correction

---

.vscode/launch.json
.vscode/tasks.json
packages/__tests__/src/router-lite/events.spec.ts
packages/__tests__/src/router-lite/smoke-tests.spec.ts
packages/router-lite/src/component-agent.ts
packages/router-lite/src/route-context.ts

This uses the changes from the #2043 to ensure that the injected element in the routed viewmodel is indeed hydrated. 
Fixes #2042.

fix(router-lite): element injection issue

---

examples/router-hooks/src/my-app.ts
examples/router-hooks/src/views/first-section/first-section.html
examples/router-hooks/src/views/first-section/first-section.ts
packages/__e2e__/5-router/src/app.html
packages/__e2e__/5-router/src/app.ts
packages/__e2e__/5-router/src/pages/params.html
packages/__e2e__/5-router/src/pages/params.ts
packages/__e2e__/5-router/src/router-configured.spec.ts
packages/router/src/router.ts

This PR fixes an issue with refreshing the browser with url params and routes.
- Add e2e test that does a refresh

fix(router): fix refresh with url params issue

---

docs/user-docs/aurelia-packages/dialog.md

Add missing DefaultDialogEventManager in code sample when using a customized dialog

Update dialog.md code sample

---

packages/__tests__/src/2-runtime/expression-parser.spec.ts
packages/__tests__/src/2-runtime/new-expression.spec.ts
packages/expression-parser/src/ast.ts
packages/expression-parser/src/expression-parser.ts
packages/expression-parser/src/index.ts
packages/runtime/src/ast.eval.ts

This PR implements the `NewExpression` syntax. This allows you to instantiate global types:
```html
<template>
<input value.bind="email" type="email" placeholder="Enter email">
<p if.bind="new RegExp('^\\S+@\\S+\\.\\S+$').test(email)">Valid Email Address</p>
</template>
```
And types that are defined in-scope
```ts
class Foo {}
export class MyElement {
Foo = Foo;
}
```
```html
<child-element prop.bind="new Foo()"></child-element>
```

feat(expression-parser): NewExpression

---

packages/web-components/README.md

This PR just adds some documentation howto use web components. As it took me some time to investigate current gitbook and source codes. This may be updated using insights from core aurelia developers. However, I've tested the documented configuration on real project.

ADD usage section of web components

---

packages/__tests__/src/2-runtime/ast.spec.ts
packages/__tests__/src/2-runtime/expression-parser.spec.ts
packages/expression-parser/src/ast.ts
packages/expression-parser/src/expression-parser.ts
packages/runtime/src/ast.eval.ts

This PR implements the exponentiation (`**`) operator.

feat(templating): support exponentiation operator

---

docs/user-docs/templates/template-syntax/template-promises.md

Removing a repeated phrase from the docs about the use of `promise.bind` that is right after the other.

docs(template-promises): remove duplicate text

---

.circleci/config.yml
packages/addons/rollup.config.mjs
packages/aurelia/rollup.config.mjs
packages/compat-v1/rollup.config.mjs
packages/dialog/rollup.config.mjs
packages/expression-parser/rollup.config.mjs
packages/fetch-client/rollup.config.mjs
packages/i18n/rollup.config.mjs
packages/kernel/rollup.config.mjs
packages/metadata/rollup.config.mjs
packages/platform-browser/rollup.config.mjs
packages/platform/rollup.config.mjs
packages/route-recognizer/rollup.config.mjs
packages/router-html/rollup.config.mjs
packages/router-lite/rollup.config.mjs
packages/router/rollup.config.mjs
packages/runtime-html/rollup.config.mjs
packages/runtime/rollup.config.mjs
packages/state/rollup.config.mjs
packages/store-v1/rollup.config.mjs
packages/template-compiler/rollup.config.mjs
packages/testing/rollup.config.mjs
packages/ui-virtualization/rollup.config.mjs
packages/validation-html/rollup.config.mjs
packages/validation-i18n/rollup.config.mjs
packages/validation/rollup.config.mjs
packages/web-components/rollup.config.mjs

chore: used LTS node 22 in CI

---

.husky/commit-msg
.husky/pre-commit
packages/__tests__/src/validation-html/validate-binding-behavior.spec.ts
packages/validation-html/src/validate-binding-behavior.ts

fix(validation): removed bindings on unbind

---

.circleci/config.yml
benchmarks/app-repeat-keyed-expr/bench.json
benchmarks/app-repeat-keyed-expr/startup-latest.html
benchmarks/app-repeat-keyed-expr/startup-local.html
benchmarks/app-repeat-keyed-expr/startup.index.js
benchmarks/app-repeat-keyed-string/bench.json
benchmarks/app-repeat-keyed-string/startup-latest.html
benchmarks/app-repeat-keyed-string/startup-local.html
benchmarks/app-repeat-keyed-string/startup.index.js
benchmarks/latest/rollup.config.mjs
benchmarks/local/rollup.config.mjs
benchmarks/package.json
packages/__tests__/src/3-runtime-html/repeat.keyed.array.spec.ts
packages/__tests__/src/3-runtime-html/repeat.keyed.map.spec.ts
packages/runtime-html/src/resources/template-controllers/repeat.ts

The scope caching only relied on item identity. This was an oversight. Now it uses the keys in keyed mode and properly retains the scope / binding context when you re-assign a new array or new items with the same keys.
Fixes https://github.com/aurelia/aurelia/issues/2087
I experimented with a few different methods before settling on full key evaluation. It seems there is no other way to guarantee correct up-to-date keys in all scenarios (including the combination of expression-based keys with destructured locals) other than pre-evaluating them all. This may have performance impact. Therefore it may be a good idea to explicitly point out in the docs that using string-based keys is preferable if possible
I added the test case from https://github.com/aurelia/aurelia/issues/2087 as well as a …

fix(repeat): change to key-based scope caching in keyed mode

---

packages/__tests__/src/i18n/t/translation-integration.spec.ts
packages/i18n/src/t/translation-binding.ts

fix(i18n): reactive translation of conditional projected content

---

docs/user-docs/TOC.md
docs/user-docs/getting-to-know-aurelia/template-controllers.md
docs/user-docs/templates/binding-behaviors.md
docs/user-docs/templates/template-syntax/attribute-binding.md
docs/user-docs/templates/template-syntax/event-binding.md
docs/user-docs/templates/template-syntax/overview.md
docs/user-docs/templates/template-syntax/template-promises.md
docs/user-docs/templates/template-syntax/template-references.md
docs/user-docs/templates/template-syntax/template-variables.md
docs/user-docs/templates/template-syntax/text-interpolation.md

NOT READY FOR MERGE YET
Some of our docs go back years in the early days of Aurelia 2. Now things are getting towards stable release, this overhauls some of the docs to be easier to follow, better formatted and more examples for many crucial aspects of Aurelia 2, with lots more to follow.

WIP: docs(all): updating aurelia 2 docs to be more cohesive and better

---

package-lock.json
package.json
packages/__tests__/src/validation-html/validate-binding-behavior.spec.ts
packages/validation/src/validator.ts

fix(validation): for dynamically accessed fields

---

packages-tooling/__tests__/src/plugin-conventions/preprocess-resource.spec.ts
packages-tooling/__tests__/src/plugin-conventions/type-checking/_shared.ts
packages-tooling/__tests__/src/plugin-conventions/type-checking/without-convention.basic.spec.ts
packages-tooling/plugin-conventions/src/preprocess-resource.ts
packages-tooling/plugin-conventions/src/template-typechecking.ts

In this iteration, the following supports are added to the type-checking:
- Handling TS private properties #2115.
- Handling method calls.
- Added tests for method overloads, and union typed properties and method arguments.

chore(tooling/type-checking): handling TS private members and method calls

---

docs/user-docs/developer-guides/scenarios/multi-root.md

Correction of documentation for multi root scenario as suggested by @Sayan751 on Discourse https://discourse.aurelia.io/t/aurelia2-reload-root-component/6365
The solution that was described didn't actually work.

doc(multi-root): correct multi root scenario doc and link to example

---

docs/user-docs/router-lite/configuring-routes.md
package-lock.json
package.json
packages/__tests__/src/router-lite/navigation-strategy.spec.ts
packages/router-lite/src/events.ts
packages/router-lite/src/index.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/route.ts
packages/router-lite/src/validation.ts

This is a port of navigation strategy of au1 router. An example looks as follows.
```ts
import { customElement } from '@aurelia/runtime-html';
import { route, NavigationStrategy, RecognizedRoute } from '@aurelia/router-lite';
import template from './my-app.html';
import { About } from './about';
import { Home } from './home';
let dataLoaded = false;
@route({
routes: [
{
path: ['', 'home'],
component: Home,
},
{
path: 'about',
component: About,
},
{
path: 'foo',
component: new NavigationStrategy((viewportInstruction: IViewportInstruction, ctx: IRouteContext, node: RouteNode, route: RecognizedRoute<unknown>) => {
if (dataLoaded) return Home;
dataLoaded = true;
return About;
})
}
],
})
export class MyApp {}
```
cc: @simonfox

feat(router-lite): navigation strategy

---

packages/__tests__/src/router-lite/navigation-strategy.spec.ts

#2139
Example test case to address #2139

test(router-lite): navigation strategy

---

packages/__tests__/src/i18n/t/translation-integration.spec.ts
packages/i18n/src/t/translation-binding.ts

This handles the residual fix of reactive translation on change of t-params for a projcted content.
#2150

fix(i18n): reactive translation of conditional projected content - t-params

---

docs/user-docs/developer-guides/error-messages/README.md
docs/user-docs/developer-guides/error-messages/router/README.md
docs/user-docs/developer-guides/error-messages/router/aur2000.md
docs/user-docs/developer-guides/error-messages/router/aur2001.md
docs/user-docs/developer-guides/error-messages/router/aur2002.md
docs/user-docs/developer-guides/error-messages/router/aur2003.md
docs/user-docs/developer-guides/error-messages/router/aur2004.md
docs/user-docs/developer-guides/error-messages/router/aur2005.md
docs/user-docs/developer-guides/error-messages/router/aur2006.md
docs/user-docs/developer-guides/error-messages/router/aur2007.md
docs/user-docs/developer-guides/error-messages/router/aur2008.md
docs/user-docs/developer-guides/error-messages/router/aur2009.md
docs/user-docs/developer-guides/error-messages/router/aur2010.md
docs/user-docs/developer-guides/error-messages/router/aur2011.md
docs/user-docs/developer-guides/error-messages/router/aur2012.md
docs/user-docs/developer-guides/error-messages/router/aur2013.md
docs/user-docs/developer-guides/error-messages/router/aur2014.md
docs/user-docs/developer-guides/error-messages/router/aur2015.md
docs/user-docs/developer-guides/error-messages/router/aur2016.md
docs/user-docs/developer-guides/error-messages/router/aur2017.md
docs/user-docs/developer-guides/error-messages/router/aur2018.md
packages/router/src/errors.ts

Adds documentation for router errors AUR2000 to AUR2018, providing detailed descriptions, causes, and solutions for each error to assist developers in debugging and resolving router-related issues. Also links errors in dev mode.

docs(router): add error message documentation

---

docs/user-docs/components/bindable-properties.md
docs/user-docs/components/class-and-style-binding.md
docs/user-docs/components/component-lifecycles.md
docs/user-docs/components/components.md
docs/user-docs/components/customelement-api.md
docs/user-docs/components/scope-and-binding-context.md
docs/user-docs/developer-guides/animation.md
docs/user-docs/developer-guides/building-plugins.md
docs/user-docs/developer-guides/bundlers/README.md
docs/user-docs/developer-guides/migrating-to-aurelia-2/side-by-side-comparison.md
docs/user-docs/developer-guides/ui-virtualization.md
docs/user-docs/developer-guides/web-components.md
docs/user-docs/templates/conditional-rendering.md
docs/user-docs/templates/custom-attributes.md
docs/user-docs/tutorials/building-a-todo-application.md

Missing APIs, erroneous outdated imports, lack of detail, poor cohesion and other facets of Aurelia 2 docs that needed to be improved.

WIP docs(user-docs): improving and expanding numerous doc sections

---

docs/user-docs/getting-to-know-aurelia/dependency-injection.md

Existing docs blew chunks and now they're better.

docs(di): add missing di methods and revise docs

---

packages/__tests__/src/2-runtime/queue.spec.ts
packages/runtime-html/src/resources/template-controllers/promise.ts
packages/runtime/src/queue.ts

fix(queue): prevent task cancellation from triggering unhandledRejection

---

docs/user-docs/developer-guides/scenarios/tailwindcss-integration.md

This details configuring Aurelia 2 projects with the latest version of Tailwind which changed a lot of things.

docs(tailwind): update tailwind docs

---

.vscode/launch.json
docs/user-docs/router/configuring-routes.md
docs/user-docs/router/navigating.md
docs/user-docs/router/navigation-model.md
docs/user-docs/router/router-configuration.md
docs/user-docs/router/transition-plans.md
docs/user-docs/router/viewports.md
packages/__tests__/src/router/_shared/create-fixture.ts
packages/__tests__/src/router/smoke-tests.spec.ts
packages/router/src/component-agent.ts
packages/router/src/options.ts
packages/router/src/route-tree.ts

The router option is a temporary option to the devs transitioning from router-direct to router.
It is requested here: https://discourse.aurelia.io/t/migrating-from-router-direct-to-router-lite-params-queryparams/6484/2

chore(router): added an option to treat query parameters as path parameters

---

packages/__tests__/src/2-runtime/queue.spec.ts

https://github.com/aurelia/aurelia/commit/35ea8b505454ac3396555725927e7c5c798b6fcd

test: greaterThanOrEqualTo

---

.circleci/config.yml
package.json

It's a good idea to keep local and CI versions the same to avoid "works locally but not in CI" (or vice versa) situations. This is in preparation for some CI pipeline improvements.
Also start cleaning up the circleci config from stuff we no longer use

pin local node & npm versions to match CI

---

docs/user-docs/tutorials/building-a-todo-application.md

(docs)tutorials/todo: fix typo

---

docs/user-docs/README.md

docs(introduction): fix typo

---

docs/user-docs/router/router-hooks.md
docs/user-docs/router/routing-lifecycle.md
package-lock.json
packages/__e2e__/6-router/index.ejs
packages/__e2e__/6-router/index.html
packages/__e2e__/6-router/package.json
packages/__e2e__/6-router/playwright.config.js
packages/__e2e__/6-router/src/animation-hooks.ts
packages/__e2e__/6-router/src/index.ts
packages/__e2e__/6-router/src/pages/home.ts
packages/__e2e__/6-router/src/pages/one.ts
packages/__e2e__/6-router/src/pages/two.ts
packages/__e2e__/6-router/src/router.animation.spec.ts
packages/__tests__/src/router/_shared/configuration.ts
packages/__tests__/src/router/lifecycle-hooks.spec.ts
packages/__tests__/src/router/location-manager.spec.ts
packages/__tests__/src/router/smoke-tests.spec.ts
packages/router/src/component-agent.ts
packages/router/src/options.ts
packages/router/src/router.ts

This pull request implements a history navigation direction marker for `@urelia/router`.  To detect the direction of navigation, you can use the `isBack` property from the `options: INavigationOptions` parameter in the lifecycle hooks.
The `isBack` property will be `true` if the navigation is a backward navigation (e.g., user clicked the browser's back button) and `false` for forward navigation.
```typescript
import { IRouteViewModel, INavigationOptions, Params, RouteNode } from '@aurelia/router';
import { customElement } from '@aurelia/runtime-html';
@customElement({
name: 'my-component',
template: `<div class="page">My Component Content</div>`,
})
export class MyComponent implements IRouteViewModel {
public loading(
params: Params,
next: RouteNode,
current: RouteNode | null,
options: …
```

feat(router): history navigation direction marker

---

.vscode/launch.json
.vscode/tasks.json
packages/__tests__/src/router/smoke-tests.spec.ts
packages/router/src/route-context.ts

Fixes the issue #2247 
cc: @mahlonsmith

fix(router): exception with `nav: false`

---

docs/user-docs/getting-to-know-aurelia/dependency-injection-di/overview.md

Addresses issue https://github.com/aurelia/aurelia/issues/2221

docs(di): migration for di docs
