src/runtime/binding/binding.ts

Removing this until all the binding logic is working properly and stabilized, to simplify the process. Then we can add it back in in a form that makes sense for the new logic.

refactor(binding): remove connect-queue (temporarily)

---

.circleci/config.yml

Hopefully make it easier to see what goes wrong when it goes wrong

chore(ci): enable npm ci verbose logging

---

src/runtime/dom.ts
src/runtime/templating/rendering-engine.ts
src/runtime/templating/template.ts
src/runtime/templating/view.ts

Also, added some notes on which things are likely to go away with the removal of shadow dom emulation. In the end, I'm hopeful that a good chunk of this will be simplified. However, I think it's likely going to still be very valuable to have core abstractions like ITemplates that create IViews. The simplicity can come from the fact that you will no longer need a RenderSlot to render the IView. You can basically just have an INode (or RenderLocation, which will just be an INode) and simply append the IView at the location.

doc(runtime): clarify the purpose of several core items

---

packages/runtime/src/dom.ts
packages/runtime/src/templating/custom-element.ts
packages/runtime/src/templating/render-context.ts
packages/runtime/src/templating/render-location.ts
packages/runtime/src/templating/render-slot.ts
packages/runtime/src/templating/renderer.ts
packages/runtime/test/unit/dom.spec.ts

This PR adds the minimal infrastructure to provide template controllers with an `IRenderLocation` instance, which is an `INode` representing the location in the DOM where the template controller can add/remove views.
This is a much simpler abstraction than `IRenderSlot`. The `IRenderLocation` gives the lowest-level possible power to a template controller, allowing for re-designed controllers that are more performant and use less memory.
Next steps involve converting a simple template controller over to use the new abstraction, removing its usage of `IRenderSlot`. The first controllers converted will likely be `with` and `replaceable`. Once these are done, we can move on to `if` and/or `repeat`.
After all template controllers are updated to use the new abstraction, we can remove the old …

feat(templating): add the low-level render location abstraction

---

packages/jit/src/templating/binding-command.ts
packages/jit/src/templating/template-compiler.ts
packages/jit/test/unit/templating/template-compiler.spec.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/binding-behavior.ts
packages/runtime/src/binding/value-converter.ts
packages/runtime/src/resource.ts
packages/runtime/src/templating/custom-attribute.ts
packages/runtime/src/templating/custom-element.ts
packages/runtime/src/templating/instructions.ts
packages/runtime/src/templating/renderer.ts
packages/runtime/src/templating/rendering-engine.ts
packages/runtime/test/unit/templating/attribute-assistance.ts

* I renamed the `get` method of `IResourceDescriptions` to `find`. I'm making a conscious movement away from calling things "get" in code as it has very little explanatory power.
* I renamed the `key` method of `IResourceKind` to `keyFrom` to make it clear that the key was being derived from the input. `key` seemed too much like a property name rather than a name for a pure function.
I'd like to change the `IServiceLocator` interface to not use the `get` or `getAll` names but instead use `resolve` and `resolveAll`, or something similar. This would be a breaking change from vCurrent so this might be a case where we want to keep the old methods as an alias. I'm not sure at this time, so I'm delaying this change.

refactor(all): improving a couple of method names related to resources

---

packages/runtime/src/binding/property-observation.ts
packages/runtime/src/templating/custom-attribute.ts
packages/runtime/src/templating/custom-element.ts
packages/runtime/src/templating/resources/with.ts
packages/runtime/src/templating/runtime-behavior.ts
packages/runtime/test/unit/templating/resources/with.spec.ts

This PR attempts to simplify the behavior around bindable callbacks.
In vCurrent, whether or not a bindable self callback is invoked during the binding process depends on whether or not you have a `bind` callback. If you have a `bind` callback, the self callbacks for each property will not be called. However, if you don't have a `bind`, they will be called. If they are called, then they are called one by one, after each property is set, rather than all together after all properties are set.
For vNext I'm proposing that bindable self callbacks never fire during initialization, regardless of whether or not you have a `bound` callback. This makes it very clear how to implement behaviors. If you need to do something upon initialization, you implement `bound`. If you need to react to changes …

fix(runtime): dry up bindable callback behavior

---

packages/runtime/src/binding/event-manager.ts
packages/runtime/src/binding/observer-locator.ts
packages/runtime/src/dom.ts

HTML spec says that `Node.tagName` is always upper case when it is an element type, so we don't really need to normalize it. Slight perf improvement.
Though I'm clueless at the moment why those 4 tests are failing @bigopon you always catch these kinds of things, any idea? :bug:

refactor(dom): use uppercase tag names

---

packages/runtime/src/binding/property-observation.ts
packages/runtime/src/templating/resources/with.ts
packages/runtime/src/templating/runtime-behavior.ts

This PR removes the lazy location of bindable properties based on naming conventions. This change reduces the complexity of the runtime, making component hydration a little leaner. Additionally, this PR encapsulates the way that the Observer handles "self callbacks".
For vNext, I had hoped to make it possible to have completely POJO components, with bindables being automatically inferred based on property/callback naming conventions. So, this was implemented inside of the runtime. However, this approach to solving the problem didn't align with the idea that the runtime should work only off of explicit data and AOT should enable conventions that created that data. It also added needless complexity due to the fact that bindables could come from yet another location, at another time in the …

fix(runtime): remove lazy bindable location and encapsulate observer

---

packages/jit/src/templating/template-compiler.ts
packages/jit/test/unit/templating/template-compiler.spec.ts
packages/runtime/src/binding/call.ts
packages/runtime/src/binding/listener.ts
packages/runtime/src/binding/ref.ts
packages/runtime/src/templating/instructions.ts
packages/runtime/test/unit/templating/renderer.spec.ts

Closes #84 
- Changes `instruction.type` from number to string. Also converts the enum to const enum (preserve const enums is enabled) for better performance by inlining.
- Added some unit tests to the renderer as an initial effort to improve test coverage in that area, and to have some lower level verification that the instructions work
- Made a few binding properties public on the classes themselves. Primarily for unit testing, but I believe it makes sense for them to be exposed (if you go so far as to cast to a concrete binding class, you probably want to access some of its properties too).

refactor(instructions): change number type to string

---

.vscode/settings.json
packages/kernel/src/di.ts

This PR converters the invoker lookup to an array, ordered by dependency count. Previously, it was an object with the dependency count as key and the invoker as value.

fix(di): convert invokers to an array

---

packages/runtime/src/binding/binding-behavior.ts
packages/runtime/src/binding/binding-context.ts
packages/runtime/src/binding/value-converter.ts
packages/runtime/src/templating/custom-attribute.ts
packages/runtime/src/templating/custom-element.ts

This PR refactors the internals of the `define` methods of each of the resources types so that they use shared functions rather than creating new function instances on every method invocation.
While working on the `CustomElementResource` a helper factory method for basic scopes was also factored out and placed on the `BindingContext`.

refactor(runtime): lift resource methods

---

packages/runtime/src/templating/rendering-engine.ts
packages/runtime/src/templating/view.ts

This PR does two things:
1. Moves the View and ViewFactory code into the `view.ts` file with the related interfaces. There was a reason to have it where it was, once upon a time, I think. That reason has gone and it's better to keep things together.
2. Reworks View and ViewFactory so that a custom class doesn't need to be created for every View that a factory creates. This should be much more efficient.
After the refactoring to remove the custom class generation for the primary scenarios, the component view scenario is left in an odd state. I intend to fix this up, but since it's strongly coupled to the `compose` element scenarios, I chose not to do it as part of this PR. I'd like to fix this up at the same time as the `compose` element fixups.

refactor(view): increase cohesion of view code

---

packages/examples/e2e-benchmark/vcurrent/app.ts
packages/examples/e2e-benchmark/vcurrent/index.html
packages/examples/e2e-benchmark/vcurrent/instrumenter.ts
packages/examples/e2e-benchmark/vnext/app.ts
packages/examples/e2e-benchmark/vnext/index.html
packages/examples/e2e-benchmark/vnext/instrumenter.ts
packages/runtime/src/binding/array-observer.ts
packages/runtime/src/binding/collection-observer.ts
packages/runtime/src/binding/computed-observer.ts
packages/runtime/src/binding/dirty-checker.ts
packages/runtime/src/binding/element-observation.ts
packages/runtime/src/binding/map-observer.ts
packages/runtime/src/binding/observation.ts
packages/runtime/src/binding/observer-locator.ts
packages/runtime/src/binding/property-observation.ts
packages/runtime/src/binding/property-observer.ts
packages/runtime/src/binding/resources/update-trigger-binding-behavior.ts
packages/runtime/src/binding/set-observer.ts
packages/runtime/src/binding/subscriber-collection.ts
packages/runtime/src/binding/target-accessors.ts
packages/runtime/src/binding/target-observer.ts
packages/runtime/src/templating/runtime-behavior.ts
packages/runtime/test/unit/binding/array-observer.spec.ts
packages/runtime/test/unit/binding/map-observer.spec.ts
packages/runtime/test/unit/binding/property-observation.spec.ts
packages/runtime/test/unit/binding/set-observer.spec.ts
packages/runtime/test/unit/binding/subscriber-collection.spec.ts

fix(e2e-benchmark): simplify markers and use setTimeout to include render time
perf(binding): remove unnecessary work / cleanup
refactor(binding): convert subscriber-collection to decorator for sync and async
I'm a little hesitant on whether I prefer the approach I took on property observer vs the approach on collection observers.
- On the property observers there is a partial interface implementations with as few properties and methods declared as possible. This gives a much cleaner view of the implementation, but lacks a degree of transparency perhaps. It also means observers need to be cast explicitly.
- On the collection observers the full interfaces are implemented. This means everything that decorators would set on the prototype is explicitly declared. I think it's ugly and messy, …

e2e benchmark fixes + perf improvements

---

packages/jit/src/templating/template-compiler.ts
packages/jit/test/unit/templating/template-compiler.integration.spec.ts
packages/jit/test/unit/templating/template-compiler.spec.ts

Besides some tests, I tried to add if / else linking. But it seems rather difficult to get access to resource constructor during compilation, which makes it hard to determine if a template controller requires linking. Test for if / else
https://github.com/aurelia/aurelia/blob/6bfc9e1914ec4314bb5c3b5256a2034817198d32/packages/jit/test/unit/templating/template-compiler.integration.spec.ts#L512-L524
@EisenbergEffect @fkleuver

fix(template-compiler): template controller instrs order, linking

---

packages/jit/src/templating/template-compiler.ts
packages/jit/test/unit/templating/template-compiler.integration.spec.ts
packages/jit/test/unit/templating/template-compiler.spec.ts
packages/runtime/src/binding/binding.ts
packages/runtime/src/binding/let-binding.ts
packages/runtime/src/templating/instructions.ts
packages/runtime/src/templating/renderer.ts
packages/runtime/test/unit/binding/let-binding.spec.ts
packages/runtime/test/unit/templating/renderer.spec.ts

With the template compiler in, I was able to verify the implementation. It's pretty ready, except I need to handle the scenario where `<let/>` is defined not at the start of a template:
```html
<template>
<div>${fullName}</div>
<let full-name.bind="firstName + ` ` + lastName"></let>
</template>
```
@EisenbergEffect @fkleuver Is there already a way to add a instruction without a target ? If no, probably I'll need to splice let instructions into the start of a definition instructions, beside adding some marker based on it (yak)
Note: Or we can also only support `<let/>` as is, which means if it's defined after a binding already created a property on binding context, it will just use it.

feat(Let): let binding

---

.circleci/config.yml
scripts/ci-env.ts
test/e2e/browserstack.conf.ts

@EisenbergEffect 
This should fix the nightly and make the each-commit test runs a bit faster than it currently does. Browserstack tests run for the 4 major browsers on latest version for each commit. Unit tests only run in chrome.
The full test suite (60+ browsers in browserstack) including benchmarks only run on commit to master.
The nightly runs the same thing as what's run on each commit with the addition of firefox unit tests.
Also posts allure results whether the PR test run failed or not.

chore(ci): make the distribution of tests more sensible

---

.circleci/config.yml
package.json
scripts/publish.ts
test/e2e/browserstack.conf.ts
test/e2e/package.json

So the process would be:
- `npm run prepare-release` -> updates all the versions and generates changelogs, but does not commit/tag/push anything
- Review that all is ok
- `git add . && git commit -m "v0.2.0" && git tag v0.2.0 -m "v0.2.0" && git push --follow-tags` (or something among those lines)
- CircleCI will build, run tests (incl e2e) and then (based on the tag it detected) do a squash merge into release and pushes to release
- The push to release then triggers the same workflow but with more extensive e2e tests, at the end of which it will start a publish job. This publish job will need manual approval. If you hit approve, it publishes to `@latest`
I'm not completely happy about this; it's a first draft of the release process. Will need to find ways to make it less redundant as well …

ci(all): add automated publish@latest script / minor tweaks

---

scripts/karma.conf.ts

Should have done this a long long time ago, sorry. Anyway, this speeds up the tests by about a factor 3. 
@bigopon @EisenbergEffect

chore(tests): use progress instead of mocha reporter to speed up the test runner

---

.circleci/config.yml

With the new circleci 2.1 this will be much easier to manage. Parameterized commands will also allow us to configure individual jobs more granularly based on the workflow they're running in (e.g. only run the bundle script if it's inside the nightly workflow). For the time being, I'm disabling the benchmarks and the allure reports to make the jobs run faster and eliminate some intermittent failures

ci: temporarily disable flaky and time-consuming jobs

---

packages/jit/src/templating/template-compiler.ts
packages/jit/test/unit/templating/template-compiler.spec.ts
packages/jit/test/unit/util.ts

`as-element` should not go through as `propertyBinding`. This is just temporary patch probably until we have a more beautiful solution

fix(template-compiler): remove node after parsing

---

packages/jit/src/templating/element-parser.ts
packages/jit/src/templating/semantic-model.ts
packages/jit/src/templating/template-compiler.ts
packages/jit/test/unit/templating/template-compiler.integration.spec.ts
packages/jit/test/unit/templating/template-compiler.spec.ts

This PR fixes template controllers on template elements, and also correctly processes multiple template controllers per element.
The fix itself could likely be distilled down to changing 2-3 lines of code, but I had to do a few cycles of refactoring to increase the clarity of the flow enough for the necessary changes to surface. That's why it's paired with a moderately sized refactor. Hopefully this refactor makes it easier to follow the flow for others as well.

template controller fixes

---

packages/jit/src/templating/semantic-model.ts
packages/jit/src/templating/template-compiler.ts
packages/jit/test/unit/templating/template-compiler.integration.spec.ts

@bigopon @EisenbergEffect 
I'm not sure in which scenario the flush is actually needed (is there any demo or tests to prove the situation?) because in this integration test you can see the value propagating all the way from the app to the 5th level nested custom element on startup, without a single flush..

template compiler tests

---

packages/kernel/src/di.ts
packages/kernel/test/unit/di.integration.spec.ts
packages/kernel/test/unit/di.spec.ts

There was a small bug in the alias registration fluent API for InterfaceSymbol and a few other minor oversights. Additionally, there were a number of errors in the tests themselves. This PR corrects all these issues and gets the full test set working with no more ignored tests.
Fixes #191

fix(DI): alias registration param order and tests

---

packages/runtime/src/templating/view.ts

@EisenbergEffect the chance that this ever matters is close to zero, but something about `Number.MAX_VALUE` just rubs me the wrong way. It's a crazy large number that can't even be displayed in non-scientific notation.
I thought about using `0xFFFFFF` instead (the max 32 bit value) because hand-wavey 32 bit integer vs 64 bit float things. But I like `0xFFFF` more. It's 65k, which may as well be unlimited, and I doubt anyone would ever utilize that much. But if they do, it's likely unintended and considering this remote possibility of some long-running app having a small memory leak this could make that small difference to prevent the memory usage from piling up to infinity. It's very tentative, I know. 
Here's an equally meaningless benchmark to give it something at least :) …

chore(view): use a more realistic cache size

---

packages/jit/src/template-compiler.ts
packages/jit/test/unit/template-compiler.spec.ts

This is to align with vCurrent behavior.
resolves #201

fix(TemplateCompiler): properly startup compilation with <template/>

---

packages/jit/test/unit/template-compiler.integration.spec.ts

This PR only adds integration tests for the app as a whole, and does not touch any framework code. The tests in particular focus on the integration between different flavors and combinations of template controllers.
I also reworked all the existing tests to explictly call setup and teardown, so that tests stay atomic even within loops, and don't accidentally share any state.
* Improving templating test coverage: https://github.com/aurelia/aurelia/issues/197
* bug 1 https://github.com/aurelia/aurelia/issues/218
* bug 2 https://github.com/aurelia/aurelia/issues/219
Quite a few (albeit exotic) combinations fail and they are commented out with // TODO's, explaining briefly what fails. Most notable:
- repeat+if/else on template elements results in the wrong nodes (namely the `<au-loc>` nodes) …

test(all): add more integration tests

---

packages/runtime/src/binding/binding-context.ts
packages/runtime/src/binding/observation.ts
packages/runtime/src/binding/observer-locator.ts
packages/runtime/src/binding/subscriber-collection.ts
packages/runtime/src/templating/custom-element.ts
packages/runtime/src/templating/resources/repeat.ts
packages/runtime/src/templating/resources/with.ts
packages/runtime/test/unit/binding/ast.spec.ts
packages/runtime/test/unit/binding/binding-context.spec.ts
packages/runtime/test/unit/binding/binding.spec.ts
packages/runtime/test/unit/binding/let-binding.spec.ts
packages/runtime/test/unit/binding/shared.ts
packages/runtime/test/unit/mock.ts
packages/runtime/test/unit/templating/scope-assistance.ts
packages/runtime/test/unit/templating/view.spec.ts

This PR should lay the groundwork for more intelligent features, optimizations, and increase the precision of typings by explicitly defining classes for `Scope`, `BindingContext`, `OverrideContext` and `ObserversLookup`.
The key thing is the ability to tell the difference between a "synthetic" binding context (as indicated by the `$synthetic` property) and a regular binding context (e.g. a user view model). By checking this property, we can take certain shortcuts or do additional things that would otherwise be unsafe to do. Especially template controllers such as the repeater will benefit from this, once utilized properly.
All that aside, classes perform slightly better in terms of memory than regular objects, so memory consumption will go down with this.
Loosely related to anything that …

refactor(binding-context): explicitly model scope, context and observer lookup

---

packages/runtime/src/binding/binding.ts
packages/runtime/test/unit/binding/binding.spec.ts

This is a small tweak with potentially big impact. When the `sourceExpression` in a Binding is an `AccessScope` and we're sure that there is at most 1 observer, then we can make these assumptions:
- The `newValue` we received into `handleChange()` is correct value (because there are no other observers that could have called the `handleChange`)
- The `newValue` we received is the latest value (because it's a naked `AccessScope` and not something that's wrapped in for example a valueConverter)
Side note: it's the `$kind` property that makes this more viable and interesting than it would be for the vCurrent AST, because there you would have to call `instanceof` which is much more expensive than direct number comparison. 
The existing binding tests (albeit a bit messy) are reasonably thorough …

perf(binding): reduce redundant calls to evaluate()

---

package-lock.json
package.json
scripts/karma.conf.ts

- Failed test assertions were logged to the console twice. Fixed this by switching around coverage and progress reporters.
- Failed tests were showing useless stack traces in both normal and `ChromeDebugging` mode where everything is on line 1. Fixed this by adding `source-map-support` and switching to devtool `inline-source-map`.
- Failed tests in `ChromeDebugging` mode were linking to nonexistent files after the above change, fixed this by switching to `eval-source-map` only in debugging mode
This makes debugging and troubleshooting tests a little nicer again @EisenbergEffect @bigopon

chore(karma-webpack): fix double error logging and stack trace sourcemaps

---

.circleci/config.yml

Use the aurelia circleci docker image (which has the correct git and machine config) for pushing to the repo and publishing to npm.
Also restore the `npm ci` cache before attempting to publish since we're using custom publish scripts. This caused the nightly to fail earlier.. :)

ci: use aurelia docker image for pushing/publishing, restore cache before publish

---

.circleci/config.yml

Fixes two small oversights in the publish jobs:
- Run the post-publish e2e tests *after* publishing to npm (currently runs in parallel)
- Use the correct git identity for pushing to dev and release

ci: make post-publish wdio test jobs wait for publish

---

packages/kernel/src/di.ts
packages/runtime/src/templating/renderer.ts
packages/runtime/src/templating/rendering-engine.ts

This PR fixes the type inference of the return type for `get()` and `getAll()` against the `IContainer` or `IServiceLocator` interfaces.
Before:
```ts
const cs = container.get(IChangeSet):
// cs is of type "{}"
const cs = container.get<IChangeSet>(IChangeSet):
// cs is of type "IChangeSet" (casting or explicitly type arguments are necessary)
```
After:
```ts
const cs = container.get(IChangeSet):
// cs is of type "IChangeSet"
const cs = container.get<IChangeSet>(IChangeSet):
// cs is of type "IChangeSet"
```

chore(di): fix get() and getAll() return types on IServiceLocator interface

---

docs/CONTRIBUTING.md
docs/SUPPORT.md

Some minor grammar tweaks and fixes in `CONTRIBUTING.md` and `SUPPORT.md`:
- `etc` -> `etc.`
- `behavio` -> `behavior`
- `first hand` -> `firsthand`
- And converted a couple of hard tabs to spaces, making them consistent with the rest of the file. (they indented differently in my editor making them appear weird/wrong)

doc: minor grammar/typo fixes

---

packages/jit/src/expression-parser.ts
packages/jit/test/unit/expression-parser.spec.ts

The built-in esprima that ships with `aurelia-cli` doesn't seem to recognize the exponentiation `**` operator introduced in ES2016.
That can be considered a bug in `aurelia-cli` that needs fixing, but on the same token if it breaks `aurelia-cli` it might break other tooling as well for unsuspecting users. So I refactored the expression-parser to stop using exponentiation.
Taking another close look, I realized, the manual number parsing is only about 25-30% faster on chrome than native and accounts for less than 1% of total parsing time. That total parsing time is typically less than 1-2ms even on large apps. And it's quite likely that chrome and friends will only get faster at this, so at some point the benefit is likely nonexistent.
So for a gain of a couple microseconds at best, I'm …

refactor(expression-parser): get rid of exponentiation to preserve ES2015 parser compatibility

---

packages/plugin-requirejs/src/component.ts
packages/plugin-requirejs/src/configuration.ts
packages/plugin-requirejs/src/processing.ts
packages/plugin-requirejs/src/types.ts
packages/plugin-requirejs/src/view.ts

Initial round of fixing lining warnings in `@aurelia/plugin-requirejs`.
Related to #249
Adding @types/requirejs introduces more issues than it solves. It's incomplete (i.e. isBuild is missing on the RequireConfig interface ) and it's creating conflicts:
```
node_modules/@types/node/index.d.ts(5984,5): error TS2300: Duplicate identifier 'mod'.
node_modules/@types/requirejs/index.d.ts(38,11): error TS2300: Duplicate identifier 'mod'.
node_modules/@types/requirejs/index.d.ts(422,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.
```
So I went for a (simplified) version of duck-typing. Just enough to match the parts of the API being used.
Executed without issues:
- lerna run lint …

style(plugin-requirejs): fix linting warnings

---

package-lock.json
package.json
packages/kernel/package-lock.json
packages/kernel/package.json
packages/kernel/src/di.ts

Use the official Reflect metadata API type definitions instead of rolling our own.
API proposal:
https://www.typescriptlang.org/docs/handbook/decorators.html#metadata
https://rbuckton.github.io/reflect-metadata/
Type definitions:
https://github.com/rbuckton/reflect-metadata
Related to #249.
As `@types/reflect-metadata` is deprecated we use the definitions bundled with `reflect-metadata`. Because this is outside the `@types` scope we need to manually reference the type definitions.
This also reintroduces some `any` types, but as they're part of the official spec proposal it seems a valid use-case, so I suppressed those warnings.
- `lerna run lint --scope=@aurelia/kernel` -> No new linting warnings
- `npm build` -> succeeds without errors.
- `npm test` -> succeeds without test failures.

style(kernel): use official Reflect metadata API type definitions

---

packages/kernel/src/interfaces.ts

This PR adds some clarifying JSDoc comments to the `Decoratable` and `Decorated` interfaces because the way I designed it (which can likely be improved) makes it a bit tricky to make sense of them. It's a side effect I believe, of making it easier to use them once you *do* understand them.
Loosely related to https://github.com/aurelia/aurelia/issues/249
Motivated by discussion in https://github.com/aurelia/aurelia/pull/262
I would like to invite @BBosman specifically (and @EisenbergEffect / @bigopon if you've got time) to look at the (intellisense rendered by the) JSDoc comment I added, and tell me if the types make sense after reading just that. If it does not, I need to do a better job obviously :)
This PR does not contain any code changes - the test is to verify whether the comments …

docs(interfaces): add explanation and example for decorator helper types

---

packages/runtime/src/binding/ast.ts

Fixes an issue with binding behaviors that had no test coverage yet. It surfaced when @Alexander-Taran tried to run the krausest benchmark. When re-binding a binding behavior it only checks if the behaviorKey is undefined, but it needs to check for null as well since that's what it's set to during unbind.
n/a
It's just one line of code :)
Verified the fix by running the krausest benchmark. Breaks no existing tests. Need to add additional tests (was already on my todo) for repeater mutations + binding behaviors after the lifecycle PR is merged in, since the test would break right after merging otherwise.
Add the appropriate tests

fix(binding): add null check to check for existing behaviorKey

---

packages/kernel/src/di.ts
packages/kernel/test/unit/di.spec.ts

This PR adds the `@transient` and `@singleton` decorators "back" (they already existed in vCurrent and were gone). The primary methods are exposed on the `DI` object for consistency with `inject` and `Resource.define`. They can be used as decorators and as expressions. Some examples:
```ts
// 1. declaration + decorator
@transient
class Foo { }
// 2. declaration + decorator expression
@transient()
class Foo { }
// 3. declaration + member expression
class Foo { }
DI.transient(Foo);
// 4. declaration + function expression (1. decorator)
class Foo { }
transient(Foo);
// 5. declaration + function expression (2. decorator expression)
class Foo { }
transient()(Foo);
// 6. class expression + member expression (returns class with strongly typed static register)
const Foo = DI.transient(class {}); …
```

feat(di): add transient and singleton decorators

---

packages/runtime/src/aurelia.ts
packages/runtime/src/binding/array-observer.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/binding-behavior.ts
packages/runtime/src/binding/binding-mode.ts
packages/runtime/src/binding/computed-observer.ts
packages/runtime/src/binding/dirty-checker.ts
packages/runtime/src/binding/element-observation.ts
packages/runtime/src/binding/event-manager.ts
packages/runtime/src/binding/map-observer.ts
packages/runtime/src/binding/observer-locator.ts
packages/runtime/src/binding/property-observer.ts
packages/runtime/src/binding/resources/binding-mode-behaviors.ts
packages/runtime/src/binding/resources/debounce-binding-behavior.ts
packages/runtime/src/binding/resources/sanitize.ts
packages/runtime/src/binding/resources/self-binding-behavior.ts
packages/runtime/src/binding/resources/signals.ts
packages/runtime/src/binding/resources/throttle-binding-behavior.ts
packages/runtime/src/binding/resources/update-trigger-binding-behavior.ts
packages/runtime/src/binding/set-observer.ts
packages/runtime/src/binding/signaler.ts
packages/runtime/src/binding/subscriber-collection.ts
packages/runtime/src/binding/svg-analyzer.ts
packages/runtime/src/binding/target-observer.ts
packages/runtime/src/binding/value-converter.ts

Linting fixes in the `binding` part of `@aurelia/runtime`
Related to #249.
Mostly syntactical linting fixes, but also a couple of strict type checks which could use some scrutiny.
Hit a few files also touched in #250, but I think these changes are compatible.
- `lerna run lint --scope=@aurelia/runtime` -> Significant drop in the number of reported warnings
- `npm run build` -> Succeeded without errors.
- `npm run test` -> Succeeded without test failures.
Once #250 lands the linting warnings that have a bit more impact in `binding` can be tackled, together with the warnings in the root and templating files.
Another follow up would be implementing the outcome of https://github.com/aurelia/aurelia/pull/262#discussion_r230880271 outside `binding` and work on …

style(runtime): fix linting warnings in binding

---

tslint.json

Disable the `promise-function-async` rule for `tslint` for now.
Paraphrasing @fkleuver from https://github.com/aurelia/aurelia/issues/273#issuecomment-437924643:
> The Esprima parser version that ships with aurelia-cli only understands ES2015.
> Later syntax causes aurelia-cli to fail in the transform phase. 
> Until aurelia-cli is updated (and other popular bundlers!), we need to avoid ES2015 incompatible syntax altogether.
As we're not allowed to use `async` for now, it's counterproductive to have the linter complain about it missing.
- Related to #249 
- Fixes #273 
Disabling the rule altogether (for now) is a better solution than sprinkling the code with `// tslint:disable` statements imho. 
Ran:
- `npm run lint` and it didn't warn about `promise-function-async` issues anymore.
Hope …

chore: disable promise-function-async linting rule

---

packages/kernel/src/di.ts
packages/runtime/src/binding/binding-behavior.ts
scripts/generate-tests/util.ts
scripts/test-suite.ts
tslint.json

Add `Decorate` and `Decorated` typeguards to `@bindingBehavior`.
Related to https://github.com/aurelia/aurelia/pull/262#discussion_r230879707 and #264.
Just `@bandingBehaviour` for now, to validate my interpretation of #264. 
Ran:
- `npm run lint` without introducing new warnings
- `npm run build` without errors
- `npm run test` without test failures
Once this is done, I'll start rolling this out to other decorators.

chore(runtime): decorate bindingBehavior

---

packages/jit/src/binding-command.ts
packages/jit/src/template-compiler.ts
packages/jit/test/integration/prepare.ts
packages/runtime/src/aurelia.ts
packages/runtime/src/binding/binding-behavior.ts
packages/runtime/src/binding/value-converter.ts
packages/runtime/src/definitions.ts
packages/runtime/src/html-renderer.ts
packages/runtime/src/resource.ts
packages/runtime/src/templating/create-element.ts
packages/runtime/src/templating/custom-attribute.ts
packages/runtime/src/templating/custom-element.ts
packages/runtime/src/templating/lifecycle-attach.ts
packages/runtime/src/templating/lifecycle-bind.ts
packages/runtime/src/templating/lifecycle-render.ts
packages/runtime/src/templating/resources/compose.ts
packages/runtime/src/templating/resources/if.ts
packages/runtime/src/templating/resources/repeat.ts
packages/runtime/src/templating/resources/replaceable.ts
packages/runtime/src/templating/resources/with.ts

Decorated `@bindingCommand`, `@valueConverter`, `@customAttribute` and `@customElement` with `Decorate` and `Decorated` typeguards.
Also added a base `IResourceDefinition` interface per the discussion at https://github.com/aurelia/aurelia/pull/272#issuecomment-438000257.
Follow up to #272.
- This includes the next step in the `Source` to `Definition` rename. I think I got all occurrences but a check couldn't hurt.
- All decorators define their `ISomething` and `ISomethingType` interfaces in the same file, with the exception of `customElement` and `customAttribute`. I decided to move those types to their corresponding files as well for consistency. Is this the right approach?
- Added and reverse engineered `IValueConverter` from current usage in the codebase, so a check if it's valid would …

refactor: add typeguards to decorators and rename Source to Definition

---

packages/kernel/src/platform.ts
packages/kernel/src/reporter.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/binding-context.ts
packages/runtime/src/binding/binding.ts
packages/runtime/src/binding/call.ts
packages/runtime/src/binding/computed-observer.ts
packages/runtime/src/binding/connectable.ts
packages/runtime/src/binding/interpolation-binding.ts
packages/runtime/src/binding/let-binding.ts
packages/runtime/src/binding/listener.ts
packages/runtime/src/binding/ref.ts
packages/runtime/src/binding/set-observer.ts
packages/runtime/src/dom.ts
packages/runtime/src/lifecycle.ts
packages/runtime/src/observation.ts
packages/runtime/src/templating/resources/repeat.ts

@fkleuver mentioned in https://github.com/aurelia/aurelia/pull/274#discussion_r232724663 that he wanted to get rid of `StrictAny` in favour of `unknown`. This PR does just that.
Follow up to #274 and related to #249.
Notable changes:
- Mostly just a straight up search and replace for `StrictAny` to `unknown` and then upstreamed those changes to all call sites.
- As a consequence I had to introduce casting in a couple of places. The ones in `packages/runtime/src/templating/resources/repeat.ts` could probably be tightened up a bit?
I also snuck in some linting fixes:
- Removed some unneeded tslint suppressions.
- Removed all suppressions for `no-empty` and gave them a `return;`.
Ran the usual tests.
See #249.

refactor(runtime): remove StrictAny in favor of unknown

---

packages/debug/src/reporter.ts
packages/jit/test/unit/template-compiler.spec.ts
packages/kernel/src/di.ts
packages/kernel/test/unit/di.spec.ts
packages/runtime/src/binding/set-observer.ts
packages/runtime/src/definitions.ts
packages/runtime/src/resource.ts

Removed and fixed almost all `no-reserved-keywords` suppressions.
There are 8 left, of which 7 are valid suppressions imho. Number 8 is in `ITargetedInstruction` and its kin, but when I started fixing those it was turtles all the way down, so I'd like to leave that one as a separate issue for now.
One more for #249 😄 
Just the usual checks and maybe validate that the remaining 7 are indeed valid suppressions.
n/a
Fix `ITargetedInstruction` and its kin.

refactor: remove no-reserved-keywords suppressions and fix most of them

---

packages/jit/src/ast.ts
packages/jit/src/attribute-parser.ts
packages/jit/src/attribute-pattern.ts
packages/jit/src/configuration.ts
packages/jit/src/element-parser.ts
packages/jit/src/index.ts
packages/jit/src/semantic-model.ts
packages/jit/test/unit/attribute-pattern.spec.ts
packages/jit/test/unit/template-compiler.spec.ts
packages/kernel/src/di.ts

Introduces a new decorator `@attributePattern` that allows you to register a custom pattern for parsing attribute names.
The only special keyword is `PART` which means "match any number of characters that does not occur in the provided symbol list" ~"match any number of characters out of `-_$+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789`". Any characters in the pattern that are not included in this list will automatically be interpreted as symbols (or part separators).~
You place this decorator on a class, with one or more patterns per decorator. Then you add methods to the class corresponding to the patterns in the decorator - those methods will be called with the interpretation result if a pattern for that class is matched.
The interpretation result is the raw …

view compiler extension point (part 1/2)

---

packages/jit/src/binding-command.ts
packages/jit/src/semantic-model.ts
packages/kernel/src/di.ts
packages/plugin-requirejs/src/processing.ts
packages/runtime/src/binding/binding-context.ts
packages/runtime/src/binding/binding.ts
packages/runtime/src/binding/computed-observer.ts
packages/runtime/src/binding/let-binding.ts
packages/runtime/src/binding/observer-locator.ts
packages/runtime/src/binding/resources/attr-binding-behavior.ts
packages/runtime/src/binding/resources/debounce-binding-behavior.ts
packages/runtime/src/definitions.ts
packages/runtime/src/dom.ts
packages/runtime/src/html-renderer.ts
packages/runtime/src/instructions.ts
packages/runtime/src/observation.ts
packages/runtime/src/templating/create-element.ts
packages/runtime/src/templating/resources/compose.ts
packages/runtime/src/templating/resources/repeat.ts
packages/runtime/src/templating/resources/with.ts
packages/runtime/src/templating/view.ts
tslint.json

More linting fixes. This time its mostly `any` to more strict type conversions.
Related to #249.
Notable changes:
- Mostly `any` conversions where I could upstream already existing types.
- ~~In `ITargetedInstruction` the `type` property will be renamed to `Type` in a future PR, but as far as I know there are no such plans for `from`, so I suppressed those warnings.~~
- Disabled the `no-reserved-keywords` linting rule, see discussion below.
Depend on CircleCI.
- Check types used by Scope (https://github.com/aurelia/aurelia/pull/297#discussion_r234462754)
- Maybe undo some renames that were done just to satisfy `no-reserved-keywords`.
- And more, see #249.

refactor: more any to strict typing conversions

---

packages/debug/src/reporter.ts
packages/runtime/src/binding/array-observer.ts
packages/runtime/src/definitions.ts

Now that the decision is made to disable the `no-reserved-keywords` linting rule (See #297) it's better to revert some of the changes made just to satisfy that linting rule, when their original names better suited their purpose.
Part of #249, follow up to #297 and partially reverts #262 and #290.
Straight up renames.
Will increase the number of linting errors until #297 is merged and `no-reserved-keywords` is actually disabled.
Trust in CircleCI
See #249.

refactor: partially revert renames due to no-reserved-keywords

---

packages/runtime/src/binding/computed-observer.ts
packages/runtime/src/binding/subscriber-collection.ts
packages/runtime/src/binding/target-observer.ts
packages/runtime/src/lifecycle.ts
packages/runtime/src/templating/lifecycle-render.ts
packages/runtime/src/templating/resources/if.ts

Fixes all warnings related to the `no-floating-promises` tslint rule.
Part of #249.
The linting rule warns on every Promise-chain that does not have a `catch` at the end. So we add one where I'm just propagating the error up the stack.
Trust CircleCI.
See #249.

refactor: fix no-floating-promises linting warnings

---

packages/examples/dbmonster-a/app-config.ts
packages/examples/test-aot/app-config.ts
packages/jit/src/ast.ts
packages/jit/src/semantic-model.ts
packages/jit/test/unit/template-compiler.spec.ts
packages/runtime/src/dom.ts
packages/runtime/test/unit/mock.ts
packages/runtime/test/unit/util.ts

Shortens the `au-marker` element name to `au-`.
This makes templates quite a bit shorter, thereby easier to read and smaller in size (for pre-compiled templates).
Originally the idea was to rename it to `au`, but that wouldn't make it compliant with WebComponents, hence the dash. There's no rule that a custom element name cannot end with a dash, and something like `a-u` just seems very awkward.
It's a bit weird ending with a dash, but I actually quite like it. It stands out.
Wonder what others think @EisenbergEffect @bigopon ?
N/A
N/A
Verified that a custom element with this name can be created via `customElements.define`
N/A

perf(all): shorten au-marker to au-m

---

packages/kernel/src/di.ts
packages/runtime/src/binding/target-accessors.ts
tslint.json

A few linting fixes for `di`.
Edit: added a `tslint.json` tweak to globally allow usage of the `xlink` namespace and removed a corresponding suppression.
Part of #249 
Once this is merged only `kernel/src/di.ts`, `jit/src/expression-parser.ts` and `runtime/src/observation.ts` still have linting errors, excluding the `completed docs` rule, and most of them are `no-any` errors.
CircleCI
See #249.

refactor(kernel): linting fixes for di

---

packages/jit/src/binding-command.ts
packages/kernel/src/interfaces.ts
packages/runtime/src/binding/array-observer.ts
packages/runtime/src/binding/call.ts
packages/runtime/src/binding/computed-observer.ts
packages/runtime/src/binding/dirty-checker.ts
packages/runtime/src/binding/element-observation.ts
packages/runtime/src/binding/map-observer.ts
packages/runtime/src/binding/observer-locator.ts
packages/runtime/src/binding/property-observation.ts
packages/runtime/src/binding/set-observer.ts
packages/runtime/src/binding/subscriber-collection.ts
packages/runtime/src/binding/target-accessors.ts
packages/runtime/src/binding/target-observer.ts
packages/runtime/src/observation.ts
packages/runtime/src/templating/create-element.ts

This is a WIP.
This changes `IIndexable` from `any` to `unknown` and fixes call sites, propagating out to the API boundaries. It also switches from `IIndexable` to base `object` in a few places where we're not actually interested type-wise that it is indexable, just that it's an object. 
Part of #249.
Is this the right way to go? Especially interested in feedback from @fkleuver as he had some ideas on where he wanted to go with this, but open to feedback from all. 👍
(And all these changes are just for one `any` -> `unknown` linting warning fix 😁)
CircleCI
See #249.

refactor: linting fixes for IIndexable

---

.codeclimate.yml

The `sonarts` and `tslint-microsoft-contrib` custom tslint rules cause CodeClimate to crash. This PR disables tslint on CodeClimate following discussion around https://github.com/aurelia/aurelia/pull/310
Follow-up to: https://github.com/aurelia/aurelia/pull/310
We could create an secondary tslint.json config with just the rules that CodeClimate supports, and point codeclimate.yml to that one. This isn't particularly important since we already have a lint job on CI, but it is a potential point of improvement for the future

chore(codeclimate): disable tslint on codeclimate

---

packages/debug/src/reporter.ts
packages/jit/src/element-parser.ts
packages/jit/src/expression-parser.ts
packages/jit/src/semantic-model.ts
packages/jit/src/template-compiler.ts
packages/kernel/src/di.ts
packages/plugin-svg/src/svg-analyzer.ts
packages/runtime/src/aurelia.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/collection-observer.ts
packages/runtime/src/binding/element-observation.ts
packages/runtime/src/binding/observer-locator.ts
packages/runtime/src/binding/property-observation.ts
packages/runtime/src/binding/property-observer.ts
packages/runtime/src/binding/resources/self-binding-behavior.ts
packages/runtime/src/binding/resources/update-trigger-binding-behavior.ts
packages/runtime/src/binding/subscriber-collection.ts
packages/runtime/src/binding/target-accessors.ts
packages/runtime/src/binding/target-observer.ts
packages/runtime/src/definitions.ts
packages/runtime/src/dom.ts
packages/runtime/src/html-renderer.ts
packages/runtime/src/lifecycle.ts
packages/runtime/src/templating/custom-attribute.ts
packages/runtime/src/templating/custom-element.ts
packages/runtime/src/templating/lifecycle-attach.ts
packages/runtime/src/templating/lifecycle-render.ts
packages/runtime/src/templating/resources/repeat.ts
tslint.json

Typescript has two ways of type assertion:
1. `variable as type`
2. `<type>variable`
In the codebase both ways are used interchangeably. For consistency it would be better to pick one and stick to it. After discussing it with @fkleuver we decided to go for the `as` style type assertion, because:
- When using TypeScript with JSX, only as-style assertions are allowed. ([Reference](https://www.typescriptlang.org/docs/handbook/basic-types.html))
- It reduces confusion when used in conjunction with Generics.
So this PR turns on the related linting rule and changes all type assertions to use the `as` style.
Related to #249.
Migration was done using the `--fix` option of `tslint`.
CircleCI
See #249.

refactor: standardise on "as" type casts

---

packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/binding-context.ts
packages/runtime/src/definitions.ts
packages/runtime/src/dom.ts
packages/runtime/src/lifecycle.ts
packages/runtime/src/resource.ts
packages/runtime/src/templating/custom-attribute.ts
packages/runtime/src/templating/custom-element.ts
packages/runtime/src/templating/lifecycle-render.ts
packages/runtime/src/templating/resources/compose.ts
packages/runtime/src/templating/resources/if.ts
packages/runtime/src/templating/resources/repeat.ts
packages/runtime/src/templating/resources/with.ts
packages/runtime/src/templating/view.ts

Refactoring `runtime` to adhere more to `strictNullChecks`.
Part of #254.
This is just a partial fix, but I decided to get some of the low hanging fruit out of the way first, before going for the bigger changes.
Trust in CircleCI.
Do the rest and turn the options on by default in the `tsconfig` files.

refactor(runtime): strictNullChecks fixes

---

examples/jit-aurelia-cli-ts/package.json
examples/jit-browserify-ts/package.json
test/wdio/cases/dev/jit-aurelia-cli-ts/package.json
test/wdio/cases/dev/jit-browserify-ts/package.json
test/wdio/cases/latest/jit-aurelia-cli-ts/package.json
test/wdio/cases/latest/jit-browserify-ts/package.json
test/wdio/cases/local/jit-aurelia-cli-ts/package.json
test/wdio/cases/local/jit-browserify-ts/package.json

Gulp finally published `4.0.0` to their `latest` channel, so the `next` semver tag stopped working and broke the `aurelia-cli-ts` example. In addition, the `latest` now points to `4.0.0` which breaks the browserify example. This PR fixes both issues.
Build broke
N/A
CircleCI tests should pass
N/A

chore(examples): update gulp semver range to reflect 4.0.0 release

---

packages/aot/package.json
packages/debug/package.json
packages/jit/package.json
packages/kernel/package.json
packages/plugin-parcel/package.json
packages/plugin-requirejs/package.json
packages/plugin-svg/package.json
packages/plugin-webpack/package.json
packages/router/package.json
packages/runtime/package.json
packages/testing/package.json
packages/validation/package.json
scripts/bundle.ts

This addresses some difficulties for myself, @bigopon and @jwx with regards to building test apps inside the repo using relative paths. Currently you'll have to `npm run bundle:dist` for any updates to propagate and this takes about a minute for all packages.
This PR allows you to `npm run bundle` on individual package level, making it more viable to use a local test app for developing purposes with somewhat quick iterations.
`npm run bundle:dist` only needs to be run once so the dependent bundles exist. After that, you can `npm run bundle` for example inside `packages/router` to refresh the router for the test app. No need to `npm run build` as well (but in case of any typing errors you might still want to try this though)
N/A
N/A
Verified with the router package
N/A

chore(all): add script to bundle only a single package

---

packages/jit/src/template-binder.ts
packages/jit/test/integration/template-compiler.kitchen-sink.spec.ts

@jwx discovered this the hard way in his router test app, but apparently I broke the compiler when there are comments. Big oops. I added traversal for all node types back in and all should work again as it did before.
N/A
Added traversal for other node types and reused `bindChildren` in `template-binder`
Added a few xml-based tests to verify all node type traversals don't cause the compiler to hang or crash. This is just a bit quick-n-dirty but it does the job for now
Add more complete tests for the different document types (html, xml, svg) that can be parsed by the browser as well as rendering for these.

fix(template-binder): correctly traverse not-compilable node types

---

test/browserstack/package-lock.json
test/browserstack/package.json
test/browserstack/tsconfig.json
test/browserstack/webpack.config.js

Fix for the browserstack tests.
Switching to tsc build outputs with es modules broke browserify (which browserstack was using). I tried parcel but that results in every dependency getting bundled 10 times or so. Webpack seemed to be the easiest solution.
N/A
N/A
Verified the running app locally, it *should* work on CI as well.
N/A

test(browserstack): switch to webpack to fix the e2e job

---

.vscode/launch.json
packages/jit-html/test/integration/template-compiler.compose.spec.ts
packages/jit-html/test/integration/template-compiler.kitchen-sink.spec.ts
packages/kernel/src/di.ts
packages/kernel/src/resource.ts
packages/kernel/test/di.spec.ts
packages/router/src/viewport.ts
packages/runtime-html/src/create-element.ts
packages/runtime/src/aurelia.ts
packages/runtime/src/renderer.ts
packages/runtime/src/rendering-engine.ts
packages/runtime/src/resources/custom-element.ts
packages/runtime/src/templating/lifecycle-render.ts
packages/runtime/test/au-dom.ts
packages/runtime/test/resources/custom-element.dependencies.spec.ts
packages/runtime/test/template.spec.ts
packages/runtime/test/templating/custom-element.$hydrate.spec.ts

This PR fixes locally registered dependencies in jit mode (and a small bit of test cleanup).
- `createRenderContext` is called [much earlier](https://github.com/aurelia/aurelia/compare/fix-local-deps?expand=1#diff-b12a454f7d84dd07c94592e2fb3b0a30R257) and is also passed into the template compiler so that the resources are available throughout. 
- the render context becomes a mandatory argument in a couple places where it was optional before (but it may be `null`), making the parameters a bit more visible. 
- render context is also passed via `hydrate` now so that you actually get a proper container tree representing the resource tree, instead of only sibling containers based on the root like it was before
- A special `resourceLookup` object is added to the container where any resolvers …

Fix local deps

---

packages/runtime/src/observation/computed-observer.ts
packages/runtime/src/observation/dirty-checker.ts
packages/runtime/test/observation/computed-observer.spec.ts
packages/runtime/test/util.ts

This PR fixes (and verifies) computed observation
N/A (was an outstanding TODO)
- Removed `GetterController` and merged it into `GetterObserver`, reducing the overall call stack depth and complexity of the implementation.
- Removed `DirtyChecker` fallback when `Proxy` is not available, since this falls under IE11 compatibility which I think shouldn't be clogging the code too much right now. Better tackle that framework-wide as a whole later on, taking a good look at the best polyfill options etc.
- Separated batched and synchronous dependencies, making computed observation in principle synchronous like the rest (DOM and array changes are batched anyway) and removing the need for queueing the computed observer itself in the lifecycle.
- Various small tweaks and fixes regarding problematic …

feat(runtime): fix+test the computed observer

---

packages/jit-html/src/template-compiler.ts
packages/jit-html/src/template-element-factory.ts
packages/jit/src/attribute-parser.ts
packages/kernel/src/interfaces.ts
packages/router/src/resources/viewport.ts
packages/router/src/router.ts
packages/runtime-html/src/html-renderer.ts
packages/runtime-html/src/observation/observer-locator.ts
packages/runtime-html/src/resources/binding-behaviors/update-trigger.ts
packages/runtime-html/src/resources/custom-elements/compose.ts
packages/runtime/src/lifecycle.ts
packages/runtime/src/observation/observer-locator.ts
packages/runtime/src/renderer.ts
packages/runtime/src/rendering-engine.ts
packages/runtime/src/resources/binding-behaviors/signals.ts
packages/runtime/src/resources/custom-attributes/if.ts
packages/runtime/src/resources/custom-attributes/repeat.ts
packages/runtime/src/resources/custom-attributes/replaceable.ts
packages/runtime/src/resources/custom-attributes/with.ts
packages/runtime/src/resources/value-converters/sanitize.ts

As mentioned in https://github.com/aurelia/aurelia/pull/366#issuecomment-454895508 by @fkleuver.
> A nice follow up might be to give `InterfaceSymbol` the `unknown` type argument as a default, so the whole thing doesn't need to be written out in full everywhere.
Follow up to #366.
n/a
CircleCI
n/a

refactor: make unknown the default for InterfaceSymbol

---

packages/jit-html/test/integration/di-registrations.spec.ts

Fixes a regression in the DI registration unit tests caused by the proxy observer PR.
It slipped through the crack because I thought the tests on master were failing solely because of the package-lock issue with the browserstack tests.

chore(jit-html): fix unit tests

---

examples/jit-aurelia-cli-ts/package.json
packages/examples/e2e-benchmark/vcurrent/package-lock.json
packages/examples/e2e-benchmark/vcurrent/package.json
test/wdio/cases/dev/jit-aurelia-cli-ts/package.json
test/wdio/cases/latest/jit-aurelia-cli-ts/package.json
test/wdio/cases/local/jit-aurelia-cli-ts/package.json

This PR fixes an open security alert on the vcurrent e2e benchmark project which had the latest event-stream installed, and also pins the event-stream version to 3.3.4 (the latest safe version) on other packages that had it set to `latest`.

chore(all): pin event-stream to safe version 3.3.4 in all package.jsons

---

packages/jit-html/test/integration/template-compiler.kitchen-sink.spec.ts
scripts/karma.conf.ts

Somewhere along the line CircleCI stopped being able to parse the generated `test-results.xml` making it impossible to see which tests failed on CI (you only see that *something* failed and have to run them all locally to find out which).
This PR is solely intended to fix that problem.

CI: fix test result report

---

packages/kernel/src/di.ts
packages/plugin-svg/src/svg-analyzer.ts
packages/runtime-html/src/binding/listener.ts
packages/runtime-html/test/observation/observer-locator.spec.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/binding.ts
packages/runtime/src/binding/call.ts
packages/runtime/src/binding/ref.ts
packages/runtime/src/observation/array-observer.ts
packages/runtime/src/observation/binding-context.ts
packages/runtime/src/observation/map-observer.ts
packages/runtime/src/observation/property-observer.ts
packages/runtime/src/observation/set-observer.ts
packages/runtime/src/renderer.ts
packages/runtime/src/resources/custom-attributes/repeat.ts
packages/runtime/test/observation/observer-locator.spec.ts
packages/runtime/test/observation/proxy-observer.spec.ts

Just a quick in-between PR to make a few small tweaks across the project that needed to happen for a while
- Replaced `delete obj.property` with `Reflect.deleteProperty(obj, property)` for consistency
- Pre-declare variables with `let` instead of declaring them with `const` on each iteration in loops
- Replace `Object.defineProperty` with `Reflect.defineProperty` for consistency
- Eliminate a few locally declared variables where they wouldn't have any perf benefit

perf(all): pre-declare variables used in loops

---

packages/kernel/src/eventaggregator.ts
packages/kernel/src/index.ts
packages/kernel/test/eventaggregator.spec.ts

Ports EventAggregator over from vCurrent. Basic port of both `src` and `test`, with linting and typing changes applied.
n/a
Notable changes:
- ~~Added a `static register` method for registration with DI, with test.~~
- Made the callback signature explicit `(data?: unknown, event?: string) => unknown` (was `Function`) and generic and gave it its own type `EventAggregatorCallback<T>` for ease of use and readability.
- You can subscribe by channel (`string`) or type (`Constructable`, was `any`) and added function overloads (with generics) to make the API clearer.
- Dropped the `aurelia-logger` dependency and switched to `Reporter` for logging/throwing errors.
- Added some missing tests to increase coverage.
- Many cosmetic linting fixes (almost all spacing related).
CircleCI.
Decide if we …

feat(kernel): port EventAggregator to vNext

---

packages/fetch-client/src/retry-interceptor.ts
packages/runtime-html/src/dom.ts
packages/runtime/src/observation/binding-context.ts
packages/runtime/src/resources/custom-attributes/repeat.ts
packages/runtime/src/templating/lifecycle-bind.ts
tslint.json

Mark linting violations instead of errors, fix some straggler violations, disable `no-useless-cast linting rule` linting rule and mark `no-unnecessary-type-assertion` as warning for now to appease CircleCI.
Resolves: #249 
- Set default severity to `error`
- Disabled `no-useless-cast linting rule` linting rule as its similar to `no-unnecessary-type-assertion`.
- Marked `no-unnecessary-type-assertion` as `warning` as it triggers false positives on CircleCI and added a TODO comment to fix that issue.
- Fixed a few straggler linting errors.
CircleCI
- A few rules are still marked as `warning`, eventually these violations need to be fixed and the rules set to the default severity as well.

chore: set default linting severity to "error"

---

package-lock.json
package.json
packages/jit-html-browser/test/setup.ts
packages/jit-html/src/template-binder.ts
packages/jit-html/test/integration/binding-commands.spec.ts
packages/jit-html/test/integration/html-attributes.spec.ts
packages/jit-html/test/unit/template-compiler.spec.ts
packages/kernel/src/index.ts
packages/kernel/src/interfaces.ts
packages/runtime/src/aurelia.ts
packages/runtime/src/observation/self-observer.ts
packages/runtime/src/observation/target-observer.ts
packages/runtime/test/observation/property-observation.spec.ts
scripts/karma.conf.ts

- Fixes #423 (oldValue was not stored in the target observer so it never recognized the difference between an initial value and an empty string set as the next value)
- Adds `InjectArray` as a shorthand type for `ReadonlyArray<InterfaceSymbol | Constructable | string>`
- Register the app host as `INode` so it can be injected into the root component
- Removes coercion from change handler in SelfObserver and moves the callback to after `callSubscribers`, so updates are actually already propagated and/or queued when the callback is invoked and you can work with the results
- Fixes #421 by removing interpolations from attribute values during compilation
- Fixes #423 
Changes probably speak for themselves :)
- Added ~2k tests to verify the various combinations of class binding initialization …

DOM binding fix and misc

---

packages/router/src/queued-browser-history.ts
packages/router/test/e2e/doc-example/src/components/about.ts
packages/router/test/unit/instruction-resolver.spec.ts
packages/router/test/unit/queued-browser-history.spec.ts

This PR makes the `go` method in the queued browser history await the following `popstate` event before resolving. It also adds the option to make `go` not trigger the `popstate` event callback and thereby behaving like `pushState` and `replaceState`.
A small thing that'll be important for the refactor that's currently going on.
- Tests still pass.
- Added some new tests to verify change.
- Continue refactor with part 2 (out of probably no more than 3)

Dynamic routing: improve queued browser history

---

packages/router/src/history-browser.ts
packages/router/src/viewport-content.ts
packages/router/test/e2e/doc-example/src/app.ts

This PR makes the `pop` method take advantage of the new suppress popstate event parameter of the `go` method in the queued browser history.
Some low hanging fruit before the bigger refactoring continues.
- Tests still pass.
- Continue refactor

Dynamic routing: clean up history pop

---

packages/jit-html-browser/test/setup.ts
packages/jit-html/test/integration/replaceable.spec.ts
packages/jit-html/test/integration/replaceable_n_tc.spec.tsx
packages/jit-html/test/integration/replaceable_repeat.spec.tsx
packages/jit-html/test/integration/replaceable_with.spec.tsx
packages/jit-html/test/integration/util.ts
packages/jit-html/test/tsconfig.json
scripts/karma.conf.ts
scripts/tsconfig.test.json

This PR adds test cases (most are failing) for many common scenarios where `[replaceable]` is being used in conjunction with important template controllers `[repeat]`, `[with]`
Backward compatibility and feature completeness
I started to use some JSX as empty space in is hard to eliminate within the middle of template string
N/A
Moar tests
@EisenbergEffect @fkleuver

chore(replaceable): add failing tests for common scenarios

---

packages/router/src/history-browser.ts
packages/router/src/router.ts
packages/router/test/e2e/doc-example/index.ejs
packages/router/test/e2e/doc-example/src/app.ts

This PR makes the `cancel` method take advantage of the new suppress popstate event parameter of the `go` method in the queued browser history.
Some low hanging fruit before the bigger refactoring continues.
- Tests still pass.
- Continue refactor

Dynamic routing: clean up history cancel

---

packages/router/src/history-browser.ts
packages/router/src/router.ts

This PR removes the `redirect` method from history browser.
Some low hanging fruit before the bigger refactoring continues. This should be reviewed and merged after https://github.com/aurelia/aurelia/pull/438.
- Tests still pass.
- Continue refactor

Dynamic routing: remove redirect from history browser

---

test/browserstack/tsconfig.json

Our `browserstack` broke with the release of [webdriverio 5.6.0](https://twitter.com/webdriverio/status/1098534277459918848)
> 💥 Another update for all our @typescriptlang users: with the latest v5.6.0 (just released) we changed the way you have to define your WebdriverIO types depending whether you use the sync mode or async mode. Please have a look here: https://t.co/h0PkcfRBK7
They made async the default and sync opt-in, while it used to be the other way round.
See #444, #425, and #430 for examples of `browserstack` currently failing.
n/a
Switched to the `@wdio/sync` types, as described in the article linked from the tweet.
See if CircleCI starts working again.
n/a

build: fix browserstack

---

renovate.json

We want to "automate" dependency updating a bit through `renovate`. By removing the `renovate.json` we can retrigger the onboarding experience and set it up the way we want.
From: https://renovatebot.com/docs/reconfigure-renovate/
Follow up to #450
Reverts #284 
Restarts the `renovate` onboarding experience so we can (re)configure it the way we want.
n/a
Re-configure `renovate`

chore: nuke renovate.json to retrigger onboarding

---

packages/router/src/route-table.ts
packages/router/src/router.ts

This PR illustrates how the router's extension points are used to integrate traditional route table routes with the router. It contains a `RouteTable` skeleton that uses the extension points with a simple, hard coded example.
In summary, any route component, be it a route table or a dynamic routing syntax, can do whatever it wants and offer whatever API it wants towards developers as long as it translates to and from sets of viewport instructions when dealing with the router.
The `RouteTable` contains a simple, hard coded example that works (with limitations) for the application in `packages/router/test/e2e/doc-example` to illustrate …

Dynamic routing: RouteTable skeleton and extension points

---

lerna.json
package.json

Always `hoist` all packages through `lerna`.
n/a
I can't think of a situation where we don't want to have `lerna` host packages.
The `package.json` scripts have the `--hoist` argument, but that doesn't ensure hoisting when somebody manually does a `lerna bootstrap`. By adding it to `lerna.json` we can guarantee hosting.
CircleCI.
n/a

Always hoist

---

packages/jit-html/test/integration/util.ts
packages/jit/src/binding-command.ts
packages/kernel/src/di.ts
packages/kernel/src/interfaces.ts
packages/kernel/test/di.spec.ts
packages/router/src/nav-route.ts
packages/router/test/e2e/layouts/src/app.ts
packages/runtime-html/src/dom.ts
packages/runtime-html/src/projectors.ts
packages/runtime/src/binding/connectable.ts
packages/runtime/src/resources/binding-behavior.ts
packages/runtime/src/resources/custom-attribute.ts
packages/runtime/src/resources/custom-element.ts
packages/runtime/src/resources/value-converter.ts
packages/runtime/src/templating/bindable.ts
packages/runtime/src/templating/lifecycle-bind.ts
packages/runtime/test/binding/ast.spec.ts
packages/runtime/test/binding/binding.spec.ts
packages/runtime/test/renderer.spec.ts
packages/runtime/test/resources/custom-element.resource.spec.ts

Reap the benefits of the recent [Typescript 3.3](https://blogs.msdn.microsoft.com/typescript/2019/01/31/announcing-typescript-3-3/) update.
n/a
Notable changes:
- Removed the `T & any` hack from `Constructable`, as it's no longer needed.
- That triggered some typing errors that where previously masked due the use of `any`, so I fixed those.
- Removed some linting supressions that are no longer needed, as the false positives no longer trigger.
- Minor linting changes
CircleCI
n/a

Use Typescript

---

packages/kernel/src/interfaces.ts

Merging both #425 and #451 together broke `master` as they had some unintended interactions.
This PR adds a temporary workaround to get `master` into a buildable state.
Related to #425 and #451
Just a quick hack to get `master` buildable.
CircleCI
Find a clean and permanent solution.

Fix master

---

packages/router/src/instruction-resolver.ts
packages/router/src/nav-route.ts
packages/router/src/nav.ts
packages/router/src/resources/nav.ts
packages/router/src/resources/viewport.ts
packages/router/src/router.ts
packages/router/src/scope.ts
packages/router/src/viewport-content.ts
packages/router/src/viewport-instruction.ts
packages/router/src/viewport.ts
packages/router/test/e2e/doc-example/src/components/authors/author.ts
packages/router/test/e2e/doc-example/src/components/books/redirect-about.ts
packages/router/test/e2e/scope/index.ejs
packages/router/test/unit/instruction-resolver.spec.ts

This PR contains the third part of the refactor towards viewport instruction and instruction resolver. It primarily removes the string parsing and handling from scope and replaces it with instruction resolver calls. It's one step closer having the router only deal with viewport instructions internally.
Ignore everything in packages/router/test/e2e/** since they are just my own test applications while working.
- Re-visit scoped viewports

Dynamic routing: refactor viewport instruction, part 3

---

packages/router/src/instruction-resolver.ts
packages/router/test/e2e/doc-example/src/components/authors/author.ts
packages/router/test/e2e/doc-example/src/components/authors/authors.ts
packages/router/test/e2e/doc-example/src/components/books/book.ts
packages/router/test/e2e/doc-example/src/components/books/books.ts
packages/router/test/e2e/doc-example/src/components/chat/chat-users.ts
packages/router/test/e2e/layouts/src/components/contacts.ts
packages/router/test/e2e/nav/src/app.ts
packages/router/test/e2e/nav/src/components/contacts.ts
packages/router/test/unit/instruction-resolver.spec.ts
packages/router/test/unit/router.spec.ts

This PR replaces the equals separator before parameters with a parantheses around the parameters for the default url syntax. The link
```html
<a href="book(3)">Night Watch</a>
```
results in the url (using hash)
`www.something.com/#/book(3)`
which navigates to the component `book` and pass the parameter `3` to `canEnter`/`enter`. Other examples:
```html
<a href="todos">All todos</a>
<a href="todos(active)">Todos left to, well, to do</a>
```
This PR doesn't do anything about parameter format with named parameters and/or more than one parameter (`parameter=value&parameter=value`). That will come in a later PR.
Ignore everything in …

Dynamic routing: use parantheses around parameters in url syntax

---

packages/jit-html/src/attribute-pattern.ts
packages/jit-html/src/binding-command.ts
packages/jit-html/src/configuration.ts
packages/jit-html/src/index.ts
packages/jit-html/src/template-binder.ts
packages/jit-html/test/integration/binding-command.class.spec.ts
packages/jit-html/test/integration/binding-command.style.spec.ts
packages/jit-html/test/integration/util.ts
packages/runtime-html/src/binding/attribute.ts
packages/runtime-html/src/binding/listener.ts
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/create-element.ts
packages/runtime-html/src/definitions.ts
packages/runtime-html/src/dom.ts
packages/runtime-html/src/html-renderer.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/instructions.ts
packages/runtime-html/src/observation/element-attribute-observer.ts
scripts/test-lib.ts

This PR is extracted from #364 to make the process easier. It adds support for class/style binding with the following syntax:
```html
<div class.my-class="shouldHaveMyClass">
<div my-class.class="shouldHaveMyClass">
<div style.background="bgValue">
<div background.style="bgValue">
<div -webkit-user-select.style="bgValue">
<div style.-webkit-user-select="bgValue">
<div --my-custom.style="value">
<div style.--my-custom="value">
```
Class will be toggle based on truthy/falsy evaluation, while style will be set as is.
N/A
Ignore the `AttrAttributePattern` and `AttrBindingCommand`. They are there for future work related to following template:
```html
<div my-attr.attr="myAttr">
<div attr.my-attr="myAttr">
<a-web-component disabled.attr="disabled">
<a-web-component attr.disabled="disabled">
``` …

feat(attr-binding): add class/style binding

---

.circleci/config.yml

This PR integrates the cypress tests added by @rowellx68  in his pr https://github.com/aurelia/aurelia/pull/461 so that they run on CIrcleCI automatically on each push/commit, as well as during the nightly and before releases. Thanks again @rowellx68  !
Follow up to https://github.com/aurelia/aurelia/pull/461
Nothing spectacular, just roughly copy-pasted the browserstack configuration and adjusted some paths.
Verified job outcome @ https://circleci.com/gh/aurelia/aurelia/16814
Perhaps a little bit of cleanup in the circleci config as well as moving some stuff around

ci: run cypress tests on circleci

---

renovate.json

With #454 we've introduced `renovate` to keep our dependencies up to date, but it's not working as intended. `renovate` is creating branches (and keeping those up to date) put not creating corresponding PR's. This PR should fix that.
Follow up tweak to #454.
Every Monday morning `renovate` is supposed to look at packages needing updates as per our scheduled configuration and if any need an upgrade, create a PR for that.
We also configured `:prNotPending`, which according to the [docs](https://renovatebot.com/docs/presets-default/#prnotpending) should: `Wait until branch tests have passed or failed before creating the PR`. But for some reason the branch tests are always in a `pending` state.
So the fix is to remove that setting and have it create the PR's immediately (based on the set …

Tweak Renovate Configuration

---

examples/jit-pixi-webpack-ts/package.json
package-lock.json
package.json
packages/aot/package.json
packages/debug/package.json
packages/examples/dbmonster-a/package.json
packages/examples/e2e-benchmark/vcurrent/package.json
packages/examples/e2e-benchmark/vnext/package.json
packages/fetch-client/package.json
packages/jit-html-browser/package.json
packages/jit-html-jsdom/package.json
packages/jit-html/package.json
packages/jit-pixi/package.json
packages/jit/package.json
packages/kernel/package.json
packages/plugin-parcel/package.json
packages/plugin-requirejs/package.json
packages/plugin-svg/package.json
packages/plugin-webpack/package.json
packages/router/package.json
packages/runtime-html-browser/package.json
packages/runtime-html-jsdom/package.json
packages/runtime-html/package.json
packages/runtime-pixi/package.json
packages/runtime/package.json
packages/store/package.json
packages/testing/package.json
packages/validation/package.json
renovate.json
test/browserstack/package.json

Pin typescript and fix some `renovate` warnings.
* https://github.com/Microsoft/TypeScript/issues/30662
* #471 
Due to Typescript introducing breaking changes in version `3.4.0`, for which there is no clean workaround, we need to stick to `~3.3.4000` for the foreseeable future.
Another (minor) change is that I moved some `devDependencies` to `dependencies` in the root `package.json`, as they're specified as `dependencies` in the individual packages, which was causing those versions to go out of sync as we have different upgrade policies for `devDependencies` and `dependencies`.
Once this is merged #471 should auto-update after the next run of the `renovate` job.
CircleCI
Hope the `typescript` folks fix this one way or another.

chore: pin typescript and harmonize renovate deps

---

examples/jit-aurelia-cli-ts/package.json
examples/jit-browserify-ts/package.json
examples/jit-fuse-box-ts/package.json
examples/jit-parcel-ts/package.json
examples/jit-pixi-webpack-ts/package.json
examples/jit-webpack-ts/package.json
packages/router/test/e2e/doc-example/app/package.json
packages/router/test/e2e/doc-example/package.json
packages/router/test/e2e/layouts/package.json
packages/router/test/e2e/modules/package.json
packages/router/test/e2e/nav/package.json
packages/router/test/e2e/scope/package.json
packages/router/test/e2e/siblings/package.json
packages/router/test/e2e/wizard/package.json
test/cypress/app/package.json
test/kitchen-sink/package.json

More `typescript` pinning in the hope it fixes e2e on CircleCI. And it appears it does...
Follow up to #472.
Also pins `typescript` to `~3.3.4000` where it ws previously set to `latest`.
CircleCI
n/a

chore: more typescript pinning

---

packages/kernel/src/di.ts
packages/kernel/src/interfaces.ts
packages/runtime/src/renderer.ts

The `unknown` default of `InterfaceSymbol`, `Constructable` etc are making DI completely unusable in end user projects with the TypeScript `strict` mode enabled, so I'm reverting them back to `any`. The way TypeScript handles decorators simply doesn't allow anything else, unfortunately.
I'm pushing this in between the other things because it's an easy (yet fairly critical) fix.
Exclusively contains a few `unknown` -> `any` type changes and a couple of tslint suppressions accompanied with that. Changes should speak for themselves
No new tests should fail
Merge to #464 and continue from there with the rest
<a id="e3dedcd0-5ccf-11e9-bc99-bbe5d5810388" href="none" codereview-uuid-reserved-tag />

fix(di): make the decorators compatible with ts strict mode for end users

---

packages/router/src/history-browser.ts
packages/router/src/router.ts
packages/router/src/viewport-content.ts
packages/router/src/viewport.ts
packages/router/test/e2e/doc-example/app/src/components/authors/about-authors.ts
packages/router/test/e2e/doc-example/app/src/components/authors/author.ts
packages/router/test/e2e/doc-example/cypress/integration/books-route.spec.ts
packages/router/test/e2e/doc-example/cypress/integration/default-route.spec.ts
packages/router/test/mock/browser-history-location.mock.ts
packages/router/test/unit/router.spec.ts

This PR adds the possibility for a component to specify a `reentryBehavior` property that controls whether it's possible to reenter the same component (even with identical parameters). Allowed values are:
- `disallow` - don't allow reentries into component at all (no navigation)
- `refresh` - create a new instance of the component (like a browser _refresh_) which replace the existing
- `enter` - reuse the existing component and call the navigation methods 
- `default` - use default behavior (`enter` if parameters are different, otherwise `disallow`)
Ignore everything in packages/router/test/e2e/** since they are just my own test …

Dynamic routing: component reentry behavior

---

packages/__tests__/router/router.spec.ts

It seems two colons are missing in one of the test, making these tests always pass no matter what.
Probably, this should be fixed by changing assertions to checking what values are, not that they no longer have some value.
see also [https://github.com/aurelia/aurelia/pull/489](url)

Fixed typos in router.spec.ts

---

packages/__tests__/router/e2e/doc-example/app/package.json
packages/__tests__/router/router.spec.ts
packages/router/src/router.ts
packages/router/src/utils.ts

This PR fixes an issue with clearing all viewports as well as slightly restructures handling of viewport defaults.
- Re-visit scoped viewports

Dynamic routing: fix clear all viewports

---

packages/__tests__/jit-html/replaceable.spec.ts
packages/runtime/src/renderer.ts

Fixes a scope bug in replaceable where if there are template controllers between the `replace-part` and the binding that needs to access the parent scope, the scope would actually not be reachable.
This is because `parts` were not passed through from outside the immediate parent when rendering a template controller, but rather only the parts from the immediate parent.
A small enough change that the code can speak for itself.
One test added to verify the particular scenario I ran into. 
Added a note that this needs to be verified in more combinations of similar nature that I don't have time to write right now.
This might actually also fix one or more of the cases @bigopon wrote and had commented out. Could you double check?

fix(replaceable): retain parts through template controllers in the replace-part

---

packages/__tests__/jit-html/replaceable.spec.ts
packages/__tests__/runtime/ast.spec.ts
packages/runtime-html/src/binding/attribute.ts
packages/runtime-html/src/binding/listener.ts
packages/runtime-html/src/resources/custom-elements/compose.ts
packages/runtime/src/ast.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/binding.ts
packages/runtime/src/binding/call.ts
packages/runtime/src/binding/interpolation-binding.ts
packages/runtime/src/binding/let-binding.ts
packages/runtime/src/binding/ref.ts
packages/runtime/src/lifecycle.ts
packages/runtime/src/observation/binding-context.ts
packages/runtime/src/observation/property-accessor.ts
packages/runtime/src/resources/custom-attributes/if.ts
packages/runtime/src/resources/custom-attributes/repeat.ts
packages/runtime/src/resources/custom-attributes/replaceable.ts
packages/runtime/src/resources/custom-attributes/with.ts
packages/runtime/src/templating/controller.ts

A more involved fix that addresses a deeper underlying issue with the "quick-n-dirty" part propagation logic I wrote earlier: the scope from the target `replace-part` was only bindable when every binding inside the `replace-part` was bound at the same time as the wrapping `replaceable`.
Now, by propagating the selected part name through the binding and AST (in a similar manner to how the flags flow through it), it will also work in a large number of edge cases that weren't accounted for earlier.
Most notably, when the content of a `replace-part` is wrapped inside an `if` which starts as `false`, when that `if` turns to `true` the scope of the inner binding would not have proper access to the part scope. This case (and probably many others, still need more tests) is now working.
A number …

fix(replaceable): make part scopes also work when not immediately bound from the wrapping replaceable

---

packages/__tests__/jit-html/template-compiler.spec.ts
packages/__tests__/runtime/controller.spec.ts
packages/jit-html/src/template-compiler.ts
packages/kernel/src/functions.ts
packages/kernel/src/index.ts
packages/runtime-html/src/resources/custom-elements/compose.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/definitions.ts
packages/runtime/src/lifecycle.ts
packages/runtime/src/observation.ts
packages/runtime/src/observation/binding-context.ts
packages/runtime/src/renderer.ts
packages/runtime/src/rendering-engine.ts
packages/runtime/src/resources/custom-attributes/with.ts
packages/runtime/src/templating/controller.ts

A refactor to clean things up a bit, use less resources, and offload some work to the template compiler so the controllers and resources have less tracking and tracing to do.
Important design change is that it adds an extra property to `ITemplateDefinition`: `scopeParts`. If anyone can think of a better (but not too long) name I'm all ears. The property is an array of the part names that need access to the scope of the resource on which that property sits.
Likely some improvements are still needed, but I need to sleep some nights on a more general internal refactor for smoother information exchange between different moving parts.
Mostly more code deleted than added. Added one `mergeDistinct` helper function to the kernel to efficiently merge and deduplicate two primitive arrays. I put it …

fix(replaceable): fix some more edge cases with multi nested elements and template controllers

---

packages/runtime/src/definitions.ts

A small change to make the `customElement` decorator a bit more typescript friendly. Change the constraint from `IRegistry` to `Key`, which more or less allows you to specify anything in there.
While not as "safe" from a typing perspective, this pretty much can't be accomplished anyway because we also allow string dependencies.

chore(di): use key type for dependencies array

---

packages/__tests__/jit-html/template-compiler.spec.ts
packages/jit-html/src/template-binder.ts
packages/jit/src/resource-model.ts

- Fixes attribute name registrations (they were erroneously being camelCased before, so that `attribute-name` would be mapped to `attributeName` - now it's back to normal again)
- Adds a new binding shorthand. If you leave the attribute value empty in a binding command (`.bind`, `.one-time`, `.to-view`, `.from-view`, `.two-way` and the `.bind` shorthand `:`) then it will default to the camelCased attribute name.
So, these:
```html
<my-element value.bind></my-element>
<my-element :value></my-element>
<my-element some-value.bind></my-element>
<my-element :some-value></my-element>
<input value.two-way>
```
Are equivalent to these:
```html
<my-element value.bind="value"></my-element>
<my-element :value="value"></my-element>
<my-element some-value.bind="someValue"></my-element>
<my-element …
```

Misc fixes

---

examples/jit-pixi-webpack-ts/package.json
package-lock.json
package.json
packages/plugin-pixi/package.json
renovate.json

Fixate `pixi.js` on `~4.8.8` for now, as `^5` contains breaking changes which will need some more effort to resolve.
This should unblock #505.
Updated to and fixated on the latest `pixi.js@^4`
Trust CircleCI.
See if this bring #505 in a mergeable state.

chore: fixate pixi.js for now

---

package.json

I noticed that during `npm init` and/or `npm refresh` it's calling `lerna bootstrap` twice.
n/a
After running `npm ci` it automatically triggers the `postinstall` script, which does a `lerna bootstrap --ci`, so there is no need to call it again ourselves.
Running `npm init` and/or `npm refresh` no longer shows the `lerna bootstrap` output twice.
n/a

chore: remove duplicate lerna bootstrapping

---

.circleci/config.yml
examples/jit-browserify-ts/package.json
scripts/change-package-refs.ts

`examples/jit-browserify-ts` fails with message:
```
/Users/huocp/aurelia/aurelia/examples/jit-browserify-ts/node_modules/@aurelia/jit-html-browser/dist/esnext/index.js:1
import { DefaultBindingLanguage as JitDefaultBindingLanguage, DefaultBindingSyntax as JitDefaultBindingSyntax, DefaultComponents as JitDefaultComponents } from '@aurelia/jit';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```
This error is due to browserify uses `'browser': 'dist/esnext/index.js'` in package.json, but browserify doesn't understand ES module format.
This does not affect other bundlers, they use "module" field over "browser" field.
This fix was manually tested on `examples/jit-browserify-ts` .

fix(all): properly support browserify, use umd build in "browser" field of package.json

---

packages/__tests__/router/e2e/navigation-skeleton/app/package.json
packages/examples/e2e-benchmark/package-lock.json
packages/examples/e2e-benchmark/package.json
packages/examples/e2e-benchmark/vcurrent/package.json
packages/examples/e2e-benchmark/vnext/package.json
renovate.json

Some `package.json` tweaks:
- Fixate `bootstrap`, as migrating to `^4` requires usage changes.
- Unpin `chromedriver`. The new CircleCI setup should support newer versions again.
n/a
With the *recent* CircleCI build changes we should now be on a version of the images that support newer versions of Chrome, making the pinning no longer needed.
And migrating from Bootstrap V3 to V4 requires manual changes to the used HTML, so I've pinned it for now until (and if) we decide to put in the effort to switch to V4.
CircleCI
n/a

chore: tweak package.json files

---

packages/router/src/resources/viewport.ts

This PR just hides the viewport header element (but keeps it around for now to make my life easier).
Ignore everything in `packages/router/test/e2e/**` since they are just my own test applications while working. In fact, the interim nature of this PR means there's probably not that much to actually review.

Dynamic routing: Hide viewport header

---

packages/__tests__/router/e2e/doc-example/app/index.ejs
packages/__tests__/router/e2e/doc-example/app/src/app.ts
packages/__tests__/router/e2e/doc-example/app/src/components/authors/author.ts
packages/__tests__/router/e2e/doc-example/app/src/components/books/book.ts
packages/__tests__/router/e2e/doc-example/app/src/components/login-special.ts
packages/__tests__/router/e2e/doc-example/app/src/components/login.ts
packages/__tests__/router/e2e/doc-example/app/src/components/main.ts
packages/__tests__/router/e2e/doc-example/app/src/startup.ts
packages/__tests__/router/e2e/doc-example/app/src/state.ts
packages/__tests__/router/e2e/doc-example/cypress.json
packages/__tests__/router/e2e/doc-example/cypress/integration/books-route.spec.ts
packages/__tests__/router/e2e/doc-example/cypress/integration/selectors.po.ts
packages/__tests__/router/e2e/doc-example/tsconfig.json
packages/__tests__/router/instruction-resolver.spec.ts
packages/__tests__/router/router.spec.ts
packages/router/src/guard.ts
packages/router/src/guardian.ts
packages/router/src/index.ts
packages/router/src/instruction-resolver.ts
packages/router/src/router.ts
packages/router/src/viewport-content.ts
packages/router/src/viewport-instruction.ts
packages/router/src/viewport.ts
packages/router/test/e2e/doc-example/app/src/components/login-special.ts
packages/router/test/e2e/doc-example/app/src/components/login.ts
packages/router/test/e2e/doc-example/app/src/components/main.ts

This PR contains the first version of router guards before navigation (such as an auth guard). It works, but could use a nicer API regarding "state to continue back to". Basic usage example:
```typescript
this.router.guardian.addGuard((instructions) => {
if (this.verifyLogin()) {
return true;
}
this.state.loginReturnTo = this.router.instructionResolver.mergeViewportInstructions([
...this.state.loginReturnTo,
...this.router.activeComponents,
...instructions
]);
alert("You've timed out!");
this.state.loggedIn = false;
this.router.goto('login');
return false;
}, { exclude: ['', 'login'] });
```
**Note** that this PR contains a **breaking change** in that component arguments move from after the viewport to after the component in hrefs/urls.
```
book@detail-viewport(id=123) -> …
```

Dynamic routing: router guards

---

packages/runtime/src/renderer.ts

-This allows a a bindable to be set to true when nothing is passed in to the attribute.  This greatly reduces the boilerplate for times when you want to set a static true value. *see below
```html
<element disabled outlined ></element>
```
```typescript
class Element{
@bindable public disabled: boolean = false; //THIS WILL BE TRUE
@bindable public outlined: boolean = false; //THIS WILL BE TRUE
}
```

Allow default value for attributes that are bound with no explicit value being set

---

packages/kernel/src/index.ts
packages/router/src/configuration.ts
packages/runtime/src/activator.ts
packages/runtime/src/aurelia.ts
packages/runtime/src/configuration.ts
packages/runtime/src/index.ts
packages/runtime/src/lifecycle-task.ts
packages/testing/src/assert.ts

This is a somewhat quick-n-dirty startup task implementation, mostly to get some API feedback and get the ball rolling. I hope others can help me refine/improve/test this.
The idea is that you create a task from a fluent API and register the created object with DI. The activator then resolves all tasks and executes them at the right times during initial startup.
There are 4 "slots": `beforeCreate`, `beforeRender`, `beforeBind` and `beforeAttach`.
- `beforeCreate` will run "before app()" in a sense, that is, it will run before the root App is instantiated from DI. This is where you can, for example, manipulate container registrations while all static registrations are already available.
-`beforeRender` runs before the app root is rendered / controller created. So you could for example …

feat(runtime): initial implementation for startup tasks

---

packages/__tests__/runtime-html/children-observer.spec.ts
packages/__tests__/runtime/controller.spec.ts
packages/runtime-html/src/projectors.ts
packages/runtime-html/src/resources/custom-elements/compose.ts
packages/runtime/src/definitions.ts
packages/runtime/src/index.ts
packages/runtime/src/rendering-engine.ts
packages/runtime/src/resources/custom-element.ts
packages/runtime/src/templating/children.ts
packages/runtime/src/templating/controller.ts

The ShadowDOMProjector was observing and providing it’s shadow children instead of content children. This PR fixes that. It also introduces filter and select functions to the ChildrenObserver, so that consumers can decide just which children they want and whether they want the element, controller, or viewModel (or whatever else).
There’s still no `@children` decorator or runtime capability to set this up. That still needs to be done. I’d like to be able to have some simple defaults like `@children(TabItem)` or `@children(HTMLElement)` or even `@children(TabItem, ‘.some-selector’)` to get all child view models of a type, or all elements, or all child view models of a type where the element matches a selector, for example. Here’s something that’s typical:
```TypeScript
export class …
```

Child Observation

---

.vscode/settings.json
packages/__tests__/jit-html/focus.spec.ts
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/resources/custom-attributes/focus.ts
packages/runtime-html/src/resources/custom-attributes/utils.ts

Add focus attribute, as one of core attributes in vCurrent
N/A
N/A
Need to re-enable multiple binding scenarios once the support is back:
```html
Working:
<input focus.two-way="hasFocus">
Not working:
<input focus="value.two-way: hasFocus">
```
Add more tests

feat(focus): add focus attribute

---

packages/__tests__/router/e2e/doc-example/app/src/components/main.ts
packages/__tests__/router/instruction-resolver.spec.ts
packages/__tests__/router/router.spec.ts
packages/router/src/instruction-resolver.ts
packages/router/src/resources/viewport.ts
packages/router/src/router.ts
packages/router/src/viewport-instruction.ts
test/realworld/src/app.ts
test/realworld/src/components/article/article-meta.html
test/realworld/src/components/article/comment.html
test/realworld/src/components/auth/auth.html
test/realworld/src/components/profile/profile.html
test/realworld/src/components/profile/profile.ts
test/realworld/src/resources/elements/article-preview.html
test/realworld/src/shared/layouts/header-layout.html

This PR makes viewports scoped by default. This means that viewports by default will create a new scope/hierarchical segment. The difference being
Unscoped viewports, current default
```html
<host>
<a href="products">Product list, relative</a> 
<a href="/products">Product list, absolute</a> 
<a href="product(123)">Show product 123, relative</a> 
<a href="/product(456)">Show product 456, absolute</a> 
<au-viewport name="master" used-by="products"></au-viewport>
<a href="products">Product list, relative</a> 
<a href="/products">Product list, absolute</a> 
<a href="product(123)">Show product 123, relative</a> 
<a href="/product(456)">Show product 456, absolute</a> 
<au-viewport name="detail" used-by="product">
<a href="products">Product list, relative</a> 
<a href="/products">Product list, …
```

Dynamic routing: default to scoped viewports

---

packages/__tests__/kernel/di.integration.spec.ts
packages/__tests__/runtime-html/styles.spec.ts
packages/__tests__/setup-browser-router.ts
packages/__tests__/setup-browser.ts
packages/__tests__/setup-node.ts
packages/kernel/src/di.ts
packages/runtime-html-browser/src/index.ts
packages/runtime-html-jsdom/src/index.ts
packages/runtime-html/src/dom.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/projectors.ts
packages/runtime-html/src/styles/css-modules-registry.ts
packages/runtime-html/src/styles/shadow-dom-registry.ts
packages/runtime-html/src/styles/shadow-dom-styles.ts
packages/runtime-html/src/styles/style-configuration.ts
packages/testing/src/html-test-context.ts

This PR implements the necessary infrastructure to support both CSS Modules Preprocessing and Shadow DOM CSS styles in the HTML runtime. The Shadow DOM styles implementation supports using adoptedStyleSheets if present, and falling back to style elements if not. When using adoptedStyleSheets, it can handle both strings and CSSStyleSheet instances, providing support for the upcoming CSS Modules spec as well.
* #524 
The basic idea is that "styles" are a dependency of the template. So, the infrastructure is based around plugging in different ways to handle CSS, based on application preference. Depending on configuration, when styles are added to a component dependency list, a different registry will be used to register the correct set of services within the component's render context. For …

Runtime Support for Styles

---

packages/__tests__/jit-html/blur.integration.spec.ts
packages/__tests__/jit-html/blur.unit.spec.ts
packages/__tests__/jit-html/focus.spec.ts
packages/__tests__/karma.conf.js
packages/runtime-html/src/resources/custom-attributes/blur.ts
packages/runtime/src/lifecycle.ts

Wheel event requires special handling, it's hard to generalize it inside blur attribute. Also, using enqueueRAF with once: true will help avoid doing redundant dequeue.
N/A
N/A
N/A
N/A

Blur attribute

---

renovate.json
test/js-framework-benchmark/webdriver-ts-results/src/App.tsx
test/js-framework-benchmark/webdriver-ts/package.json

This should (partially) get Renovate back in line.
* #551 
This PR fixes two separate issues related to dependency updates:
* There is a newer version of `chromedriver`. The problem is that that package is directly tied to the version of Chrome installed on the machine. In this case the version of Chrome installed on the Docker image used on CircleCI. My solution is to pin `chromedriver` to the currently used version `^74.0.0` across the board. Note that this is a temporary solution, because when CircleCI decides to update its version of Chrome stuff will start breaking again. This would happen with or without `renovate` though...
* `test/js-framework-benchmark/webdriver-ts-results` is using version `3.3.3333` of `typescript`. Once you upgrade it to the current `3.5.3` (that the rest of …

chore: partially fix renovate

---

packages/__tests__/jit-html/replaceable.spec.ts
packages/jit-html/src/template-binder.ts

This allows projection of elements without defining default replacements when a containerless element is being used.
See below for usage examples.
```ts
@customElement({
name: 'cool-button', containerless: true, template: `
<button>
<template replaceable />
</button
`})
export class CoolButton {
message = 'I am inside the coolest button on earth!';
}
```
```html
<template>
<cool-button> I am still pretty cool since I live in some unknown realm
owned by the coolest button on earth </cool-button>
<cool-button>${message} </cool-button>
<cool-button> <template>${message} </template> </cool-button>
</template>
```
```ts
export class App{
message= 'I am the parent of the coolest button on earth!';
}
```
N/A
Tests writen.
E2E tests.

feat(default-replaceable): allow replace conv

---

packages/router/src/guard.ts
packages/router/src/guardian.ts
packages/router/src/index.ts
packages/router/src/instruction-resolver.ts
packages/router/src/interfaces.ts
packages/router/src/nav-route.ts
packages/router/src/nav.ts
packages/router/src/navigator.ts
packages/router/src/resources/viewport.ts
packages/router/src/router.ts
packages/router/src/scope.ts
packages/router/src/type-resolvers.ts
packages/router/src/viewport-content.ts
packages/router/src/viewport-instruction.ts
packages/router/src/viewport.ts
test/realworld/package-lock.json
test/realworld/src/app.ts
test/realworld/src/main.ts

This PR refactors and restructures interfaces and types, including renaming `IRouteableCustomElement*` to `IRouteableComponent*` and using them where appropriate. It also fixes a small bug in `au-nav`s active route.
Ignore everything in `packages/router/test/e2e/**` since they are just my own test applications while working. 
- …

refactor(router): refactor interfaces and types

---

packages/__tests__/router/route-recognizer.spec.ts
packages/__tests__/router/viewport-content.spec.ts
packages/router/src/browser-navigator.ts
packages/router/src/guard.ts
packages/router/src/guardian.ts
packages/router/src/instruction-resolver.ts
packages/router/src/interfaces.ts
packages/router/src/link-handler.ts
packages/router/src/nav-route.ts
packages/router/src/nav.ts
packages/router/src/navigator.ts
packages/router/src/parser.ts
packages/router/src/queue.ts
packages/router/src/resources/nav.ts
packages/router/src/resources/viewport.ts
packages/router/src/route-recognizer.ts
packages/router/src/router.ts
packages/router/src/scope.ts
packages/router/src/type-resolvers.ts
packages/router/src/utils.ts
packages/router/src/viewport-content.ts
packages/router/src/viewport-instruction.ts
packages/router/src/viewport.ts
packages/router/tsconfig.json

This PR enables TypeScript strict mode! 
I tried doing as little actual changes/refactoring as possible, but a fair amount of changes were unavoidable. Future PRs will do some additional refactoring of types and interfaces.
I've disabled the tests for route recognizer that failed. I don't know the route recognizer well enough and it's currently not used.
- …

refactor(router): enable typescript strict mode

---

packages/__tests__/router/browser-navigator.spec.ts
packages/router/src/browser-navigator.ts
packages/router/src/navigator.ts
packages/router/src/router.ts
packages/testing/src/mocks.ts
test/realworld/package-lock.json
test/realworld/src/app.html
test/realworld/src/main.ts
test/realworld/src/resources/value-converters/date.ts

This PR makes it possible to configure the router to not use url fragment hash (to "use push state").
```typescript
au.register(
RouterConfiguration.customize({ useUrlFragmentHash: false }),
)
```
Note that the web server need to be configured to handle "redirects to the right application page" for deep links and other browser url manipulations to work. 
- Added two new tests that tests the configuration difference.
- Add tests for the new …

feat(router): configure to not use url fragment hash

---

packages/__tests__/router/configuration.spec.ts
packages/router/src/browser-navigator.ts
packages/router/src/navigator.ts
packages/router/src/router.ts

This PR makes the router's `loadUrl` method `await`able by returning a promise that's resolved when the url is loaded.

refactor(router): make load url awaitable

---

packages/__tests__/plugin-conventions/preprocess-html-template.spec.ts
packages/__tests__/plugin-conventions/preprocess-resource.spec.ts
packages/__tests__/plugin-conventions/preprocess.spec.ts
packages/plugin-conventions/src/options.ts
packages/plugin-conventions/src/preprocess-resource.ts
packages/plugin-conventions/src/preprocess.ts

1. Implement conventional `@view` decorator for #584.
2. Fixed a compatibility issue on existing decorators. The injected decorator is now before existing decorators.
3. Improve compatibility with uppercase resource name
- Convention now support ua-foo.js to match resource class name UAFoo.

Conventional view locator

---

packages/__tests__/plugin-conventions/preprocess-html-template.spec.ts
packages/__tests__/plugin-conventions/preprocess.spec.ts
packages/plugin-conventions/src/preprocess-html-template.ts
packages/plugin-gulp/README.md
packages/webpack-loader/README.md
test/realworld/src/html.d.ts

As Rob suggested, simplified HTML only element by implementing `register(container)` method in html module.
Passed manually tested in app.
Need to update makes skeleton after this release.

refactor(plugin-conventions): simplify usage of html only element

---

packages/__tests__/jit-html/template-compiler.ref.spec.ts

Don't use `Array.prototype.flatMap`
N/A
N/A
N/A
N/A

fix(tests): use map/reduce instead of flatmap

---

packages/__tests__/router/e2e/nav/src/tracing.ts
packages/debug/src/configuration.ts
packages/debug/src/index.ts
packages/debug/src/tracer.ts
packages/testing/src/tracing.ts

This is part of #630, to avoid naming conflict with kernel Tracer.
BREAKING CHANGE: debug Tracer is renamed to DebugTracer

refactor(debug): rename Tracer to DebugTracer

---

.codeclimate.yml

Tweak the `.codeclimate.yml` settings a bit, so they more closely mirror out `eslint` setup, to see if it reduces the PR build warning noise a bit.
n/a
- Check if CodeClimate has less to complain about. 
n/a
n/a

chore: tweak codeclimate settings

---

docs/engineering-notes/specs.md
docs/user-docs/app-basics/app-configuration-and-startup.md
docs/user-docs/app-basics/dependency-injection.md
docs/user-docs/app-basics/internationalization.md
docs/user-docs/examples/custom-attributes/binding-to-element-size.md
docs/user-docs/getting-started/components.md
packages/aurelia/README.md
packages/aurelia/src/index.ts

Also added two re-exports `ISignaler` and `HTMLDOM` in "aurelia" package because i18n sample code uses them.

docs: update doc to use latest "aurelia" package

---

packages/kernel/src/di.ts

Fixes a type inference issue in the `Resolved<K>` and `IServiceLocator` types that caused `container.get(key)` to return `any` for certain `InterfaceSymbol`s with the latest typescript update.
N/A
N/A
No functional changes to test. Build must succeed.
N/A

fix type inference issue with Resolved<K>

---

packages/__tests__/jit-html/custom-elements.spec.ts
packages/__tests__/jit-html/template-compiler.spec.ts
packages/__tests__/runtime/let-binding.spec.ts
packages/jit-html/src/template-binder.ts
packages/jit-html/src/template-compiler.ts
packages/jit/src/semantic-model.ts
packages/runtime/src/binding/let-binding.ts
packages/runtime/src/definitions.ts
packages/runtime/src/instructions.ts
packages/runtime/src/renderer.ts
packages/testing/src/au-dom.ts

Let in v2 was developed at during the finalization of v1 let, so it carried some old naming. Change from `to-view-model` to `to-binding-context`
N/A
N/A
N/A
N/A

fix(let): to-view-model -> to-binding-context

---

packages/jit-html/src/semantic-model.ts
packages/jit-html/src/template-binder.ts
packages/jit-html/src/template-compiler.ts
packages/jit/src/index.ts
packages/jit/src/resource-model.ts
packages/jit/src/semantic-model.ts
packages/testing/src/tracing.ts

- Simplified the `TemplateBinder` by passing the `manifest`, `manifestRoot`, etc via method parameters rather than storing&restoring them as class instance properties. Data flow should be easier to understand now. Also added some comments.
- Removed the symbol interfaces from the semantic model, using type unions of the classes instead. Also introduced node generic type arguments to make the types more accurate and require a little bit less casting.
- Cleaned up the resource model classes.
- Fixed a number of linting issues along the way.
Fixes https://github.com/aurelia/aurelia/issues/677
The semantic-model in `jit-html` looks a bit hacky, but this structure is needed to provide html-specific defaults for the generic type arguments. We might opt to get rid of those generics entirely and …

refactor(jit-html): cleanup template-binder and improve semantic-model types

---

.codeclimate.yml

As discussed with @fkleuver on Discord, I feel the `codeclimate`  [Maintenance Checks](https://docs.codeclimate.com/docs/maintainability) no longer provide any benefit.
Most (if not all) of these checks are also done by our linting setup and `eslint` gives a higher degree of control (within the code itself) to enable/disable or tweak settings inline. Another issue is that we currently have to mark exclusion both on the `lint` and the `codeclimate` level, which is a bit of double work.
n/a
The effects of this PR should be self evident on this PR.
n/a
n/a

chore: disable codeclimate Mainenance Checks

---

packages/__tests__/router/e2e/doc-example/app/src/components/authors/authors.ts
packages/__tests__/router/link-handler.spec.ts
packages/__tests__/router/router.spec.ts
packages/router/src/configuration.ts
packages/router/src/index.ts
packages/router/src/link-handler.ts
packages/router/src/resources/goto.ts

This PR renames the `au-href` attribute to `goto`.
```html
<a goto="foo(bar)">foo with bar</a>
<a goto.bind="'foo(bar)'">foo with bar</a>
<a goto.bind="{ component: 'foo', parameters: 'bar' }">foo with bar</a>
<a goto.bind="{ component: Foo, parameters: 'bar' }">foo with bar</a>
```
The last example currently requires that the `Foo constructor` is known within the view model. For example
```typescript
import { Foo } from './foo';
export class MyComponent {
private readonly Foo = Foo;
}
```
- …

refactor(router): rename au-href to goto

---

packages/__tests__/plugin-conventions/name-convention.spec.ts
packages/__tests__/plugin-conventions/preprocess-resource.spec.ts
packages/plugin-conventions/src/name-convention.ts
packages/plugin-conventions/src/options.ts
packages/plugin-conventions/src/preprocess-resource.ts

1. Add support of `@templateController` in conventions.
* If you already decorated class with `@templateController`, conventions will skip the resource (even if there is `CustomAttribute` suffix in class name).
* If you name resource as `export class FooBarTemplateController` without decorator, conventions will inject `@templateController('foo-bar')`.
2. Add check on existing import statement on new "aurelia" package to avoid double import.
#657
#630 
Manually tested in a webpack app.
To be tested in user apps.

Support templateController in conventions.

---

scripts/logger.ts

Fix a typing issue causing `browserstack` to fail.
n/a
Check that the `e2e_browserstack` test stops failing on CircleCI.
CircleCI
n/a

test: fix browserstack error

---

packages/__tests__/.eslintrc.js
packages/__tests__/i18n/t/translation-integration.spec.ts
packages/__tests__/i18n/t/translation-render.spec.ts
packages/__tests__/jit-html/blur.integration.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.if-else.double.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.if-else.repeat.double.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.if-else.repeat.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.if-else.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.spec.ts
packages/__tests__/jit-html/template-compiler.harmony.spec.ts
packages/__tests__/jit-html/template-compiler.ref.spec.ts
packages/__tests__/jit-html/template-compiler.spec.ts
packages/__tests__/jit-html/template-element-factory.spec.ts
packages/__tests__/kernel/di.integration.spec.ts
packages/__tests__/kernel/di.spec.ts
packages/__tests__/runtime-html/attr-binding-behavior.spec.ts
packages/__tests__/runtime-html/checked-observer.spec.ts
packages/__tests__/runtime-html/dom.spec.ts
packages/__tests__/runtime-html/self-binding-behavior.spec.ts
packages/__tests__/runtime/array-observer.spec.ts
packages/__tests__/runtime/ast.spec.ts
packages/__tests__/runtime/binding-behavior.spec.ts
packages/__tests__/runtime/binding-mode-behaviors.spec.ts
packages/__tests__/runtime/binding.spec.ts
packages/__tests__/runtime/debounce-binding-behavior.spec.ts
packages/__tests__/runtime/dirty-checker.spec.ts
packages/__tests__/runtime/throttle-binding-behavior.spec.ts
packages/__tests__/runtime/value-converter.spec.ts
scripts/generate-tests/template-compiler.static.ts
scripts/generate-tests/util.ts

Enable the `no-hooks` linting rule and disable the violations for now. This ensures we get no new global hooks, while being able to easily find the remaining ones and slowly refactor those away.
I did already remove a couple of global `before` and `after ` hooks that didn't seem necessary (anymore).
n/a
A spot check on the changes made would be appreciated.
CircleCI
More linting

chore: switch to no-hooks

---

packages/__tests__/.eslintrc.js
packages/__tests__/jit-html/generated/template-compiler.mutations.basic.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.if-else.double.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.if-else.repeat.double.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.if-else.repeat.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.if-else.spec.ts
packages/__tests__/jit-html/generated/template-compiler.static.spec.ts
scripts/generate-tests/util.ts

Move the `eslint-disable` statements that are at the top of the generated tests (and are put there by the npm `generate-tests:template-compiler.*` scripts) to `.eslintrc.js`. This increases maintainability as the list keeps increasing and is now in a single location instead of in each file.
Also switched off `compat/compat` within tests as it doesn't make sense there.
n/a
Just moving some stuff around.
CircleCI
n/a

chore: move inline eslint disables to .eslintrc.js for generated tests

---

packages/__tests__/package.json

Set the `node` engine requirement to `>=12.0.0` in `__tests__/package.json` as the tests for `i18n` make use of `RelativeTimeFormat`, which is only available in [Node 12 and up](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat).
n/a
Self explanatory imho.
CircleCI
n/a

test: require node >= 12.0.0

---

docs/user-docs/app-basics/internationalization.md
packages/__e2e__/src/plugins/sut-i18n.ts
packages/i18n/src/df/date-format-value-converter.ts
packages/i18n/src/i18n.ts
packages/i18n/src/nf/number-format-value-converter.ts
packages/i18n/src/rt/relative-time-value-converter.ts
packages/i18n/src/t/translation-binding.ts
packages/i18n/src/t/translation-value-converter.ts

Exported `I18N` interface so that devs don't have to explicitly refer to `I18NService`.

fix(i18n): type definition

---

packages/__tests__/jit-html/portal.spec.tsx
packages/__tests__/jit-html/template-compiler.primary-bindable.spec.ts
packages/jit-html/src/template-binder.ts

At the moment, multi binding attributes usage does not camel-case-ize the target attribute-property, making the following not working:
```html
<div square="border-radius: 5"></div>
```
But the following work;
```html
<div square="borderRadius: 5"></div>
```
Fix that by always convert target attribute-property to camel case
N/A
Should there be a warning in case an upper case character is detected in attribute name?
N/A
N/A

Fix multi binding compilation

---

packages/__tests__/5-jit-html/custom-attributes.spec.ts
packages/__tests__/5-jit-html/custom-elements.spec.ts
packages/runtime-html/src/html-renderer.ts
packages/runtime/src/renderer.ts

Currently, `SetPropertyRenderer` simply does an assignment in the form of `object[prop] = value`. This causes change handler to fire prematurely. Simply set `currentValue` of the observer to avoid this
N/A
N/A
N/A
N/A

Fix ce ca compilation

---

docs/user-docs/getting-started/components.md

- The documentation says the user to create a new file called
`register`, but it imports it as `registry`.
It fix a simple typo in the documentation.
None
None
1. Generate the user documentation;
2. Go to the "Getting Started" > "Building Components";
3. Go to the "Component Registration" section;
4. Verify if the filename in the example is named "registry.ts".

docs(getting-started): Fix wrong filename in example.

---

packages/runtime/src/binding/property-binding.ts

Removed a spurious semicolon, which resulted in a Terser error when running `npm run-script build` with `npx makes`. See #735 for details.
Fixes #735 
I verified this removes the extra semicolon in `runtime/dist/esnext/binding/property-binding.js` after an `npm run build`
CircleCI
Figure out why the eslint `no-extra-semi` rule didn't notify us of this.

fix(runtime): remove stray semicolon triggering Terser error

---

packages/aurelia/src/quick-start.ts
packages/runtime/src/aurelia.ts

- `Aurelia.register` in the quick-start had the wrong parameter type (`IRegistry`). This is now changed to `unknown` so it accepts anything (we may want to constrain it a bit more before going alpha though)
- Modified the `.app` signature on both the static and instance methods of `Aurelia` to return a type that omits `app` and `register`, so that the type system will not allow users to perform those invalid operations. `register` has to come before `app` and there is now no other way to do it.
Fixes https://github.com/aurelia/aurelia/issues/736
This is the effect:

chore(aurelia): fix the startup api types

---

packages/kernel/src/functions.ts
packages/kernel/src/index.ts
packages/kernel/src/metadata.ts

- Fixes an issue where a certain decorator usage type in monaco would cause metadata to throw
- Improves general error messages
- Exposes new functions `isObject` and `isNullOrUndefined` (used by metadata in this PR) from the kernel, to use in the framework and/or by end users for convenience

Metadata fixes

---

.eslintrc.js
packages/__tests__/1-kernel/di.spec.ts
packages/__tests__/5-jit-html/binding-behaviors.spec.ts
packages/__tests__/5-jit-html/custom-attributes.spec.ts
packages/__tests__/5-jit-html/template-compiler.harmony.spec.ts
packages/__tests__/5-jit-html/template-compiler.primary-bindable.spec.ts
packages/__tests__/5-jit-html/template-compiler.ref.spec.ts
packages/__tests__/5-jit-html/value-converters.spec.ts
packages/i18n/src/t/translation-binding.ts
packages/kernel/src/di.ts
packages/kernel/src/functions.ts
packages/kernel/src/index.ts
packages/router/src/resources/goto.ts
packages/router/src/resources/viewport.ts
packages/runtime-html/src/binding/attribute.ts
packages/runtime-html/src/observation/attribute-ns-accessor.ts
packages/runtime-html/src/observation/class-attribute-accessor.ts
packages/runtime-html/src/observation/data-attribute-accessor.ts
packages/runtime-html/src/observation/style-attribute-accessor.ts
packages/runtime-html/src/resources/custom-attributes/blur.ts
packages/runtime-html/src/resources/custom-attributes/focus.ts
packages/runtime-html/src/styles/css-modules-registry.ts
packages/tsconfig-build.json

Previously we threw an error when the container gets `Object` as a key, but that turned out to have a few unintended side effect, such as not being able to do partial dependency resolution.
So, now we just report a warning instead, and we also do this on other natives (e.g. `Array`, `HTMLElement`, etc)
There is also a new exported helper function `isNativeFunction`, used by the container for the above, that will be useful in other parts of the framework and possibly also for end users.
Furthermore, there are a few issues with `emitDecoratorMetadata` in nodejs that I'm addressing now, because they're making things difficult in AOT.

Emit decorator metadata

---

renovate.json
test/wdio/package-lock.json
test/wdio/package.json

Update `fibers` in `test/wdio/package.json`. This is a partial fix for #756. 
- #756 
The `wdio` package depends on `fibers@^3` which fails to install on Node 12. I've managed to update the dependencies with a `package-lock.json` tweak, fooling npm into using `fibers@^4`.
So `npm ci` works and will install the currently newest versions. `npm install` will still fail though.
I also had to only partially upgrade and pin `chromedriver` to `77.0.0` as updating CircleCI to use `78.0.1` resulted in a single failing test in Chrome.
And lastly I merged the two `pixi` exclusions in `renovate.json` to a single one.
CircleCI
- Create a PR on the `wdio` package to have them update it to `fibers@^4`, to have a more permanent solution.
- Fix the underlying issue causing the test to fail on when …

chore: update fibers to 4.0.2

---

packages/runtime/src/observation.ts
packages/runtime/src/observation/array-observer.ts
packages/runtime/src/observation/map-observer.ts
packages/runtime/src/observation/set-observer.ts

Stores collection observers in module-scoped weakmaps instead of as a property on the collections themselves.
This should help the garbage collector out a bit and reduce the chances of accidental memory leaks

perf(collection-observation): store observers in weakmaps

---

.circleci/config.yml

`test/browserstack` is now a `lerna` managed package, so it doesn't need its own `npm i` anymore, as it uses the hoisted packages.
n/a
Self explanatory imho.
CircleCI
n/a

chore(browserstack): no unneeded npm i on circleci

---

package-lock.json
package.json

The `validate-commit-msg` package has been deprecated, so switch to `commitlint`.
n/a
Configuration should be identical, so it should be a drop in replacement.
Type is mandatory and must be from a predefined list.
Scope is optional and can be anything
Description is mandatory.
Per request I made the config explicit instead of using `@commitlint/config-conventional`.
CircleCI
I also tried to commit some local commits with invalid commit messages and they were rejected as before.
n/a

chore: migrate from validate-commit-msg to commitlint

---

packages/__tests__/2-runtime/property-observation.spec.ts
packages/__tests__/5-jit-html/custom-attributes.spec.ts
packages/__tests__/5-jit-html/custom-elements.spec.ts
packages/__tests__/5-jit-html/deep-bindables.spec.ts
packages/__tests__/tasks/copy-html.js
packages/aurelia/src/index.ts
packages/debug/src/tracer.ts
packages/runtime/src/index.ts
packages/runtime/src/observation/bindable-observer.ts
packages/runtime/src/observation/self-observer.ts
packages/runtime/src/templating/bindable.ts
packages/runtime/src/templating/controller.ts

Provide the ability to config bindable with getter/setter interceptors. Note that those config are purely interceptors, and expected to be pure functions. Usage example would be:
Defining a setter for altering incoming value:
```ts
export class MyEl {
@bindable({ set: Number })
public value: number
@bindable({ set: val => Number(val) || 0 })
public credit: number
}
```
Then in template, the scenarios like following will work as expected:
```html
<input type="number" value.bind="value">
<input type="number" value.bind="credit">
```
Or in code:
```ts
myEl.value = '5';
// myEl.value === 5
myEl.value = 'a';
// myEl.value === NaN
myEl.credit = '1';
// myEl.credit === 1;
myEl.credit = 'a';
// myEl.credit === NaN
```
Defining a getter:
```ts
export class MyEl {
@bindable({ get: val => …
```

Bindable observer

---

packages/__tests__/webpack-loader/loader.spec.ts
packages/webpack-loader/src/index.ts

For webpack, conditional loader (in webpack.config) is needed for shadow-dom css processing.
closes #776

fix(webpack-loader): canot use raw-loader on scss or less

---

packages/runtime/src/resources/custom-attributes/repeat.ts

Fixes a specific edge case where removing the only item of an array as the first array mutation for a repeater causes a ReferenceError due to module-scoped variable not yet being initialized. (the `if (len > maxLen)` logic that would initialize it, doesn't evaluate to true when the apparent initial length is 0)
Pending e2e test for this scenario: https://github.com/aurelia/aurelia/issues/781
Verified the fix locally. Needs e2e test to prevent future regression.

fix(repeat): initialize module-scoped index eagerly to fix reference error

---

packages/__tests__/1-kernel/di.spec.ts
packages/kernel/src/di.ts

When primitive values are passed into `register()` this may cause unpredictable results, such as `Metadata` throwing an error, even when the end user has no control over that (such as when passing in a synthetically created module object by a bundler).
This PR causes the DI container to simply ignore those invalid values. I chose to do this in the top-level registration loop (as opposed to only in the inner `Object.keys` loop) so as to also make the container a bit more forgiving when passing in an array of registrations where one or more values is invalid. Being the most front-facing surface api, it should probably be forgiving in these scenarios.
We may want to let the reporter log a warning in this case in the future for good measure.
Added tests for all primitive values shapes in the …

fix(container): ignore primitive values in register

---

packages/__tests__/2-runtime/ast.spec.ts
packages/__tests__/3-runtime-html/array-index-observer.spec.ts
packages/__tests__/5-jit-html/array-index-observer.spec.ts
packages/__tests__/5-jit-html/computed-observer.spec.ts
packages/aurelia/src/index.ts
packages/kernel/src/di.ts
packages/kernel/src/functions.ts
packages/kernel/src/index.ts
packages/runtime-html/src/observation/checked-observer.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/index.ts
packages/runtime/src/observation.ts
packages/runtime/src/observation/array-observer.ts
packages/runtime/src/observation/computed-observer.ts
packages/runtime/src/observation/map-observer.ts
packages/runtime/src/observation/observer-locator.ts
packages/runtime/src/observation/set-observer.ts
packages/testing/src/inspect.ts
packages/testing/src/util.ts

Add ability to observe array index
Supports the scenario described at https://github.com/aurelia/binding/issues/444
with slightly modified templating syntax
Instead of
```html
<ul>
<li repeat.for="item of items">${item}</li>
</ul>
<p repeat.for="item of items">
<input value.two-way="item"
</p>
```
It can work with:
```html
<ul>
<li repeat.for="item of items">${item}</li>
</ul>
<p repeat.for="item of items">
<input value.two-way="items[$index]"
</p>
```
N/A
N/A
N/A

Fix arr index observation

---

.eslintrc.js
.vscode/extensions.json

- `import/no-deprecated` turns out to be among the primary causes for eslint to be slow in our repository, so we're disabling it:
- `@typescript-eslint/indent` has recurring issues, in particular with parameter decorators (see https://github.com/typescript-eslint/typescript-eslint/issues/1232). There seems to be no indicator of anyone being invested in fixing that anytime soon. Since indentation is not much of a problem in our repo with all the autofixing available in-editor, I'm disabling this rule for now.
- Also adding back in `extensions.json` to make clearer to contributors which extensions they will probably want to install when working on the repo.

disable two counter-productive lint rules + update extensions.json

---

packages/__tests__/5-jit-html/custom-attributes.spec.ts
packages/jit-html/src/template-binder.ts
packages/jit/src/resource-model.ts
packages/runtime/src/resources/custom-attribute.ts

Add a new config for custom attribute to have ability to always parse their value as single binding. An example for this would be `goto` attribute:
```html
<a goto="http://outside.com"></a>
```
N/A
N/A
N/A
Plan to spec dynamic options properly to complete custom attribute features

feat(custom-attr): add no multi bindings cfg

---

packages/kernel/src/di.ts

Address a typing issue with the `ResolveCallback` type. This is an old (and common) mistake where the callback parameters were optional. The intent was to not force the user to specify them, but that is the default behavior in TypeScript anyway. The actual effect was that the parameters given to the user were "possibly undefined" even though DI guarantees to pass them in.
So the parameter types here are now correct:
```ts
DI.createInterface().withDefault(x => x.callback((handler, requestor, resolver) => { ... }));
// handler, requestor and resolver were possibly undefined. Now they are not, so they don't need to be explicitly typed or null checked by the user anymore.
```
Added some minor unrelated cleanup / tweaks in separate commits. Keep forgetting them otherwise.
No new functionality …

Fix callback type / minor stuff for DI

---

packages/__tests__/5-jit-html/custom-elements.spec.ts
packages/runtime/src/observation/bindable-observer.ts

Fix the wrong initialization logic of bindable observer. Oops on me
Ternary logic is reverse
N/A
Maybe add a few tests that has view model with property value initialized before creating the observers?
N/A

fix(bindable-observer): reverse set interceptor

---

packages/router/src/router.ts

This PR makes the `goto` attribute's active link check take parameters into account.
- Continue with triage comments
- Continue with configuration api
- Fully implement guards/hooks
- Fully implement unknown routes/components
- Add navigation events
- Make `goto` listen to navigation events instead of observing
- Fix `realworld`
- Fix proper sync/async for lifecycle hooks
- Add tests for the new `au-nav` options
- Finish …

fix(router): make goto-active consider parameters

---

CONTRIBUTING.md

this will be easier to find than the reference in the README,
if you have only cloned the repo.
I had this problem, I basically never noticed the contributing docs, because I was just code hunting at first.

docs: add a contributing file for cli developers

---

packages/__tests__/router/viewport.spec.ts
packages/router/src/resources/viewport.ts

This PR makes the viewport attributes `no-link`, `no-history` and `stateful` to not require a value, only to exist, in order to be true.
- Continue with triage comments
- Continue with configuration api
- Fully implement guards/hooks
- Fully implement unknown routes/components
- Add navigation events
- Make `goto` listen to navigation events instead of observing
- Fix `realworld`
- Fix proper sync/async for lifecycle hooks
- Add tests for the new `au-nav` …

feat(router): enable exist for viewport attributes

---

packages/router/src/resources/href.ts

This PR sets no multi bindings on the `href` custom attribute.
- Continue with triage comments
- Continue with configuration api
- Fully implement guards/hooks
- Fully implement unknown routes/components
- Add navigation events
- Make `goto` listen to navigation events instead of observing
- Fix `realworld`
- Fix proper sync/async for lifecycle hooks
- Add tests for the new `au-nav` options
- …

feat(router): set no multi bindings on href attribute

---

packages/__tests__/5-jit-html/binding-resources.spec.ts
packages/runtime-html/src/binding/listener.ts

Fixes a slip-up in the Listener binding (responsible for `trigger`, `delegate` and `capture` commands) so that it works properly in combination with binding behaviors.
Reported on discord
Fix is only 1 line
Added a few tests specifically for debounce (for regular bindings and event bindings)
More tests are still necessary, also for Throttle, but at least the common cases are now verified

Listener binding fix

---

packages/kernel/src/di.ts

fix
```
node_modules/@aurelia/kernel/dist/di.d.ts:74:26 - error TS2304: Cannot find name 'Resolver'.
74     singleton(key: Key): Resolver;
~~~~~~~~
node_modules/@aurelia/kernel/dist/di.d.ts:75:26 - error TS2304: Cannot find name 'Resolver'.
75     transient(key: Key): Resolver;
~~~~~~~~
```

fix(di): should have a return type

---

packages/__tests__/1-kernel/logger.spec.ts
packages/__tests__/aot/smoke-tests.spec.ts
packages/__tests__/validation/rule-provider.spec.ts
packages/aot/src/test.ts
packages/http-server/src/configuration.ts
packages/kernel/src/index.ts
packages/kernel/src/logger.ts

This PR introduces the following improvements for logging. 
1. The `console` logging can be deactivated by simply providing `null` or `undefined` for the console implementation.
```typescript
container.register(LoggerConfiguration.create())
// OR
container.register(LoggerConfiguration.create({$console: null}));
```
2. Developers can now register Sinks explicitly while registering `LoggerConfiguration`.
```typescript
container.register(LoggerConfiguration.create({sinks: [SinkClass1, SinkClass2]}));
```
3. Sinks can declare their handling capabilities using the `sink` decorator. For the following example, the sink instance won't be notified of events other than `error`.
```typescript
@sink({ handles: [LogLevel.error] })
class EventLog implements ISink {
public readonly log: ILogEvent[] = …
```

Logging improvement

---

docs/user-docs/app-basics/validating-data.md

There was a missing import for the `newInstanceForScope` decorator used in the example. The "aurelia" package doesn't appear to export it and I had to import it from the kernel package.

docs(validating-data): missing import for decorator

---

packages/__tests__/2-runtime/scheduler.spec.ts
packages/__tests__/5-jit-html/binding-resources.spec.ts
packages/__tests__/5-jit-html/injectable.spec.ts
packages/scheduler/src/log.ts
packages/scheduler/src/scheduler.ts
packages/scheduler/src/task-queue.ts
packages/scheduler/src/task.ts
packages/scheduler/src/types.ts
packages/validation-html/src/validate-binding-behavior.ts

In this PR I cherry-picked the scheduler-related commits from https://github.com/aurelia/aurelia/pull/845 that pertain only to adding async support.
Adds a new `TaskQueueOption.async: boolean | 'auto'
- If `true`, the return value of the callback will be treated as a promise. Consecutive tasks will be run only after the promise resolved.
- If `'auto'`, the return value of the callback will be treated as a promise only if is an instance of a promise. Appropriate when it's not certain upfront whether the task callback will return a promise or not.
- If `false` (default), the scheduler will treat the task as a synchronous one and will not await it before starting the next task.
I left in some trace logging helper code that I needed from time to time in pinpointing what happens to scheduled …

feat(scheduler): awaitable async task support

---

packages/__tests__/1-kernel/eventaggregator.spec.ts
packages/aurelia/src/index.ts
packages/kernel/src/eventaggregator.ts
packages/kernel/src/index.ts

Mostly typing improvements that fixes some type inference issues with the event aggregator's `publish` signature and makes it possible for end users to override the inferred types with either invocation mechanism
This is a cherry-pick from https://github.com/aurelia/aurelia/pull/845 where I discovered that some common use cases were actually impossible to do in a type-safe manner

Event aggregator refinements

---

packages/__tests__/1-kernel/di.spec.ts
packages/kernel/src/di.ts

In some situations you still see the whole function implementation of `InterfaceSymbol` when it's added to a log or error stack trace, which isn't helpful. With this change it'll be easier to inspect declared dependencies.

report InterfaceSymbol friendly name when converted to string

---

packages/__tests__/2-runtime/ast.integration.spec.ts
packages/__tests__/2-runtime/ast.spec.ts
packages/__tests__/3-runtime-html/interpolation.spec.ts
packages/runtime/src/binding/ast.ts

The AST `.connect()` methods are no longer in use in any part, simply remove this, and tweak the tests so that they verify connecting while evaluating instead.

refactor: remove all ast.connect()

---

packages/__tests__/tsconfig.json
packages/runtime-html/src/binding/attribute.ts
packages/runtime-html/src/binding/listener.ts
packages/runtime-html/src/observation/attribute-ns-accessor.ts
packages/runtime-html/src/observation/class-attribute-accessor.ts
packages/runtime-html/src/observation/data-attribute-accessor.ts
packages/runtime-html/src/observation/element-attribute-observer.ts
packages/runtime-html/src/observation/element-property-accessor.ts
packages/runtime-html/src/observation/style-attribute-accessor.ts
packages/runtime/src/binding/property-binding.ts
packages/runtime/src/binding/ref-binding.ts
packages/runtime/src/observation/array-observer.ts
packages/runtime/src/observation/bindable-observer.ts
packages/runtime/src/observation/binding-context.ts
packages/runtime/src/observation/collection-length-observer.ts
packages/runtime/src/observation/collection-size-observer.ts
packages/runtime/src/observation/dirty-checker.ts
packages/runtime/src/observation/map-observer.ts
packages/runtime/src/observation/primitive-observer.ts
packages/runtime/src/observation/property-accessor.ts
packages/runtime/src/observation/set-observer.ts
packages/runtime/src/observation/setter-observer.ts
packages/runtime/src/observation/signaler.ts
packages/tsconfig-build.json

Some more separation to make runtime code simpler for real values vs typings

refactor: separate type import for runtime

---

docs/user-docs/examples/integration/ms-fast.md
packages/aurelia/src/index.ts

Improvement for the Fast integration documentation.
* Re-export NodeObserverLocator from Aurelia package
* Import the NodeObserverLocator class instead of interface in the fast integration exemple
* Fixes: #1028 
As a follow up question: in the [Fast integration doc page](https://docs.aurelia.io/examples/integration/ms-fast) the imports look like this:
```ts
import { AppTask, IContainer, IAttrSyntaxTransformer, NodeObserverLocator } from 'aurelia';
```
However, in my current application the `aurelia` package doesn't export `AppTask` and `IAttrSyntaxTransformer`. Should them be re-exported from the Aurelia package as well ?
Currently I've changed the imports to look as such: 
```ts
import { AppTask, IContainer, IAttrSyntaxTransformer, NodeObserverLocator } from 'aurelia';
import { …
```

docs(integration-fast): fix typing issue

---

docs/user-docs/examples/integration/ms-fast.md

The property that need to be observed with FAST-TABS is `activeid` and not `value`. Fixed the typo

docs(fast-integration): fix fast-tabs two-way obs

---

packages/aurelia/src/index.ts

Exposes partial bindable for use in the resource.d.ts file from template so it is now correct.
```ts
declare module '*.html' {
import { IContainer, PartialBindableDefinition } from 'aurelia';
export const name: string;
export const template: string;
export default template;
export const dependencies: string[];
export const containerless: boolean | undefined;
export const bindables: Record<string, PartialBindableDefinition>;
export const shadowOptions: { mode: 'open' | 'closed' } | undefined;
export function register(container: IContainer);
}
declare module '*.css';
declare module '*.scss';
```
Update the template for aurelia to utilize

fix(missing): resource.d.ts exposing incorrect

---

packages/runtime-html/src/observation/bindable-observer.ts
packages/runtime-html/src/templating/controller.ts

Continue the work at https://github.com/aurelia/aurelia/pull/1077 . This PR removes the reliance of `BindableObserver` on the `LifecycleFlags`.
In the related PR, we are removing the necessity of using `id` from connectable to determine what flags to pass around, in case of a `binding.handleChange`. The removal of that `id` removed the need of having `LifecycleFlags.updateTarget` & `LifecycleFlags.updateSource` flags. Though we couldn't remove it at that time, since `BindableObserver` still relies on `.updateSource` flag. This PR removes this so that in a next couple of PR, we revamp the flags and their usages a bit more.

refactor(bindable): use controller for determining bound state & change handler 

---

packages/__tests__/i18n/t/translation-integration.spec.ts
packages/i18n/src/t/translation-binding.ts

Ensure parameter updates is done similarly to the main translation binding in terms of timing, and it accounts for individual target property/target pair, rather than one for all. So if we have something like this:
```html
<custom-message t="[message]itemWithCount; [title]itemsWithCount" t-params.bind="{count}">
```
and `count` gets changed from `0` to `10`, it would:
- `<custom-message/>` view model `message` property immediately gets updated to `10 items`
- The update of the `title` property of `<custom-message/>` element is queued for the next frame
Before #1087 , it would always update both immediately
After #1087, it would always queue both and update after the next frame
The correct behavior should be as described above: immediate on view model and queued for view

fix(i18n): also queue param updates, fix tests

---

packages/__tests__/3-runtime-html/au-slot.spec.ts
packages/runtime-html/src/template-binder.ts

Slotted elements might be used with `as-element` attribute.
The correct parent name allows for the proper usage check.
#1103 
The test makes sure that using `as-element` with slots does not throw.

fix(template-binder): check if as-element was used

---

packages/__tests__/2-runtime/binding.spec.ts
packages/__tests__/3-runtime-html/custom-attributes.spec.ts
packages/__tests__/3-runtime-html/select-value-observer.spec.ts
packages/runtime-html/src/observation/attribute-ns-accessor.ts
packages/runtime-html/src/observation/bindable-observer.ts
packages/runtime-html/src/observation/class-attribute-accessor.ts
packages/runtime-html/src/observation/data-attribute-accessor.ts
packages/runtime-html/src/observation/select-value-observer.ts
packages/runtime-html/src/observation/style-attribute-accessor.ts
packages/runtime-html/src/observation/value-attribute-observer.ts
packages/runtime/src/observation/setter-observer.ts

Make all the value prop names of observers consistent, and to `value`

refactor(all): rename currentValue -> value

---

docs/user-docs/routing/navigating-with-load.md

There was an error with the router.load() method. The documentation stated that it should have "parameters" parameter, but it's actually "params" in the code.

Update navigating-with-load.md - Fixed router.load parameters text.

---

packages/__tests__/3-runtime-html/lifecycle-hooks.spec.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/templating/lifecycle-hooks.ts
packages/runtime-html/src/templating/render-context.ts

Currently the hooks are resolved twice if it's not from root. Fix this, also ensure that resources semantic is maintain by checking if there's a resolver first.
Tweak some code so that it's friendlier for minification

fix(lifecycle-hooks): properly maintain resources semantic

---

packages/__tests__/3-runtime-html/select-value-observer.spec.ts
packages/runtime-html/src/observation/select-value-observer.ts
test/benchmarking-apps/storage/package.json
test/benchmarking-apps/test-result/package.json

At the moment, when calling `.notify()`, `oldValue` prop of the select observer is not refreshed so future notification may not work properly because changes are not detected. Fix this & also try to fix the build on local for https://discourse.aurelia.io/t/unable-to-build-au2-on-windows/4156/
For the following template & view model:
```html
<h3>Select Product</h3>
<select value.bind="selectedProductId">
<option model.bind="null">Choose...</option>
<option repeat.for="product of products" model.bind="product.id">
\${product.id} - \${product.name}
</option>
</select>
<h3>Data</h3>
Selected product ID: \${selectedProductId}
<button click.trigger="clear()">clear</button>
```
```ts
class App {
products = [
{ id: 0, name: "Motherboard" },
{ id: 1, name: "CPU" },
{ id: 2, name: "Memory" }
]; …
```

Fix(select-observer): ensure value fresh when notify

---

packages/kernel/src/di.ts

At the moment, metadata polyfill application strict, but it probably can be eased. This is to support HMR, storybook and similar scenarios where the bundle will be loaded again and again.

refactor: ease multiple metadata polyfill strictness

---

packages/runtime/src/observation/array-observer.ts
packages/runtime/src/observation/proxy-observation.ts

At the moment, `.find` method of arrays are not properly handled in computed, it's treated as a normal method/property on an object. This PR fixes this.

fix(array-obs): handle array.find for computed obs, dont cache index obs

---

docs/user-docs/advanced-scenarios/write-custom-plugin.md
docs/user-docs/app-basics/extending-templating-syntax.md
docs/user-docs/examples/integration/ms-fast.md
packages/__tests__/3-runtime-html/attr-syntax-extension.spec.ts
packages/__tests__/router/_shared/configuration.ts
packages/i18n/src/configuration.ts
packages/router/src/configuration.ts
packages/runtime-html/src/app-task.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/templating/dialog/dialog-configuration.ts
packages/runtime-html/src/templating/dialog/dialog-service.ts
packages/runtime-html/src/templating/styles.ts

feat(app-task): allow app task to be created without a key
Make app task signature similar to `DI.createInterface<T>(...)`, where it would require all parameters to the final resolution to be declared upfront
Before:
```ts
AppTask.with(IContainer).beforeCreate().call((container) => { ... })
```
After:
```ts
// with injection usage
AppTask.beforeCreate(IContainer, (container) => { ... })
// no injection usage
AppTask.beforeCreate((container) => { ... })
```
1. `AppTask` cannot be created without a key, the following usage would throw a compilation error (TS), and runtime error (JS):
```ts
AppTask.with().beforeCreate().call(() => { ... })
```
2. `AppTask` callback may not be specified properly:
```ts
AppTask.with(IContainer).beforeCreate() // missing callback specification
```
3. `AppTask` …

refactor(app-task): simplify usage, align with .createInterface

---

docs/user-docs/app-basics/dynamic-ui-composition.md
packages/__tests__/3-runtime-html/compose.spec.ts
packages/__tests__/integration/app/molecules/specs-viewer/specs-viewer.html
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/runtime-html/src/resources/custom-elements/au-render.ts

Compared to v1 `<compose/>`, the current `au-compose` is having a different API set aiming to take advantages of the new templating primitives in v2, though since the time it was envisioned, things have changed quite a bit and its capabilities don't address the core needs of a more familiar API set in V1. This PR adds back the v1 composition functionalities, with a few breaking changes as noted below:
- main: passing a string to either view/ view model no longer means module name. The composer only understands string as template for `view` and objects and classes for `view-model` now. Though if it's still possible to turn treat string as module name, with the help of value converter:
```html
<au-compose view="https://my-server.com/views/${componentName} | loadView">
```
```ts
class …
```

feat(compose): add v1 ability to compose from view + view model + model

---

packages/__tests__/1-kernel/di.spec.ts
packages/kernel/src/di.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/runtime/src/observation/binding-context.ts
packages/testing/src/test-builder.ts

At the moment, root resources is carried over to every leaf, this seems excessive.
Rename prop `isComponentBoundary` -> `isBoundary` on scope, as scope wouldn't care how it's used.

fix(resources): prevent duplication, don't carry root resources to leaf

---

packages/__tests__/1-kernel/di.spec.ts
packages/__tests__/3-runtime-html/binding-resources.spec.ts
packages/__tests__/3-runtime-html/di-registrations.spec.ts
packages/kernel/src/di.ts

when using @newInstanceOf and @newInstanceForScope, even with an interface that already has a registered resolver, it will still throw as as it always tries to construct the interface, instead of the  corresponding implementation.
partially fixes #1166: this commit prepares a test where the most intuitive behavior is shown: ability to invoke an interface without having to declare it, if it has a default registration. Though this is inconsistent with the core, so will have to reconsider.
At the moment, it still requires the interface to be registered in order to be correctly invoked.
Find a balance between intuitiveness & consistency for `.get()` vs `@newInstanceOf()`/ `@newInstanceForScope()`

fix(new-instance): correctly invoke a registered interface

---

packages/runtime-html/src/templating/dialog/dialog-default-impl.ts

In order for the dialog itself to be centered with the `margin: auto`, its direct parent must be `display: flex` which is the overlay and not the container.

Fix dialog-default-impl: display flex on overlay

---

docs/user-docs/examples/integration/ionic.md
docs/user-docs/examples/integration/ms-fast.md
package.json
packages/__tests__/3-runtime-html/attr-syntax-extension.spec.ts
packages/aurelia/src/index.ts
packages/i18n/src/t/translation-parameters-renderer.ts
packages/i18n/src/t/translation-renderer.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/app-task.ts
packages/runtime-html/src/attribute-mapper.ts
packages/runtime-html/src/bindable.ts
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/observation/attribute-ns-accessor.ts
packages/runtime-html/src/observation/svg-analyzer.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/attribute-pattern.ts
packages/runtime-html/src/resources/binding-command.ts
packages/runtime-html/src/resources/custom-attribute.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/watch.ts

Some small changes to cleanup the project before going for the next bigger ones.
- With previous compiler refactoring, attr syntax transformer now is no longer a transformer, just a mapper. Rename this to properly reflect this. Updated doc.
- Continue separate type/value imports
- Add some comments to a few sections of the code. Ideally should be a rename, though keeping the scope small each PR.
- fix #1169

chore: clean up

---

packages/__tests__/3-runtime-html/let.spec.ts
packages/runtime-html/src/template-compiler.ts

At the moment, `<let/>` does not camelising the target property if it's an interpolation or literal:
```html
<let my-prop="1" my-p="${myProp}-2" >
```
will results in instructions against `my-prop` and `my-p` respectively, which is wrong. They should be `myProp` and `myP`. This PR fixes it.

fix(let): camel-case let target when using with interpolation/literal

---

docs/CHANGELOG.md
packages/__tests__/3-runtime-html/controller.host-sharing.integration.spec.ts
packages/__tests__/3-runtime-html/di-registrations.spec.ts
packages/__tests__/3-runtime-html/local-dependency-inheritance.spec.ts
packages/__tests__/3-runtime-html/styles.spec.ts
packages/kernel/src/di.ts
packages/router/src/component-agent.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/create-element.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/runtime-html/src/resources/custom-elements/au-render.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/templating/dialog/dialog-controller.ts
packages/runtime-html/src/templating/render-context.ts

At the moment, the container of a custom element is created after the corresponding view model has been instantiated. This creates unexpected behavior in the scope of the dependencies. Example is `@newInstanceForScope` would register the dependencies onto the parent container instead of the CE own one:
```html
app.html
<list ref="list1"></list>
<list ref="list2"></list>
```
```ts
class Model {}
class List {
constructor(@newInstanceForScope(Model) model) {}
}
```
Would result in 2 instances of `Model` scoped to with the app component container, instead of the 2 containers of `List` components.
Other changes:
- Custom element own container now registers the constructor with the instance, allowing its children to inject based on the constructor, beside the injectable token API. This is to …

refactor(templating): change custom element own container timing

---

packages/runtime-html/src/index.ts
packages/runtime-html/src/resources/custom-elements/au-slot.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/templating/render-context.ts
packages/runtime-html/src/templating/styles.ts
packages/runtime-html/src/templating/view.ts

refactor(au-slot): use new hydration context token
With the hydration context timing now more controllable, add a new injectable token: `IHydrationContext` that is only available inside a custom element hydration.
`<au-slot/>` can also retrieve its context information with ease. Also employ DI instead of manual tree walk.

feat(templating): add a injectable hydration token

---

packages/__tests__/3-runtime-html/au-slot.spec.ts
packages/__tests__/3-runtime-html/template-compiler.spec.ts
packages/kernel/src/di.ts
packages/runtime-html/src/create-element.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/runtime-html/src/resources/custom-elements/au-slot.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/templating/dialog/dialog-controller.ts
packages/runtime-html/src/templating/render-context.ts

At the moment, `<au-slot/>` view factory is determined at compilation time, which is prone to cached compilation issue, also prohibits the ability to toggle between projected content and fallback content (if there's projection, do not render fallback and vice versa) to align `<au-slot/>` behavior with native `<slot/>`. Refactor this, and move factory creation to the instantiation time of `AuSlot` so that there can be more flexibility in terms on scope choosing, factory constructing, and ensure correctness in tricky situation like 3 layers of pass through slot seen in this issue #1205.
In order to support this, `IHydrationContext` has been enhanced with a `parent` property so that it can build the proper hydration context hierarchy, allowing `<au-slot/>` to pick the right scope.
Closes …

refactor(au-slot): lazily determine view factory at instantiation time

---

.circleci/config.yml

Temporary disable the current bench app, since it's as slow as Krauset and not as clear as Krauset on giving a rough estimate where the core performance level is. For now, use some repeater tests as temporary measurement instead.

chore(ci): temp disable bench

---

docs/user-docs/TOC.md
docs/user-docs/developer-guides/extending-templating-syntax.md
docs/user-docs/developer-guides/template-compiler-hooks.md
packages/__tests__/3-runtime-html/template-compiler.hooks.spec.ts
packages/__tests__/3-runtime-html/template-compiler.spec.ts
packages/aurelia/src/index.ts
packages/kernel/src/di.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/utilities-di.ts

A missing capabilities of v1 is the compilation hooks. This is a very focused hooks of the compilation that should be much more ergonomic than the existing define hooks, which is also quite intimidating. Probably the `define` hooks can be partially replaced by a `before` + `after` compilation hooks instead.
The interface of a hook is:
```ts
interface ITemplateCompilerHooks {
beforeCompile(template: HTMLElement): void;
}
```
Note that `Hooks` in the name indicates that there may be more hooks in the future, beside `beforeCompile`.
- **added**: `allResources` resolver builder. This is to be used for many resources like injectable: `IAttrPattern`, `IBindingCommand` etc...
- Existing tests work
- Verify the resources are retrieved with resources semantic
- Refactor the compilation process & …

feat(template-compiler): add beforeCompile hooks

---

packages/__tests__/3-runtime-html/au-slot.spec.ts
packages/runtime-html/src/resources/custom-elements/au-slot.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime/src/observation.ts

Currently the all controllers are accepting host scope, which is a bit wasteful and incorrect. Issues can come up like #1210 where normal binding from CE accidentally picks up some scope from parent because it's activated by an `<au-slot/>`. Disable this, which fixes the issue, and should help avoid doing unnecessary work.
fixes #1210
Thanks @MaximBalaganskiy

fix(scope): disable host scope on CE controller

---

packages/__tests__/3-runtime-html/au-slot.spec.ts
packages/__tests__/3-runtime-html/compose.spec.ts
packages/__tests__/3-runtime-html/enhance.spec.ts
packages/__tests__/3-runtime-html/process-content.spec.ts
packages/__tests__/3-runtime-html/promise.spec.ts
packages/__tests__/3-runtime-html/repeater-custom-element.spec.ts
packages/__tests__/3-runtime-html/switch.spec.ts
packages/__tests__/3-runtime-html/template-compiler.spec.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-attribute.ts
packages/runtime-html/src/resources/custom-element.ts
packages/runtime-html/src/template-compiler.ts

Add ability to remove binding expressions, including:
- containerless
- as-element
- ref
- attr with binding expression (`attr.command="..."`)
- attr with interpolation (`attr="${someExpression}"`)
- custom attribute
- custom element bindables
The default of the default template compiler is removing all expressions. To toggle off this behavior, set `debug` to `true` (for the default compiler):
```ts
Aurelia.register(
AppTask.beforeCreate(ITemplateCompiler, compiler => compiler.debug = true)
).app(MyApp)
```
Closes #420
Example:
Before:
```html
<input type="text" value.bind="firstName">
```
After:
```html
<input type="text" class="au">
```

feat(template-compiler): ability to toggle expressions removal

---

packages/__tests__/3-runtime-html/controller.host-sharing.integration.spec.ts
packages/__tests__/3-runtime-html/di-resolutions.spec.ts
packages/__tests__/i18n/t/translation-parameters-renderer.spec.ts
packages/__tests__/i18n/t/translation-renderer.spec.ts
packages/__tests__/router/_shared/create-fixture.ts
packages/__tests__/router/hook-tests.spec.ts
packages/__tests__/router/smoke-tests.spec.ts
packages/i18n/src/t/translation-parameters-renderer.ts
packages/i18n/src/t/translation-renderer.ts
packages/router/src/component-agent.ts
packages/router/src/route-context.ts
packages/router/src/route-definition.ts
packages/router/src/route-tree.ts
packages/router/src/router.ts
packages/router/src/viewport-agent.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/create-element.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-elements/au-slot.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/templating/render-context.ts
packages/runtime-html/src/templating/view.ts
packages/store-v1/src/decorator.ts

Continue the removal of `IContainer` APIs out of `IRenderContext`, and eventual removal of the `IRenderContext` itself. This is to avoid wasteful creation of `IRenderContext`. Also, having a context on a controller unnecessarily complicate the meaning of a controller itself, where there' a few concepts that need to be juggled: `IViewFactory`, `IRenderContext`, `IController`
Also a part of this optimization, treat renderers as root only resources now. This is some kind of resources that we probably don't want to make overflexible.

refactor(render-context): remove IContainer APIs from rendering context

---

docs/user-docs/developer-guides/the-template-compiler.md
packages/__tests__/3-runtime-html/template-compiler.hooks.spec.ts
packages/__tests__/3-runtime-html/template-compiler.spec.ts
packages/runtime-html/src/template-compiler.ts

BREAKING CHANGE: the hook name has been changed to keep the consistency with the rest of templating lifecycles
Thanks @jwx for the reminder.

refactor(template-compiler): beforeCompile -> compiling

---

docs/user-docs/developer-guides/routing/common-routing-tasks.md

Copying the code from the snippet:
```typescript
@route({
routes: [
{ id: 'home', path: '', redirectTo: 'products' },
{ path: 'products', component: import('./products'), title: 'Products' },
{ path: 'product/:id', component: import('./product'), title: 'Product' }
]
})
```
I get the following error:
```
Only 'path' and 'redirectTo' should be specified for redirects
```
Hence removing `id: 'home'` from the redirect route

Small change to Redirecting routes code snippet

---

docs/user-docs/getting-to-know-aurelia/app-configuration-and-startup.md
docs/user-docs/resources/migrating-to-aurelia-2.md
packages/__tests__/3-runtime-html/controller.host-sharing.integration.spec.ts
packages/__tests__/3-runtime-html/enhance.spec.ts
packages/__tests__/3-runtime-html/if.integration.spec.ts
packages/__tests__/3-runtime-html/process-content.spec.ts
packages/__tests__/3-runtime-html/repeater.unit.spec.ts
packages/__tests__/3-runtime-html/styles.spec.ts
packages/__tests__/integration/app/molecules/random-generator/random-generator.ts
packages/__tests__/integration/app/startup.ts
packages/aurelia/src/index.ts
packages/router/src/component-agent.ts
packages/router/src/router.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/aurelia.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/templating/dialog/dialog-controller.ts
packages/runtime-html/src/templating/view.ts

At the moment, `Aurelia.enhance` works similarly to `Aurelia.app`: it would become an application root of itself. While this gives some interesting perspective to look at enhance, it makes the usage of enhance more difficult than the method name suggests. Change the way `Aurelia.enhance` work to the same with `enhance` in v1.
CHANGES:
- remove: root requirement in `Controller.forCustomElement`, `Controller.forSyntheticView`, `Controller.forCustomAttribute`: it shouldn't require irrelevant information to the construction of a controller. The existing internal way to halt/resume hydration is moved to hydration instruction.
- remove: root property in `IController`/`Controller`. This should give some more perf boost.
- doc: add examples how to create a view factory
- doc: add examples how to …

refactor(enhance): change working mechanism of enhance to the same with v1

---

examples/realworld-advanced/e2e/auth.spec.ts
examples/realworld/e2e/auth.spec.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/aurelia.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/templating/dialog/dialog-controller.ts

Currently `Controller` always try to determine the platform associated with its container, though this is not always used. Remove this and the associated properties + interfaces.
For host injection, currently we are supporting 4 injection key: `INode`, `Node`, `Element`, `HTMLElement`, This is a bit unnecessary. Remove `Node` & `HTMLElement` registration during container preparation.

chore(cleanup): avoid doing wasteful work

---

docs/user-docs/developer-guides/the-template-compiler.md
packages/__tests__/3-runtime-html/create-element.spec.ts
packages/__tests__/3-runtime-html/template-compiler.spec.ts
packages/i18n/src/t/translation-binding.ts
packages/runtime-html/src/binding-behaviors/throttle.ts
packages/runtime-html/src/observation/bindable-observer.ts
packages/runtime-html/src/observation/checked-observer.ts
packages/runtime-html/src/observation/event-delegator.ts
packages/runtime-html/src/observation/style-attribute-accessor.ts
packages/runtime-html/src/observation/svg-analyzer.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/attribute-pattern.ts
packages/runtime-html/src/resources/custom-elements/au-render.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/templating/children.ts
packages/runtime-html/src/utilities-html.ts
packages/runtime/src/observation/observer-locator.ts
packages/runtime/src/utilities-objects.ts

At the moment, `instructions` property on hydrate element/attribute/template controller doesn't sound as clear as it should. If it's about properties of CE/CA/TC then should just name it so.
- doc: Add some more doc related to how to use the default template compiler elsewhere.
- add some small comments explaining the main `_compileElement` function to balance between comprehensiveness & perf

refactor(compiler): rename instructions to props on CE/CA instruction

---

docs/user-docs/getting-to-know-aurelia/introduction/built-in-template-features/promise.bind.md
packages/__tests__/3-runtime-html/attribute-pattern.spec.ts
packages/__tests__/i18n/t/translation-integration.spec.ts
packages/__tests__/importmap.js
packages/__tests__/karma.conf.cjs
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/resources/attribute-pattern.ts
packages/runtime-html/src/resources/template-controllers/promise.ts

At the moment, when having some patterns in the following order:
```ts
{ pattern: 'then'  },
{ pattern: 't' }
```
The interpreter would build a state machine that:
- is terminatable at `t` (because of the `{ pattern: 't' }`)
- has `then` as the first matching pattern for `t` (because `then` is registered before `t`)
A fix for this is to ensure that patterns are sorted based on length. This enables the tests for simple `then`/`catch` usage:
```html
<div promise.bind="...">
<div then="data">...</div>
<div catch="err">...</div>
</div>
```
Change default binding mode of `then` & `catch` from `to-view` to `from-view`, and add more tests for the simple binding usage above. cc @Sayan751

fix(attr-parser): sort the patterns before building the states

---

packages/__tests__/i18n/t/translation-parameters-renderer.spec.ts
packages/__tests__/i18n/t/translation-renderer.spec.ts
packages/i18n/src/t/translation-parameters-renderer.ts
packages/i18n/src/t/translation-renderer.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/aurelia.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/binding-command.ts
packages/runtime-html/src/resources/custom-attribute.ts
packages/runtime-html/src/resources/custom-element.ts
packages/runtime-html/src/resources/resources-constants.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/templating/dialog/dialog-controller.ts

Currently, template compiler turns attribute values into expressions before passing it to binding command to build corresponding instructions. This is sometimes inappropriate, as the template compiler sometimes needs to know what a binding command wants.
This PR changes it so that the expression parsing job is controlled by the binding commands themselves. This should make the abstraction more sound, and avoid wasteful work while enabling a better way to author custom binding binding commands.
This is a prerequisite work, to make things nicer and easier for syntax related features such as
- on binding command #1255 
- bindables targeted binding #1258 
- shorthand syntax for property binding #1259
- attribute transferring #1197 
Start implementing attribute transferring.

refactor(template-compiler): let binding command control expression parsing work

---

packages/__tests__/3-runtime-html/binding-commands.spec.ts
packages/__tests__/router/smoke-tests.spec.ts
packages/i18n/src/t/translation-binding.ts
packages/i18n/src/t/translation-parameters-renderer.ts
packages/i18n/src/t/translation-renderer.ts
packages/router/src/resources/href.ts
packages/runtime-html/src/binding/let-binding.ts
packages/runtime-html/src/create-element.ts
packages/runtime-html/src/observation/class-attribute-accessor.ts
packages/runtime-html/src/resources/binding-command.ts
packages/runtime-html/src/template-compiler.ts

Always reflect the value of href custom attribute on the host element.
Changes:
- rename `bindingType` on binding command to `type`

fix(href): avoid native href interference

---

docs/user-docs/developer-guides/dialog.md

Fix typo in code sample in dialog.md. The variable openDialogResult is used in the previous sample, in this one it is deconstructed into { dialog }
No issues were listed for this, just came across these while reading the docs.

Fix typo in code sample in dialog.md

---

docs/user-docs/TOC.md
docs/user-docs/getting-to-know-aurelia/introduction/attributes-transfering.md
docs/user-docs/getting-to-know-aurelia/introduction/built-in-template-features/README.md
docs/user-docs/reference/examples/integration/README.md
docs/user-docs/reference/examples/integration/ionic.md
docs/user-docs/reference/examples/integration/ms-fast.md
packages/__tests__/3-runtime-html/spread.spec.ts
packages/__tests__/3-runtime-html/template-compiler.spec.ts
packages/platform-browser/src/index.ts
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/create-element.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/attribute-pattern.ts
packages/runtime-html/src/resources/binding-command.ts
packages/runtime-html/src/resources/custom-element.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/templating/controller.ts
packages/testing/src/test-context.ts

Add support for transferring attributes with `...$attrs` syntax. Example:
```html
app.html
<my-input value.bind="message">
my-input.html
<input ...$attrs>
```
Attribute transferring is a way to relay the binding(s) on a custom element to other element(s) inside it.
As an application grows, the components inside it also grow. Something that starts simple like the following component
```typescript
export class FormInput {
@bindable label
@bindable value
}
```
with the template
```html
<label>${label}
<input value.bind="value">
</label>
```
can gradually grow out of hand with a number of needs for configuration: aria, type, min, max, pattern, tooltip, validation etc...
After a while, the `FormInput` component above will be come more and more like a relayer to transfer the bindings from …

feat(attr-transfer): support attributes spreading with ...$attrs

---

packages/__tests__/3-runtime-html/au-compose.spec.ts
packages/runtime-html/src/create-element.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/runtime-html/src/resources/custom-elements/au-render.ts

This PR fixes an issue where `au-compose` does not work with `[au-slot]`. An example is the following
```html
<au-compose>
<p au-slot>Hello</p>
</au-compose>
```
for custom element template
```html
<div><au-slot></au-slot></div>
```
Will not result in
```html
<div><p>Hello</p></div>
```

feat(au-compose): works with au-slot

---

package.json
packages/__tests__/3-runtime-html/au-compose.spec.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/utilities-html.ts

- `ChangeInfo` of au compose can be a little less polluted by moving initiator info out. Added a test for #1299, it's failing because of the promise of `animate` call not resolving, due to element/style property combo being un-animatable. The main causes by the repeat require a bit bigger refactoring. Will probably need to continue in another PR.
- Added a root level script to quickly run the tests

refactor(au-compose): move initiator out of change info, add tests for #1299

---

packages/runtime-html/src/resources/template-controllers/promise.ts

The promise TC cancels any pre-settlement task if the promise is found to be settled and the pre-settlement task is not yet running. However, as the promise TC acquires the "task-promise" by doing `preSettledTask.result`, cancelling the task results in the rejection of the promise. This rejection on the users' end can be bit confusing. Thus, this error is suppressed in this PR.

fix(promise): suppressed TaskAbortError on cancellation

---

package-lock.json
package.json
packages/__tests__/karma.conf.cjs
packages/__tests__/package.json

* Add ability to run main packages in normal & watch mode from project root
* Fix an issue where not all relevant files are picked when a pattern is use.
Example:
When running
```
npm run test computed
```
Before:
```
LOG: '[00:00.354] >   160 tests in "3-runtime-html/decorator-watch.computed.spec.ts"'
```
After:
will pickup all the tests like this
```
LOG: '[00:00.000] >    56 tests in "[UNIT] 2-runtime/computed-observer.spec.ts"'
LOG: '[00:00.045] >    43 tests in "3-runtime-html/computed-observer.spec.ts"'
LOG: '[00:00.354] >   160 tests in "3-runtime-html/decorator-watch.computed.spec.ts"'
```

chore(tests): better matching file name

---

packages/__tests__/3-runtime-html/attribute-pattern.spec.ts
packages/__tests__/3-runtime-html/template-compiler.spec.ts
packages/runtime-html/src/template-compiler.ts

At the moment, when using attr pattern with custom attribute, if the new `AttrSyntax` does not have binding command, it will use the existing attribute value, instead of the value specified in the new `AttrSyntax`. Example:
```html
<div my-attr>
```
```ts
@attributePattern({ pattern: 'my-attr', symbols: '' })
class MyAttrPattern {
public 'my-attr'(rawName: string, rawValue: string, parts: string[]) {
// binding command works:
return new AttrSyntax(rawName, rawValue, 'my-custom-attr', 'bind');
// interpolation does not work
return new AttrSyntax(rawName, `some wrapping text ${rawValue}`, 'my-custom-attr', null);
// converting into multi binding mode does not work
return new AttrSyntax(rawName, `value: ${rawValue}; label: Some label`, 'my-custom-attr', null)
}
}
```
This inconsistency is …

fix(compiler): allowing syntax modification from attr pattern on some cases for custom attribute

---

packages/__tests__/3-runtime-html/promise.spec.ts
packages/__tests__/3-runtime-html/switch.spec.ts
packages/__tests__/karma.conf.cjs
packages/runtime-html/src/resources/template-controllers/promise.ts
packages/runtime-html/src/resources/template-controllers/switch.ts

This PR addresses the reported issue on discourse (https://discourse.aurelia.io/t/switch-case-statements-in-templates/4702)
of the CE VM are being instantiated even if the cases are not matched. Previously, the controller was created in the `Case#ctor`. This commit defers it to the `Case#activate`; that is, when the case matches the switch condition and about to be activated.
It also defers the instantiations for promise-tc's VMs.

refactor(switch+promise): deferred view instantiation

---

docs/user-docs/developer-guides/fetch-client.md

Following the docs before the fix, I get this error:
TS2345: Argument of type '(config: HttpClientConfiguration) => void' is not assignable to parameter of type 'RequestInit | ((config: HttpClientConfiguration) => HttpClientConfiguration) | HttpClientConfiguration'. Type '(config: HttpClientConfiguration) => void' is not assignable to type '(config: HttpClientConfiguration) => HttpClientConfiguration'. Type 'void' is not assignable to type 'HttpClientConfiguration'.

docs: HttpClient.configure returns the config, not void

---

packages/__tests__/3-runtime-html/dialog/dialog-service.spec.ts
packages/__tests__/setup-shared.ts
packages/testing/src/startup.ts

To prepare to go beta, we need to provide a testing toolset that is easy enough to use to document & teach, also helps with bug repro reports. This PR enhances the `createFixture` method, so that it runs faster, and provides a builder pattern in case clarity of what being built is prefered.
Instead of having to write:
```ts
const {} = await createFixture('<div>', class AppRoot {}, [someConfig1, someConfig2]).promise
```
can also do
```ts
const {} = await createFixture
.component(class AppRoot {})
.deps(someConfig1, someConfig2)
.html`<div>`)
.build()
.promise
```
When the parameters are compact, the former way is prefer, but can be refactored into the later if the parameters grow out of hand:
```ts
const { } = await createFixture(
`Some big chunk of markup
...
<my-el>`,
class App {
prop1 …
```

refactor(testing): enable builder pattern for fixture creation

---

packages/__tests__/3-runtime-html/au-compose.spec.ts
packages/__tests__/3-runtime-html/custom-elements.spec.ts
packages/__tests__/3-runtime-html/listener.spec.ts
packages/__tests__/3-runtime-html/template-compiler.harmony.spec.ts
packages/__tests__/state/state.spec.ts
packages/runtime-html/design-improvement-notes.md
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/runtime-html/src/template-compiler.ts
packages/runtime-html/src/templating/controller.ts
packages/testing/src/startup.ts
scripts/dev.ts

At the moment, `containerless` can only be configured from view model `@customElement` decorator. This is different with v1, where it can be configured via either view/view model. Make v2 behave similarly for now.
- rename `promise` -> `started` on `IFixture`

feat(containerless): ability to override `containerless` config from view

---

package.json
packages-tooling/__tests__/esbuild.dev.cjs
packages-tooling/__tests__/package.json
packages/kernel/src/module-loader.ts
scripts/dev-tooling.ts

Similar to core packages, tooling packages development should have a simple script to build, watch and run tests based on file name pattern. Add a new script `dev:tooling` that can be used like this:
```shell
npm run dev:tooling -- --dev [tooling package name] --test [test file pattern]
npm run dev:tooling -- -d [tooling package name] -t [test file pattern]
```
By default, plugin convention is auto built & watched for changes to rerun tests.
An example of auto build `plugin-conventions` on change, and run `preprocess-resource` tests:
```
npm run dev:tooling -- -t preprocess
```

chore(dev): add tooling dev scripts

---

packages/__tests__/.eslintrc.cjs
packages/__tests__/3-runtime-html/lifecycle-hooks.attaching.spec.ts
packages/__tests__/3-runtime-html/lifecycle-hooks.resolve.spec.ts
packages/__tests__/3-runtime-html/repeat.vc.bb.spec.ts
packages/runtime-html/src/templating/controller.ts

Continue the work on lifecycle hooks, part of #1044, add `attaching` lifecycle hooks. It'll be working similarly like other lifecycle:
- invoked before the view model attaching lifecycle
- invoked in parallel with the view model attaching lifecycle. Promises returned here will be aggregated together with view model promise returned from attaching lifecycle (if any)

feat(lifecycle-hooks): add attaching

---

packages/__tests__/3-runtime-html/lifecycle-hooks.attaching.spec.ts
packages/__tests__/3-runtime-html/lifecycle-hooks.created.spec.ts
packages/__tests__/3-runtime-html/lifecycle-hooks.detaching.spec.ts
packages/__tests__/3-runtime-html/lifecycle-hooks.hydrated.spec.ts
packages/__tests__/3-runtime-html/lifecycle-hooks.hydrating.spec.ts
packages/runtime-html/src/templating/controller.ts

Continue the work on lifecycle hooks, part of #1044, add `deataching` lifecycle hooks. It'll be working similarly like other lifecycles:
* invoked before the view model `detaching` lifecycle
* invoked in parallel with the view model `detaching` lifecycle. Promises returned here will be aggregated together with view model promise returned from `detaching` lifecycle (if any)

feat(lifecycle-hooks): detaching

---

packages/__tests__/3-runtime-html/lifecycle-hooks.attached.spec.ts
packages/runtime-html/src/templating/controller.ts

Continue the work on lifecycle hooks, part of #1044, add attached lifecycle hooks. It'll be working similarly like other lifecycles:
* invoked before the view model `attached` lifecycle
* invoked at a level after all the child levels `attached` have been invoked 
* invoked in parallel with the view model `attached` lifecycle. Promises returned here will be aggregated together with view model promise returned from `attached` lifecycle (if any)

feat(lifecycle-hooks): attached

---

packages/__tests__/3-runtime-html/lifecycle-hooks.all-in-one.spec.ts
packages/__tests__/3-runtime-html/lifecycle-hooks.binding.spec.ts
packages/__tests__/3-runtime-html/lifecycle-hooks.bound.spec.ts
packages/__tests__/3-runtime-html/lifecycle-hooks.unbinding.spec.ts
packages/runtime-html/src/templating/controller.ts

Continue the work on lifecycle hooks, part of #1044, add `binding`/`bound`/`unbinding` lifecycle hooks. It'll be working similarly like other lifecycles:
| # | invocation timing | sequence | direction |
| - | - | - | - |
| binding | before view model `binding` | parallel | top down - sequential |
| bound | before view model `bound` | parallel | top down - sequential |
| unbinding| before view model `unbinding` | parallel | bottom up - parallel |

feat(lifecycle-hooks): binding + unbinding + bound

---

.vscode/launch.json
packages/__tests__/router-lite/resources/load.spec.ts
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/index.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/resources/load.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/router.ts

This closes the issue #1347. That is, the router now supports `router.load('route/:id/as-configured', {params:{id:'foo'}})`. Any additional un-configured parameters are added to the query string.
This same behaviour is now also applicable for the `load` CA.
Finally, it removes the inclusion of parent node's parameters to the child node's parameter collection, in a hierarchical routing configuration.

fix(router-lite): better handling of parameters and querystring

---

.circleci/config.yml
docs/user-docs/getting-to-know-aurelia/components/attributes-transferring.md
examples/jit-webpack-conventions-ts/src/app.html
examples/jit-webpack-conventions-ts/src/components/jit-input.html
examples/jit-webpack-conventions-ts/src/components/jit-input.ts
packages-tooling/__tests__/plugin-conventions/preprocess-html-template.spec.ts
packages-tooling/__tests__/plugin-conventions/strip-meta-data.spec.ts
packages-tooling/plugin-conventions/src/preprocess-html-template.ts
packages-tooling/plugin-conventions/src/strip-meta-data.ts
packages/__tests__/3-runtime-html/custom-elements.decorator.spec.ts
packages/aurelia/src/index.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/resources/custom-element.ts
packages/testing/src/inspect.ts
scripts/dev-tooling.ts
test/playwright/src/examples.spec.ts

Closes #1465 
Add `<capture>` for conventions and `@capture` for standalone usage.
```html
<capture>
or
<template capture>
```
vm:
```ts
import { capture } from 'aurelia';
@capture
export class Field {
...
}
```
Also updated our pipeline so only convention is running now. If we want to test vanilla, probably it's best to put that into the same app with convention instead of running 2 independently.

Capture shortcut

---

packages/__tests__/3-runtime-html/observer-locator.spec.ts
packages/runtime-html/src/observation/observer-locator.ts

Somehow the failure in tests for some html attr observation only surfaced just now, fix them.
It seems it used to be `'role' in HTMLDivElement === true` has been changed. Firefox/Jsdom are both false while it's true on chrome. Just remove this assertion since it's not really necessary anyway.

fix(node-obs): dont treat role differently

---

docs/user-docs/developer-guides/state/README.md

Improvement for [aurelia/state](https://docs.aurelia.io/developer-guides/state) documentation.
Aurelia/State has a typo in the initial setup documentation. Following the current documentation leads to a situation where the state is created, but the state isn't updated when using dispatch.  
Additionally, no warning is shown to the user that reducers are not registered.
Change made in `docs/user-docs/developer-guides/state/README.md`
```diff
Aurelia
.register(
-   StateDefaultConfiguration.init(initialState),
-   keywordsHandler
+   StateDefaultConfiguration.init(
+     initialState,
+     keywordsHandler
+   )
)
.app(MyApp)
.start();
```
Could not find an issue on this at the time of writing.
Tests are not affected by this change.
Consider showing a warning to the user when a store is …

docs(aurelia/state): Fix error in aurelia/state setup docs.

---

docs/user-docs/getting-to-know-aurelia/custom-attributes.md

Per Discord discussions:
https://discord.com/channels/448698263508615178/448699158052864001/1005682444839682100
```typescript
import { customAttribute, inject, INode } from 'aurelia';
@inject(Element)
@customAttribute('my-cool-attr')
export class MyCoolAttribute {
private value: string;
constructor(@INode private element: Element) {
console.log('Attaching to an element'); // ✅
}
public bound() {
console.log('Initial value set', this.value) // ✅;
}
public valueChanged(): void {
console.log('Value just changed', this.value) // ❌;
}
}
```
I had this simple example of a custom attribute, but "valueChanged" was not being called when the binding was updated.
@Sayan751 suggested trying `@bindable()` which fixed the issue and so I was encouraged to update docs. When I've come through to update …

docs(attributes): update docs to include explicit bindable call

---

packages-tooling/plugin-conventions/src/hmr.ts

When using dev app build one must configure aliases to include dev Aurelia build for HMR to work. This add checks for original and mangled private method name to avoid this requirement.

Check full and mangled method names in HMR

---

packages/__tests__/3-runtime-html/event-manager.spec.ts
packages/__tests__/3-runtime-html/target-observers.spec.ts
packages/__tests__/3-runtime-html/template-compiler.harmony.spec.ts
packages/__tests__/import-env-vars.js
packages/__tests__/importmap.js
packages/__tests__/karma.conf.cjs
packages/__tests__/router-lite/.eslintrc.cjs
packages/__tests__/router-lite/hook-tests.spec.ts
packages/__tests__/util.ts

Tests related to focus/blur states often fail on firefox and require manual reruns. Just disable them and let Chrome handle it.

build(tests): make test runs on firefox less brittle

---

packages/__tests__/3-runtime-html/repeater-if-else.spec.ts
packages/runtime-html/src/aurelia.ts
packages/runtime-html/src/plugins/dialog/dialog-service.ts
packages/runtime-html/src/resources/custom-elements/au-render.ts
packages/runtime-html/src/resources/template-controllers/portal.ts
packages/runtime-html/src/resources/template-controllers/promise.ts
packages/runtime-html/src/resources/template-controllers/repeat.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/watch.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/connectable.ts

Currently, the repeater does not unsubscribe the collection when getting detached, resulting in double work when:
1. it becomes attached again and
2. the collection getting updated at the same time
The template for the 2 above conditions to happen at the same time looks like this:
```html
<div if.bind="items.length">
<p repeat.for="i of items">...
```
Reproduction:
1. start with an array of 1 item
2. remove the only item in the array, this will trigger detaching lifecycle on the repeat without unsubscribing to the array `items`
3. add a new item into the array `items` -> 💥
This PR fixes this.
Thanks to @bravius for reporting this issue in #1119

fix(repeater): re attaching when using the same array with if

---

packages/runtime-html/src/resources/template-controllers/repeat.ts

In a previous PR #1511 the fix for repeater issues when unbinding wasn't as optimal as it should, since there' still some redundant checks in the collection observer subscription code. Tweak that. Thanks @fkleuver for pointing it out.

refactor(repeat): unbind perf

---

packages-tooling/plugin-conventions/src/hmr.ts

Fix for "TS7006: Parameter 'data' implicitly has an 'any' type. " on every compontent.ts file when using HMR with typescript in strict mode

fix(hmr): add ts-ignore to fix hmr in strict TS

---

packages/__tests__/router-lite/_shared/create-fixture.ts
packages/__tests__/router-lite/resources/href.spec.ts
packages/__tests__/router-lite/resources/load.spec.ts
packages/router-lite/src/resources/href.ts
packages/router-lite/src/resources/load.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/viewport-agent.ts

This fixes the issue reported here: https://discourse.aurelia.io/t/the-aurelia-2-book/4874
This support navigating to the routes defined in the ancestor view-models. The support for `../`-prefix was partially present, but was not tested. In this the tests are added and the bug is also fixed. That is, the following use-case is now supported:
```ts
@customElement({ 
name: 'pro-duct', 
template: `product \${id} <a load="../products"></a>`  //<-- navigation to the route defined in parent context
})
class Product {
private id: unknown;
public canLoad(params: Params, _next: RouteNode, _current: RouteNode): boolean {
this.id = params.id;
return true;
}
}
@customElement({ name: 'pro-ducts', template: `<a load="../product/1"></a><a load="../product/2"></a> products` })
class Products { }
@route({ …
```

fix(router-lite): navigation to routes configured in ancestor nodes

---

packages/__tests__/router-lite/router-containerless.spec.ts
packages/runtime-html/src/templating/controller.ts

In a previous refactoring, the job of turning a host element into render location was moved from controller to compiler (marking) and renderer (replacing) so that the target can be registered & managed properly with dom fragment. That refactoring broke cases where the containerless rendering is done not from CE renderer.
This PR fixes this.
closes #1513

fix(containerless): ensure host of dynamically created containerless comp is removed

---

docs/user-docs/developer-guides/validation/displaying-errors.md
packages/__tests__/validation-html/subscribers/validation-result-presenter-service.spec.ts
packages/validation-html/src/subscribers/validation-result-presenter-service.ts

This PR fixes the issue reported by @Vheissu that the `ValidationResultPresenterService` now needs a ctor argument. This was missing in the docs. Also, it slightly compromises the previous ease of use. As the ctor arg cannot be avoided for the presenter service, this PR adds an injection symbol for the presenter service that facilitates transient injection of the presenter service. The docs and tests have been updated to reflect the change.

fix(validation-html): transient injection symbol for presenter service

---

docs/user-docs/reference/examples/binding-and-templating/README.md
packages/__tests__/2-runtime/ast.spec.ts
packages/__tests__/2-runtime/expression-parser.spec.ts
packages/__tests__/3-runtime-html/arrow-fn.spec.ts
packages/runtime/src/binding/ast.ts
packages/runtime/src/binding/expression-parser.ts
packages/runtime/src/index.ts
packages/testing/src/startup.ts
packages/validation/src/ast-serialization.ts

One of the commonly requested features in Aurelia is the ability to use arrow function in templates. It can be handy in many ways: filtering items for a repeat, passing a callback to a child component, handling an event, etc... Additionally, it is a good way to avoid having to create a view model to accommodate some code that can only be expressed via a function.
With the arrow function, the following code
```html
<my-input change.call="updateValue($event)">
<my-button click.trigger="handleClick">
```
can be rewritten with simpler, closer to JavaScript syntax:
```html
<my-input change.bind="v => updateValue(v)">
<my-button click.trigger="e => handleClick(e)">
```
It also enables us to have an easier time dealing with ad-hoc collection filtering/sorting:
```html
<div repeat.for="i of list …
```

implement arrow function syntax

---

packages/__e2e__/router/src/app.css
packages/__e2e__/router/src/app.html
packages/__tests__/router/router.spec.ts
packages/router/src/found-route.ts
packages/router/src/instructions/routing-instruction.ts
packages/router/src/interfaces.ts
packages/router/src/resources/load.ts
packages/router/src/routing-scope.ts

This PR makes it possible to use multiple bindable properties for the `load` attribute as well as adds configured route `id` as an option to select configured route with. So given a configured route
```ts
{ id: 'thing-params', path: 'thing/:id', component: MyThing, title: 'The Thing!' },
```
it will be possible to use the following options to `load`
```html
<a load="thing/123">
<a load="id: thing-params; parameters.bind: { id: 123 };">
<a load.bind="{ id: 'thing-params', parameters: { id: 123 } }">
```
- Make tests for the new options

feat(router): multiple bindable props for load attribute

---

packages/router/src/instructions/routing-instruction.ts
packages/router/src/resources/load.ts

This PR adds a compare route step to the active link check, removing the need to resolve instructions in `load`, as well as addresses some feedback on https://github.com/aurelia/aurelia/pull/1554.

refactor(router): add route compare to active check

---

packages/__tests__/3-runtime-html/arrow-fn.spec.ts
packages/__tests__/3-runtime-html/listener.spec.ts
packages/aurelia/src/index.ts
packages/runtime-html/src/binding/listener.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/renderer.ts

In a previous PR, an option was introduced to make listener able to accept function. Though it came with a cumbersome configuration. Remove the need for configuration and let the event handler call function by default, if the expression returns a function.
Thanks @jwx @brandonseydel for the suggestion

refactor: always handle event handler as fn

---

docs/engineering-notes/router-architecture-notes.md
packages/__tests__/router-lite/_shared/create-fixture.ts
packages/__tests__/router-lite/resources/href.spec.ts
packages/__tests__/router-lite/resources/load.spec.ts
packages/router-lite/src/configuration.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/resources/href.ts
packages/router-lite/src/route-expression.ts
packages/router-lite/src/router.ts
packages/router-lite/src/viewport-agent.ts

The configuration options supported was supported to be a function
that starts the Router. This was undocumented, also probably contrived.
This is removed, and the options are initialized in the `hydrated` phase
rather than the `activated` phase which was the case previously.
This hindered the availability of the customization of options to the
CAs at the right time.
Note that this is a BREAKING CHANGE, although it might be relatively
low-impacting, as the "feature" was undocumented in the first place.
Additionally, it contains some residual cleanups from the PR #1569 as pointed out by @bigopon.

fix(router-lite): handling hash in load, href CAs

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/index.ts
packages/router-lite/src/route-definition.ts
packages/router-lite/src/route.ts
packages/router-lite/src/router.ts
packages/router-lite/src/viewport-agent.ts

This PR drops the `sameUrlStrategy` router-configuration option in favour of consolidating the behaviour to the `transitionPlan` route-configuration option. This also enables the inheritance of the `transitionPlan` from the parent configuration. See the tests for example usage.

refactor(router-lite): same URL handling

---

packages/__tests__/router-lite/_shared/create-fixture.ts
packages/__tests__/router-lite/resources/href.spec.ts
packages/__tests__/router-lite/resources/load.spec.ts
packages/__tests__/router-lite/router-containerless.spec.ts
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/router.ts

Previously, the history state was changed after the navigation end event is raised. Any subscriber listening to the navigation-end event might end up with wrong history state. This PR makes the history adjustment before the navigation-end event is raised.

fix(router-lite): history state change timing

---

examples/fractals-tree/package.json
examples/fractals-tree/rollup.config.js
packages/__e2e__/playwright-util.js
packages/__tests__/3-runtime-html/portal.spec.tsx
packages/mangle-namecache.js
packages/runtime-html/src/resources/template-controllers/portal.ts
packages/runtime-html/src/utilities-dom.ts
packages/testing/src/startup.ts
scripts/dev.ts

Add `position` bindable so that apps can specify where view can be moved to, similar to `insertAdjacentElement` API. There are 4 positions:
- beforebegin
- afterbegin
- beforeend
- afterend
illustrated:
```html
// beforebegin
<div>
// afterbegin
...
// beforeend
</div>
// afterend
```
Usage:
```html
<div portal="target: meta[content=charset]; position: beforebegin"></div>
```
Resolves #1527

feat(portal): ability to specify insert position

---

packages/runtime-html/src/bindable.ts

I tried to run au2 side-by-side with au1 and got an error because the au1 Reflect polyfill is incomplete (and au1 has to run first in this scenario). After applying the changes in this PR in the dist file by hand first, I verified that au2 seemingly has no problems running inside of an existing au1 app. That definitely helps with migration.
So for future reference we should make sure to use the `Metadata` api internally and avoid using the `Reflect` polyfill.
@bigopon

fix(runtime-html): remove direct dependency on Reflect polyfill

---

packages/__tests__/router-lite/route-recognizer.spec.ts
packages/route-recognizer/src/index.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route-tree.ts

This PR corrects the registration of residue routes. 
Till now, for every route `ro/ute`, an additional route `ro/ute/*RESIDUE` is added to the recognizer. The registration of this additional route is required to facilitate hierarchical (parent-child) route recognition.
However, it poses a problem when a route itself ends with a *-segment. In that case, there is technically no need for the additional route registration with a `*RESIDUE` segment at the end.  The assumption here is that a route ending with a *-segment has no child routes configured. Also, due to this extra registration, the recognition of routes was also unexpected. For example, when the following 2 routes are registered, `b/:1`, `b/:1/*2`, an attempt to recognize the path `b/1/2` resulted in the selection of the endpoint …

fix(route-recognizer): residue handling

---

package-lock.json
package.json
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/route-tree.ts

Fixed the case of fallback when an empty route is defined. Previously it was so that when recognizing the ce-name, without any configured route with the same path, the empty route was selected. It is however expected that the correct CE definition is selected nevertheless.
This commit fixes the issue by comparing the fallback with the residue. If both matched, then it is assumed that fallback is matched with the empty route and no reasonable route-recognition took place. In such case, we can fall back to resolving the route definition by ce-name.
Please refer the tests.

fix(router-lite): fallback with ce-name

---

packages/__tests__/router-lite/config-tests.spec.ts
packages/__tests__/router-lite/hook-tests.spec.ts
packages/__tests__/router-lite/resources/viewport.spec.ts
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/index.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/router.ts
packages/router-lite/src/viewport-agent.ts

Because the default value for the `default` bindable in the au-viewport is '', it allows loading the empty route by default. However, this results in a bit weird behavior, when there are sibling viewports with default value for the `default` property. In this case both the viewports load the empty route (assuming the empty route is configured). This commit allows binding null to the `default` property which indicates that the viewport must be ignored when free and no component should be loaded by default.
This commit additionally removes the resolution mode. This option only changes the lifecycle hook timings. In my opinion that is a very niche property, removal of which might not affect the mass in devland. On the other hand, keeping this configuration property alive, hindered the …

fix(router-lite/viewport): null default binding

---

packages/__tests__/router-lite/resources/viewport.spec.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/router.ts

This commit fixes the issue of not copying the viewports from child segment. For example a path `route1/param1@vp1` is parsed roughly into the following instruction.
```json5
{
component: 'route1',
viewport: '',
children: [
{
component: 'param1',
viewport: 'vp1'
}
]
}
```
Previously the viewport `vp1` was erroneously discarded.
This commit fixes that issue.

fix(router-lite): viewport adjustment

---

packages/__tests__/router-lite/resources/viewport.spec.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/viewport-agent.ts

This PR fixes the viewport name matching between a viewport request and a viewport agent.
There are new tests to make the utility of the changes clear.

fix(router-lite): viewport-request and viewport-agent viewport name matching

---

packages/router/src/endpoints/viewport-content.ts

Fixes a bug where components that may set loading = true would break the application.  The check should make sure that the load/unload hooks are actual methods.

fix(router): check to make sure hooks are valid

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/router.ts

This PR fixes the support for couple `Router#load` overloads.
- Viewport name with component class.
- Hierarchical viewport instruction with route-id as component.
- Promise as component for the load method. Typical use-case: `import('./view-model')`.

fix(router-lite): various overloads for the load method

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route-expression.ts

This PR fixes the `queryParams` and `fragment` propagation from the navigation options from the `IRouter#load` method.
```typescript
// prduces -> /home#awesome-possum?foo=bar
router.load(
'home',
{
queryParams: { foo: 'bar' },
fragment: 'awesome-possum'
}
);
```

fix(router-lite): queryParams and fragment propagation from nav option

---

packages/__tests__/router-lite/lifecycle-hooks.spec.ts
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/route-tree.ts

This closes #1654.
Additionally, it fixes: 
- The parameter support for `redirectTo`.
```typescript
@route({
routes: [
{ path: 'fizz/:bar', redirectTo: 'p2/:bar' },
{ path: 'p2/:id?', component: P2, title: 'P2' },
]
})
```
- The fragment (hash) is added to the end of the URL.

fix(router-lite): redirectTo URL update + parameter support

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/route-tree.ts

This fixes the following use case of `{ path: 'fizz/:foo/:bar', redirectTo: 'p2/:bar/:foo' }`. That is when `/foo/1/2` is attempted to be loaded, the user will be redirected to `/p2/2/1`. Previously, it was erroneously redirected to `/p2/1/2`.

fix(router-lite): redirectTo parameter remapping

---

packages/__tests__/2-runtime/ast.spec.ts
packages/runtime-html/src/observation/observation-utils.ts
packages/runtime/src/binding/ast.eval.ts

closes #1617
Keyed access in is wrongly consider noop atm, change it to proper value access.

fix(ast): correctly resolves access keyed on primitve

---

packages/__tests__/3-runtime-html/au-slot.spec.tsx
packages/runtime-html/src/resources/custom-elements/au-slot.ts

closes #1683
Currently a structure like this
```html
<template>
<parent>
<child>
</template>
```
Will have container hierarchy like this
```
container (app)
| - container (parent)
| - container (child)
```
This does not enable the injection of `Parent` into `Child` component, and is not matching the behavior of v1.
This PR add a layer of container wrapping the container of child so that the hierarchy will look like this
```
container (app)
| - container (parent)
| - container (slot) // this container is aware of container (parent) and can register the instance for injection
| - (child)
```
Closes #1683 
cc @fkleuver @Sayan751

fix(au-slot): register the right view model instance for injection

---

packages/__tests__/3-runtime-html/binding-command.class.spec.ts
packages/__tests__/3-runtime-html/styles.integration.spec.ts
packages/__tests__/3-runtime-html/styles.spec.ts
packages/runtime-html/src/dom.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/templating/styles.ts
packages/testing/src/startup.ts

The bug described in the linked issue is caused by 2 issues:
- css module always override all the classes on an element without considering other sources of class names.
- class binding command doesn't take into account whether any mapping is available
The fix is to make:
- css module work by toggling class the same way with normal class binding
- class binding aware of existing mapping declared inside a custom element
cc @brandonseydel 
closes #1684

fix(css-modules): class cmd css module

---

.circleci/config.yml

We no longer need to publish dev tag to npm frequently, put an approval task in front of the publish dev job, so that we can choose when a new dev version go out.
cc @Sayan751 @fkleuver

chore(ci): add approval step for dev publish

---

docs/user-docs/developer-guides/migrating-to-aurelia-2/README.md
packages/__tests__/3-runtime-html/au-compose.spec.ts
packages/__tests__/compat-v1/au-compose.spec.ts
packages/compat-v1/src/compat-au-compose.ts
packages/compat-v1/src/compat-form.ts
packages/compat-v1/src/index.ts
packages/compat-v1/src/utilities.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts

enhance doc, partially address #1695
- Rename bindable properties on `<au-compose>`:
- viewModel -> component
- view -> template
- Add a function to re-enable the v1 naming for migration:
All in one:
```ts
import { compatRegistration } from '@aurelia/compat-v1';
Aurelia.register(compatRegistration)
...
```
or compose specific:
```ts
import { enableComposeCompat } from '@aurelia/compat-v1';
...
enableComposeCompat();
```
- Add breaking change doc for `<compose/>` and links to the new composition doc.
Thanks @ekzobrain 
cc @Sayan751 @fkleuver

refactor(compose): rename props and add compat layer

---

.circleci/config.yml
packages/__tests__/.eslintrc.cjs
packages/__tests__/1-kernel/di.integration.spec.ts
packages/__tests__/2-runtime/property-observation.spec.ts
packages/__tests__/karma.conf.cjs
packages/__tests__/router/smoke-tests.spec.ts
packages/__tests__/router/viewport-content.spec.ts
packages/__tests__/turbo.json
packages/runtime-html/src/renderer.ts
packages/runtime/src/observation/array-observer.ts
packages/runtime/src/observation/map-observer.ts
packages/runtime/src/observation/set-observer.ts

We often do this
```html
// in real app it's some variable that has number values
<div height.style="200">
```
and forget that `200` is not a valid value for height, it needs to come with a unit. Add a warning in dev mode so that folks can be aware of what's happening.
Also cleanup some test code & lint issues.
Thanks @jsobell

feat(style): add warning messages when binding number to ambiguous properties

---

packages/__tests__/2-runtime/proxy-observable.spec.ts
packages/__tests__/3-runtime-html/checked-observer.spec.ts
packages/__tests__/3-runtime-html/custom-elements.decorator.spec.ts
packages/__tests__/3-runtime-html/template-compiler.hooks.spec.ts
packages/__tests__/3-runtime-html/template-compiler.spec.ts
packages/__tests__/i18n/i18n.spec.ts
packages/i18n/src/i18n.ts
packages/runtime/src/index.ts
packages/runtime/src/observation/proxy-decorators.ts
packages/runtime/src/observation/proxy-observation.ts

feat(i18n): do not wrap i18next
resolves #1614
When there's a large 3rd party library object, together with many of its internal properties, being part of the dependencies of a getter observer, it can cause a lot of change triggers because whatever the internal working way of the 3rd party lib.
Add a decorator `@nowrap` so that we can have a way to draw a boundary where we don't want to go into to collect dependencies.
The decorator is also allowed to work with inheritance, means a property decorated with `@nowrap` on the parent class will also have the same effect in the child class.
@brandonseydel @Sayan751 @fkleuver

feat(proxy): add nowrap decorator

---

docs/user-docs/aurelia-packages/state.md
packages/__tests__/state/state.spec.ts
packages/state/src/action-handler.ts
packages/state/src/configuration.ts
packages/state/src/index.ts
packages/state/src/interfaces.ts
packages/state/src/state-dispatch-binding.ts
packages/state/src/state-templating.ts
packages/state/src/state-utilities.ts
packages/state/src/store.ts

resolves #1608
At the moment, actions and action handlers are in the form of type & parameters spread across multiple parameters/shapes. This creates difficulties when applications want to enforce/enable typings & intellisense on dispatch call. The reason for the current way is because we tried to stay close to v1 store, but now it's no longer necessary.
Change action handler to accept only 2 parameters: `state` and `action`. `action` can be any value now, and it's entirely up to action handler to deal with that. `dispatch` call also got modified so that it can be dispatched with any action, letting applications dictate the convention they want.
Thanks @rmja

refactor(state): action to be comes a single value

---

packages/__tests__/2-runtime/proxy-observable.spec.ts
packages/runtime/src/observation/proxy-observation.ts

If you pass in a property that's part of a computed observation structure into another class, the value is already wrapped in a proxy before that property is observed in the new class. If that new class then also uses computed observation, that property will be wrapped in a proxy again, causing a "proxy within a proxy". This can repeat itself endlessly, causing all sorts of issues.
Simply adding the proxy itself as the key to the `proxyMap` will solve that problem at least as far as the issue in our app is concerned.
cc @bigopon

fix(proxy-observation): prevent proxies from being wrapped in proxies again

---

docs/user-docs/router-lite/configuring-routes.md
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/component-agent.ts
packages/router-lite/src/index.ts
packages/router-lite/src/options.ts
packages/router-lite/src/resources/viewport.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/route.ts
packages/router-lite/src/validation.ts
packages/router-lite/src/viewport-agent.ts

feat(router-lite): non-string support for fallback

---

docs/user-docs/router-lite/navigating.md
docs/user-docs/router-lite/router-configuration.md
packages/__tests__/router-lite/_shared/create-fixture.ts
packages/__tests__/router-lite/resources/load.spec.ts
packages/router-lite/src/options.ts
packages/router-lite/src/resources/href.ts
packages/router-lite/src/resources/load.ts

feat(router-lite): activeClass router configuration

---

docs/user-docs/router-lite/navigating.md
packages/__tests__/router-lite/resources/load.spec.ts
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/resources/load.ts
packages/router-lite/src/router.ts

This commit extends the support for ../ prefix. Previously, it was only available to the string instruction. This commit adds support for `{ component: '../../route', params: { what: 'ever' } }`.
This closes https://github.com/aurelia/aurelia/issues/1728

feat(router-lite): extended support for ../ prefix

---

docs/user-docs/components/shadow-dom-and-slots.md
docs/user-docs/templates/binding-behaviors.md
packages/__tests__/3-runtime-html/binding-commands.throttle-debounce.spec.ts
packages/runtime-html/src/binding/binding-utils.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/binding-behaviors/debounce.ts
packages/runtime-html/src/resources/binding-behaviors/signals.ts
packages/runtime-html/src/resources/binding-behaviors/throttle.ts
packages/runtime-html/src/templating/children.ts
packages/runtime-html/src/templating/controller.projection.ts
packages/runtime-html/src/utilities.ts
packages/runtime/src/observation.ts
packages/state/src/state-binding-behavior.ts

Support a valid use case described in #1145 , where it's desirable to flush throttled/debounced update upon some condition.
- `throttle` & `debounce` now accept a 2nd parameter with type `string | string[]` as signals, to listen to and flush whenever there's a dispatch. Example:
```html
<input value.bind="value & throttle :200 :`finishTyping`" blur.trigger="signaler.dispatchSignal('finishTyping')">
<input value.bind="value & throttle :200 :[`finishTyping`, `newUpdate`]">
```
Resolves #1145
Thanks @avrahamcool

feat(debounce-throttle): flush via signals

---

packages/__tests__/router-lite/smoke-tests.spec.ts
packages/router-lite/src/configuration.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/router.ts

This PR adds alias registrations for the following. Thus, one from the pair can be used interchangeably as injection symbol.
- `IRouter` and `Router`
- `IRouteContext` and `RouteContext`
- `IRouterOptions` and `RouterOptions`
closes #1740

refactor(router-lite): alias registrations

---

docs/user-docs/getting-to-know-aurelia/observation/effect-observation.md
packages/__tests__/2-runtime/computed-observer.spec.ts
packages/__tests__/3-runtime-html/computed-observer.spec.ts
packages/__tests__/3-runtime-html/effect.spec.ts
packages/__tests__/3-runtime-html/observer-locator.spec.ts
packages/runtime/src/index.ts
packages/runtime/src/observation.ts
packages/runtime/src/observation/computed-observer.ts
packages/runtime/src/observation/observation.ts
packages/runtime/src/observation/observer-locator.ts

Resolves #1747 
At the moment, most of our observer locator are still around the interface `.getObserver(object, key)`. Sometimes this doesnt suffice, as there may be the need to observe more than 1 key at once. One can resolve to a getter property and observe that property, but it's cumbersome and not always appropriate/doable.
This PR adds a new overload on the `getObserver` of the observer locator, where it allows the 2nd parameter to be a function, treated as a getter, to be passed in. When a function is passed in the 2nd parameter, a different kind of observer that can deal with getter observation will be used instead.
This API also makes it simpler to create higher level API on top, so add a new API `watch` on `IObservation` for a common case:
```ts
observation.watch(obj, o => …
```

feat(observer-locator): ability to create getter based observer

---

packages/router/src/instructions/instruction-component.ts

At the moment, the router is doing a container traversal to get a component instance, when a component name is used in an instruction. This is not an intended behavior, and should be removed.
Adding a warning so that apps can have some time to check/avoid this issue. It'll be removed in a near future release.
cc @jwx

refactor(router): add warning for unsupported behavior

---

package-lock.json
package.json
packages/__tests__/2-runtime/computed-observer.spec.ts
packages/__tests__/3-runtime-html/repeater.unit.spec.ts
packages/__tests__/package.json
packages/kernel/src/api-test.ts
packages/kernel/src/di.container.ts
packages/kernel/src/di.ts
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/observation/class-attribute-accessor.ts
packages/runtime-html/src/observation/observation-utils.ts
packages/runtime/src/index.ts
packages/runtime/src/observation.ts
packages/runtime/src/observation/array-observer.ts
packages/runtime/src/observation/collection-length-observer.ts
packages/runtime/src/observation/dirty-checker.ts
packages/runtime/src/observation/map-observer.ts
packages/runtime/src/observation/observable.ts
packages/runtime/src/observation/set-observer.ts
packages/runtime/src/observation/subscriber-collection.ts

Some cleanup in between features. Part of the process of decoupling our default implementations from the corresponding interfaces.
@Sayan751 I've moved all the `test*` functions to a separate file for doing the API test. Thanks for the discussion in the other PR.

refactor: cleanup up unused code & decouple interface from default impl

---

packages/dialog/src/plugins/dialog/dialog-service.ts
packages/kernel/src/functions.ts
packages/kernel/src/index.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/router.ts
packages/router-lite/src/viewport-agent.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/resources/template-controllers/promise.ts
packages/runtime-html/src/resources/template-controllers/switch.ts
packages/runtime-html/src/templating/controller.ts

BREAKING CHANGE: rename
resolveAll is confusing when we have onResolve and resolve

refactor: rename resolveAll -> onResolveAll

---

packages/__tests__/1-kernel/di.get.spec.ts
packages/kernel/src/di.container.ts
packages/kernel/src/di.ts

resolves #1765
At the moment, `@newInstanceOf` doesn't work with interface because it expects an implementation. This creates an inconsistency where all other resolvers/APIs of the container works well with both interface and implementation. Add the ability to support `@newInstanceOf`/`@newInstanceForScope` for interface.
Thanks @mt-mshorrosh.

feat(di): ability to use newInstance() with interface

---

packages/addons/package.json
packages/aurelia/package.json
packages/compat-v1/package.json
packages/dialog/package.json
packages/fetch-client/package.json
packages/i18n/package.json
packages/kernel/package.json
packages/metadata/package.json
packages/platform-browser/package.json
packages/platform/package.json
packages/route-recognizer/package.json
packages/router-html/package.json
packages/router-lite/package.json
packages/router/package.json
packages/runtime-html/package.json
packages/runtime/package.json
packages/state/package.json
packages/store-v1/package.json
packages/testing/package.json
packages/ui-virtualization/package.json
packages/validation-html/package.json
packages/validation-i18n/package.json
packages/validation/package.json
packages/web-components/package.json

Add a "development" condition in exports to support some platforms like https://esm.sh/#docs
Those platforms that do support it will be able to pick the right dev dist.

feat(build): add a development entry point

---

packages/__tests__/router-lite/ast.spec.ts
packages/__tests__/router-lite/events.spec.ts
packages/__tests__/router-lite/location-manager.spec.ts
packages/__tests__/router-lite/resources/load.spec.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/resources/load.ts
packages/router-lite/src/router.ts
packages/router-lite/src/viewport-agent.ts

fix(router-lite): URL generation in child component

---

packages/__tests__/router-lite/resources/load.spec.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/viewport-agent.ts

This commit makes the URL hash compatible with Au1. This has been reported here: https://discourse.aurelia.io/t/url-fragment-hash-difference-between-router-lite-and-router/5176.
Additionally, it also addresses the review comments from #1778

fix(router-lite): hash compatibility with v1

---

docs/user-docs/components/components.md
docs/user-docs/components/shadow-dom-and-slots.md
docs/user-docs/templates/conditional-rendering.md
docs/user-docs/templates/local-templates.md
packages/__tests__/3-runtime-html/promise.spec.ts
packages/__tests__/3-runtime-html/spread.spec.ts
packages/__tests__/3-runtime-html/switch.spec.ts
packages/__tests__/3-runtime-html/template-compiler.local-templates.spec.ts
packages/__tests__/3-runtime-html/template-compiler.spec.ts
packages/compat-v1/src/compat-call.ts
packages/i18n/src/t/translation-parameters-renderer.ts
packages/i18n/src/t/translation-renderer.ts
packages/runtime-html/src/bindable.ts
packages/runtime-html/src/compiler/template-compiler.ts
packages/runtime-html/src/resources/binding-command.ts
packages/state/src/state-templating.ts
packages/ui-virtualization/src/virtual-repeat.ts

Closes #1091.
This is a BREAKING CHANGE, especially for the devs using local templates and the Bindable API directly.
With this change, the current code needs to be migrated as follows.
```diff
<template as-custom-element="foo-bar">
-   <bindable property="status"></bindable>
+   <bindable name="status"></bindable>
</template>
```
```diff
// Bindable API
BindableDefinition.create({
-  proerty: 'foo',
+  name: 'foo',
})
@bindable({
-  proerty: 'foo',
+  name: 'foo',
})
```

refactor: bindable property -> name

---

docs/user-docs/getting-to-know-aurelia/dependency-injection-di/README.md

Also noted that `cachedCallback` and `defer` are missing docs too.

chore(docs): update di docs for Registration.aliasTo

---

packages/__tests__/3-runtime-html/arrow-fn.spec.ts
packages/__tests__/3-runtime-html/au-slot.spec.tsx
packages/__tests__/3-runtime-html/interpolation.spec.ts
packages/__tests__/3-runtime-html/promise.spec.ts
packages/__tests__/i18n/t/translation-integration.spec.ts
packages/__tests__/router-lite/smoke-tests.spec.ts
packages/__tests__/turbo.json
packages/runtime-html/src/binding/attribute.ts
packages/runtime-html/src/binding/content-binding.ts
packages/runtime-html/src/binding/let-binding.ts
packages/runtime-html/src/binding/listener-binding.ts
packages/runtime-html/src/binding/property-binding.ts
packages/runtime-html/src/binding/ref-binding.ts
packages/runtime-html/src/binding/spread-binding.ts
packages/runtime-html/src/renderer.ts
scripts/dev.ts

Currently all bindings are evaluating expressions in strict mode, and have proved to be working fine for applications migrating from v1. Text binding (content binding), however, was not using this strict by default mode as there could be some bug regards to how null/undefined are handled.
This exception creates a discrepancy that is hard to explain, also there's not a lot of benefits doing this. Remove this behavior.
This open the way for us to remove non-strict mode in expression evaluation, as optional syntaxes are already supported. Though this will be another follow up PR.
Closes #1769 #1798

refactor(text-binding): always evaluate expressions in strict mode

---

packages/__tests__/3-runtime-html/au-slot.spec.tsx
packages/kernel/src/di.container.ts
packages/runtime-html/src/resources/custom-elements/au-slot.ts
packages/runtime/src/binding/ast.eval.ts

Supersedes #1799
Closes #
Currently inheriting resources from parent container doesn't register right resolvers. This PR fixes this. 
Thanks @ekzobrain

fix(au-slot): correctly prepare resources for slotted view

---

package-lock.json
package.json
packages/__tests__/src/router-lite/smoke-tests.spec.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/router.ts

fix(router-lite): excluded redirectTo from nav-model

---

.vscode/launch.json
packages/__tests__/src/router-lite/lifecycle-hooks.spec.ts
packages/__tests__/src/router-lite/resources/load.spec.ts
packages/__tests__/src/router-lite/smoke-tests.spec.ts
packages/router-lite/src/resources/viewport.ts
packages/router-lite/src/route-tree.ts
packages/router-lite/src/route.ts
packages/router-lite/src/viewport-agent.ts

The previous strategy of transition plan selection did not involve checking the parameters. If the parameters are the same, then the transition plan must be `none` in order to ensure that the component is not deactivated. 
Closes #1789.
Update the docs and demos. Need a new published version for that. Hence, those changes could not be included in this PR.

fix(router-lite): transition plan selection

---

packages/__tests__/src/i18n/t/translation-integration.spec.ts
packages/i18n/src/t/translation-binding.ts

This PR fixes the following issue:
```html
<my-el my-value="does not work" t="[my-value]displayTextTest"></my-el>
<my-el my-value="works" t="[myValue]displayTextTest"></my-el>
```
Reproduction: https://stackblitz.com/edit/translating-bindables?file=src%2Fmy-app.ts

fix(i18n): translating camelCased bindables

---

packages/__tests__/src/validation/rule-provider.spec.ts
packages/validation/src/rule-provider.ts

- This supports instrumentation code from @jsdevtools/coverage-istanbul-loader.
- Additionally, made a minor change where `@IValidationRules#off()` is allowed to be called for an object without any defined rules.
Applied the fix for the au1 issue: https://github.com/aurelia/validation/issues/571

fix(validation): property accessor ignore instrumenter

---

packages/runtime-html/src/compiler/attribute-mapper.ts

Add mapping support for popover api, as the attributes and properties are not similar
| attribute | property |
| - | - |
| popover | popover |
| popovertarget | popoverTargetElement |
| popovertargetaction | popoverTargetAction |
Closes #1832

feat(mapping): add mapping for popover apis

---

docs/user-docs/templates/binding-behaviors.md

The binding behavior docs were lacking in the binding behaviors department.

feat(docs): update binding behaviors with more custom examples

---

packages/__tests__/src/3-runtime-html/input.spec.ts
packages/runtime-html/src/compiler/attribute-mapper.ts
packages/runtime-html/src/observation/observer-locator.ts
packages/testing/src/startup.ts

in a previous PR, mapping was used so properties are used instead of attr. But attr is more flexible and less restrictive than properties for popover API, so change it. Add tests.

fix(popover): properly set attrs and add tests

---

packages/addons/package.json
packages/aurelia/package.json
packages/compat-v1/package.json
packages/dialog/package.json
packages/fetch-client/package.json
packages/i18n/package.json
packages/kernel/package.json
packages/metadata/package.json
packages/platform-browser/package.json
packages/platform/package.json
packages/route-recognizer/package.json
packages/router-html/package.json
packages/router-lite/package.json
packages/router/package.json
packages/runtime-html/package.json
packages/runtime/package.json
packages/state/package.json
packages/store-v1/package.json
packages/testing/package.json
packages/ui-virtualization/package.json
packages/validation-html/package.json
packages/validation-i18n/package.json
packages/validation/package.json
packages/web-components/package.json

This adds a "./development" subpath to all packages under "/packages" so that dev builds can be directly imported in nodejs without using a bundler:
```js
import { ... } from "@aurelia/runtime/development";
```
+ #1856

Add development subpath to package exports (#1856)

---

packages/__e2e__/playwright-util.js
packages/__tests__/src/router-lite/resources/load.spec.ts
packages/__tests__/src/router-lite/smoke-tests.spec.ts
packages/router-lite/src/configuration.ts
packages/router-lite/src/util.ts

fix(router-lite): Router injection and ignoring null/undefined values for query parameters

---

packages/__tests__/src/2-runtime/expression-parser.spec.ts
packages/__tests__/src/compat-v1/call.spec.ts
packages/compat-v1/src/compat-call.ts
packages/runtime/src/binding/expression-parser.ts

Removed superfluous usage of `ExpressionType.IsProperty`.
This is related to #1736.

chore(compat): cleanup call binding command

---

packages/__tests__/src/3-runtime-html/template-compiler.ce_and_surrogate.spec.ts
packages/runtime-html/src/compiler/template-element-factory.ts

This PR fixes the template wrapping for following templates:
```html
before
<template></template>
after
```
For this template, only the `template` element is considered, and the rest is ignored. This PR ensures that the whole template is wrapped with a `template` element.

fix(runtime-html): template wrapping 

---

packages/__e2e__/router/src/app.html
packages/__e2e__/router/src/router-configured.spec.ts
packages/__tests__/src/router/router.spec.ts
packages/router/src/router.ts

When a user used the browser's "back" button, the root ("/") default page was not correctly reloaded.
Resolves #1812.
In the current code (without this PR), all routing instructions are always prepended with `-` (`updateNavigation`).
The issue is due to a simple fact: `-` + ` ` *(empty)* equals `-`. And `-` *(minus)* is used to **clear** the current path/page. Thus, when we navigate to `/`, then to another page, the root page is lost and replaced by `-`.
My current fix simply checks whether the instruction is empty, and if so, it prevent the clear instruction to be added.
- Added new e2e tests for this specific case.
- Updated the existing tests to reflect a more realistic navigation flow.

fix(router): store root/default page instruction correctly

---

packages/__tests__/src/validation-html/validate-binding-behavior.spec.ts
packages/validation-html/src/validation-controller.ts
packages/validation/src/validator.ts

This PR fixes the issue where a validate instruction with tags is used to validate the bindings. So far, such tags are ignored while collecting the rules from all the bindings. That results in validating all the bindings, irrespective of the tags provided with the instruction. This PR fixes that issue.

fix(validation): evaluation of tagged rules from bindings

---

docs/user-docs/developer-guides/migrating-to-aurelia-2/README.md

Adding a `.call` binding will result is the following error:
> The ".call" binding command has been removed in v2. If you want to pass a callback that preserves the context of the function call, you can use lambda instead. Refer to lambda expression doc for more details.
Hence, I think it makes sense to remove it from the migrating to Aurelia 2 section

Removed Call binding (some-prop.call="...") in documentation

---

.circleci/config.yml
packages/__tests__/src/3-runtime-html/portal.spec.tsx
packages/runtime-html/src/resources/template-controllers/portal.ts

Currently `Portal` only move the markers around but never remove them when deactivated (like inside an if view) causing left over comments in some nodes. This PR fixes this.
close #1861

fix(portal): remove target marker when deactivated

---

examples/helloworld/package.json
packages/__tests__/src/3-runtime-html/au-slot.slotted.spec.ts
packages/__tests__/src/3-runtime-html/au-slot.spec.tsx
packages/kernel/src/di.container.ts
packages/kernel/src/di.ts
packages/runtime-html/src/resources/custom-elements/au-slot.ts

Currently in nested projection, the container hierarchy does not have all information related to projector and projection context making it unable to resolve the right instances of projectors. This PR fix this.
Added a test based on reported case from related PR with slightly more complicated usage.
- close #1873
- close #1874

fix(au-slot): properly handle nested projection registration

---

docs/user-docs/developer-guides/cheat-sheet.md

Docs adjusted so that the hook names correspond to those of the router and router-lite

rename load() hook to loading() in docs

---

packages/__tests__/src/1-kernel/di.get.spec.ts
packages/__tests__/src/3-runtime-html/di-resolutions.spec.ts
packages/__tests__/src/fetch-client/fetch-client.spec.ts
packages/fetch-client/src/http-client.ts
packages/kernel/src/di.ts
packages/kernel/src/errors.ts
packages/testing/src/startup.ts

Currently the new client resolvers `newInstanceOf`/`newInstanceForScope` are automatically causing a resolver registered whenever they are used on a container with an unregister key. This will cause surprise when child container (from child ce for example) tries to inject the same key, as the actual resolver of the `newInstanceForScope` will be the 2nd resolver registered. Also resolve an issue with `newInstanceOf` + `IHttpClient`.

fix(di): new instance resolver

---

docs/user-docs/getting-to-know-aurelia/dynamic-composition.md
packages/__tests__/src/3-runtime-html/au-compose.spec.ts
packages/runtime-html/src/errors.ts
packages/runtime-html/src/resources/custom-elements/au-compose.ts
packages/testing/src/startup.ts

Adds the ability to understand string as element name to `<au-compose/>`, it'll throw in case of the name doesn't result in a registered element. All the following usages of `<au-compose>` will yield the same result:
```html
<au-compose component.bind="el" style="width: 20%;" v="aurelia"></au-compose>
<au-compose component="my-el" style="width: 20%;" v="aurelia"></au-compose>
```
For component classes:
```ts
class MyApp {
el = MyEl
}
class MyEl {
@bindable v
}
```
just as the direct usage of `<my-el>`:
```html
<my-el style="width: 20%;" v="aurelia"></my-el>
```
* When composing directly with a custom element constructor, the constructor does not need to be a dependency of the element that owns `<au-compose>`
* When composing with a custom element name, there must be either a locally or …

feat(au-compose): ability to compose string as element name

---

docs/user-docs/getting-to-know-aurelia/enhance.md
packages/__tests__/src/3-runtime-html/enhance.spec.ts
packages/__tests__/src/3-runtime-html/portal.spec.tsx
packages/__tests__/src/3-runtime-html/process-content.spec.ts
packages/__tests__/src/integration/app/startup.ts
packages/__tests__/src/router-lite/lifecycle-hooks.spec.ts
packages/__tests__/src/router/_shared/view-models.ts
packages/aurelia/src/index.ts
packages/kernel/src/di.container.ts
packages/kernel/src/di.ts
packages/rollup-utils.mjs
packages/runtime-html/src/api-test.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/aurelia.ts
packages/runtime-html/src/compiler/template-compiler.ts
packages/runtime-html/src/errors.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/resources/binding-behavior.ts
packages/runtime-html/src/resources/binding-command.ts
packages/runtime-html/src/resources/custom-attribute.ts
packages/runtime-html/src/resources/custom-element.ts
packages/runtime-html/src/resources/value-converter.ts
packages/runtime-html/src/templating/controller.ts
packages/tsconfig-build.json

In a PR awhile ago, the return value of the `enhance` call was changed from an `IAppRoot` to a controller for simplicity. This was necessary at the time because the app root created by enhance would override an existing app root on an Aurelia instance. This , however, resulted in the loss of the ability to call app tasks in the `.enhance` call.
This PR makes `.enhance` create an app root again, but this app root would not be used by the owning Aurelia instance.
Changes:
- BREAKING CHANGE: enhance results in an app root instance instead of a controller
- improve typings of `.enhance` & `IAppRoot` to auto infer component instance type
- script dist target changed from es2020 to es2021
- remove `.create` API on container
Resolves #1787 
cc @Sayan751 @Vheissu

feat(enhance): call app tasks with `.enhance` API

---

packages-tooling/rollup-utils.mjs
packages-tooling/vite-plugin/src/index.ts
packages-tooling/vite-plugin/tsconfig.json
packages/__tests__/src/1-kernel/di.invoke.spec.ts
packages/kernel/src/di.container.ts
packages/kernel/src/errors.ts
packages/kernel/src/functions.ts

Currently, when there is an error during the instantiation of a class, there is not enough information what went wrong. This is quite an issue once there are multiple changes being added in at once, like in a dependency upgrade.
Enhance the DEV mode error message by catching the dependency resolution error while instantiate, so that there will be more information for debugging.
1. for the following code with `inject`:
```ts
export class App {
static inject = [class Abc {
constructor() {
throw new Error('testing testing');
}
}]
}
```
The error messages logged will look like this:
2. For the following code with `resolve`:
```ts
export class App {
abc = resolve(class Abc {
constructor() {
throw new Error('testing testing');
}
});
}
```
The error messages logged will look like this
Resolves …

feat(dev): better DI error messages for instantiation

---

docs/user-docs/templates/repeats-and-list-rendering.md

The repeater had no docs for the `key` attribute inside the repeater, which is a feature devs should know for efficient repeater usage.

feat(docs): add key documentation for the repeater

---

packages/__tests__/src/3-runtime-html/au-slot.spec.tsx
packages/__tests__/src/3-runtime-html/template-compiler.au-slot.spec.ts
packages/__tests__/src/3-runtime-html/template-compiler.spec.ts
packages/runtime-html/src/compiler/template-compiler.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-element.ts
packages/runtime-html/src/resources/custom-elements/au-slot.ts
packages/runtime-html/src/templating/controller.projection.ts

- add a 3rd argument to the process content hook call to store compilation or pre-compilation information and pass it onto the custom element.
- remove the special treatment of `<au-slot>` from the default compiler, this helps cleanup oddness /coupling between the default compiler and the au-slot element. This also helps cleanup the whitespace inconsistency between normal projection and au-slot fallback (which is also a projection) templates.
- resolve #1204
cc @Sayan751

feat(process-content): ability to add information to a data object

---

docs/user-docs/templates/custom-attributes.md
packages/__tests__/src/3-runtime-html/custom-attributes.spec.ts
packages/runtime-html/src/dom.ts
packages/runtime-html/src/resources/custom-attribute.ts
packages/runtime-html/src/templating/controller.ts

Part of the improvement in v2 compared to v1, where attribute and elements are both participating in the container hierarchy and causing resolver shadowing/issues with container resolution, is that only element participates in the container hierarchy.
This, however, makes finding/injecting custom attribute in a group of attributes a challenge. This is a valid need, since often times that custom attributes are developed in grouped, as discussed in #660 or https://discourse.aurelia.io/t/au2-access-parent-component-viewmodel-in-a-clean-way/5378/5
This PR adds a new utility `closest` in `CustomAttribute`, to enable walking the DOM and finding a custom attribute controller via name or constructor, like the following example:
```html
<div foo="1">
<div bar="2">
</div>
</div>
```
```ts
import { …
```

feat(custom-attribute): ability to find closest attr by name or ctor

---

docs/user-docs/developer-guides/migrating-to-aurelia-2/README.md
packages/__tests__/src/3-runtime-html/custom-elements.spec.ts
packages/aurelia/src/index.ts
packages/compat-v1/src/index.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/aurelia.ts
packages/testing/src/startup.ts
packages/testing/src/test-context.ts

Currently, form actionless submission is a part of the compat package, though it's not necessarily most useful there. Move it to be part of the main application via config `allowActionlessForm`, so that the submit event on form without an `action` attribute will be called `preventDefault()`. This is to avoid reloading the whole page, which is 99.99% of the times not wanted in an SPA.
This behavior can be configured like the following examples:
```ts
Aurelia.app({
host: ...,
component: ...,
allowActionlessForm: true, // <-- this will reload page by default
})
// or
Aurelia.register(AppTask.creating(IAppRoot, root => root.config.allowActionlessForm = true));
```
BREAKING CHANGE:
- Move actionless form submit prevention from compat to application config, though this behavior is the same with …

fix(form): prevent actionless submission

---

packages-tooling/vite-plugin/src/index.ts

To make shadow dom option work in our vite plugin with default config.
Vite app with shadow dom turned on fails to run, because vite is trying to handle css injection to html head. We need to use `./foo.css?inline` to tell vite to bypass that.
Test basic app, and shadow dom app.
More tests will be covered in aurelia/new's e2e tests.

fix(vite-plugin): when using ShadowDOM, need to load css as string

---

packages-tooling/vite-plugin/src/index.ts

fix(vite-plugin): missed some default options in "load" preprocess

---

.gitignore
packages/__tests__/package.json
packages/__tests__/src/3-runtime-html/repeater.unit.spec.ts
packages/__tests__/src/3-runtime-html/template-compiler.local-templates.spec.ts
packages/__tests__/src/3-runtime-html/template-compiler.spec.ts
packages/__tests__/tsc.dev.cjs
packages/rollup-utils.mjs
packages/runtime-html/src/binding/interfaces-bindings.ts
packages/runtime-html/src/compiler/template-compiler.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-element.ts
packages/runtime-html/src/templating/controller.ts
packages/runtime-html/src/templating/rendering.ts
packages/runtime-html/src/templating/view.ts
scripts/dev.ts

To prepare for the extraction of template compiler extraction, the direct usage of resources APIs first need to be simplified. Instead of using full element definition, only use partial. It turns out to be a pretty good change, template compiler emits just enough information about what it sees in the template.
cc @Sayan751

refactor(compiler): simplify definition creation

---

packages/__tests__/src/3-runtime-html/au-slot.spec.tsx
packages/__tests__/src/3-runtime-html/template-compiler.au-slot.spec.ts
packages/__tests__/tsc.dev.cjs
packages/runtime-html/src/resources/custom-elements/au-slot.ts

Currently if `$host` is used in the content of a custom element and that content happens to be passed through another layer of `<au-slot>`, it will end up getting wrong `$host` value. This PR fixes this.
Original thread on Discord https://discord.com/channels/448698263508615178/448699089513611266/1234665951467929666
Thanks @MaximBalaganskiy 
cc @Sayan751

fix(au-slot): ensure passthrough slot get the right host value

---

packages-tooling/__tests__/src/babel-jest/index.spec.ts
packages-tooling/__tests__/src/plugin-conventions/preprocess-html-template.spec.ts
packages-tooling/__tests__/src/plugin-conventions/preprocess-resource.spec.ts
packages-tooling/__tests__/src/plugin-conventions/preprocess.spec.ts
packages-tooling/__tests__/src/ts-jest/index.spec.ts
packages-tooling/plugin-conventions/src/preprocess-html-template.ts
packages-tooling/plugin-conventions/src/preprocess-resource.ts
packages/__e2e__/3-hmr-webpack/playwright/app.spec.ts
packages/__e2e__/3-hmr-webpack/src/components/my-input.html
packages/__e2e__/3-hmr-webpack/src/components/my-input.ts
packages/__e2e__/3-hmr-webpack/src/services.ts
packages/runtime-html/src/resources/custom-element.ts
packages/testing/src/startup.ts

As the wide support for TC39 decorators are still lacking, this PR refactors the convention-plugin to rewrite the following decorators:
- bindable
- containerless
- useShadowDOM
- capture
- alias 
- inject
Discord thread: https://discord.com/channels/448698263508615178/1230047298084409464

feat(convention): rewrite runtime-html decorators

---

packages/__tests__/src/3-runtime-html/au-slot.spec.tsx
packages/runtime-html/src/compiler/template-compiler.ts
packages/runtime-html/src/resources/custom-elements/au-slot.ts
packages/runtime-html/src/templating/rendering.ts
packages/runtime-html/src/utilities-dom.ts
packages/template-compiler/src/index.ts
packages/template-compiler/src/template-compiler.ts
packages/template-compiler/src/utilities-dom.ts

In a previous at #1959 , parent scope of a projection content is set to be always the same with the scope that provides `$host` value, which is wrong. Reported by @MaximBalaganskiy at https://discord.com/channels/448698263508615178/1236855768058302526 . This PR fixes it.
Also:
- Separate binding command resolver from other resources resolver, so it makes more sense
- use standard treewalker API instead of our own tree walker for finding target comments
- cleanup leftover unused code in #1959
cc @Sayan751

fix(au-slot): separate parent scope selection from host scope selection

---

docs/user-docs/developer-guides/migrating-to-aurelia-2/README.md
docs/user-docs/templates/template-syntax/attribute-binding.md
packages/__tests__/src/3-runtime-html/custom-elements.harmony.spec.ts
packages/__tests__/src/3-runtime-html/custom-elements.infer-expression.spec.ts
packages/__tests__/src/3-runtime-html/template-compiler.spec.ts
packages/template-compiler/src/binding-command.ts

Our binding syntax comprises of 3 parts: target, command and expression as per the following formular:
```
target.command="expression"
```
Currently, when `expression` is absent, or empty, like the following examples:
```html
<input value.bind="">
or
<input value.bind>
```
it's treated as an empty string, which means the template above works like this:
```html
<input value.bind="``">
```
This is a missed-opportunity in v1, where we could have better dev experience, like suggested in #1259 . When the `expression` is either empty or absent, we can infer the expression based on the `target`. so for the above example, it should be understood as:
```html
<input value.bind="value">
```
All binding commands that will share this behavior are:
- `.bind`
- `.one-time`
- `.to-view`
- `.from-view`
- …

feat(template): auto infer binding expression when empty

---

docs/user-docs/router-lite/router-events.md
packages/__tests__/src/router-lite/current-route.spec.ts
packages/router-lite/src/configuration.ts
packages/router-lite/src/current-route.ts
packages/router-lite/src/index.ts
packages/router-lite/src/router.ts

feat(router-lite): current route

---

packages-tooling/__tests__/src/plugin-conventions/preprocess-html-template.spec.ts
packages-tooling/plugin-conventions/.eslintrc.cjs
packages-tooling/plugin-conventions/src/hmr.ts
packages-tooling/plugin-conventions/src/preprocess-html-template.ts
packages-tooling/plugin-conventions/src/preprocess-resource.ts
packages-tooling/plugin-conventions/src/strip-meta-data.ts
packages/__e2e__/3-hmr-webpack/src/components/my-input.html
packages/__e2e__/3-hmr-webpack/src/resource.d.ts
packages/__e2e__/3-hmr-webpack/webpack.config.js
packages/expression-parser/src/expression-parser.ts
packages/template-compiler/src/interfaces-template-compiler.ts

In the previous PR at #1960 , because of the presence of `transpileOnly: true` config in our webpack e2e, we accidentally introduced broken bindables code when the html template of a component has `<bindable>` tag. The following scenario will break:
```html
<bindable name="prop1">
```
```ts
class MyEl {
@bindable value
}
```
as the generated code will be something like this:
```ts
...
CustomElement.define({ ...au2ViewDef, bindables: [...{prop1:{}}, 'value'] }, ...)
```
This PR fixes this.
Thanks @ghiscoding for reporting this at https://github.com/aurelia/aurelia/pull/1963#issuecomment-2106112004
cc @Sayan751 @3cp 
Should we change the bindable generation code to use object syntax instead of array? like the following code for the above example:
```ts
...
CustomElement.define({ …
```

fix(convention): use array for bindables isntead of object

---

packages/__tests__/src/i18n/t/translation-integration.spec.ts
packages/__tests__/src/validation-html/validate-binding-behavior.spec.ts
packages/__tests__/src/validation/rule-provider.spec.ts
packages/i18n/src/configuration.ts
packages/i18n/src/errors.ts
packages/i18n/src/i18n.ts
packages/i18n/src/t/translation-binding.ts
packages/validation-html/src/configuration.ts
packages/validation-html/src/errors.ts
packages/validation-html/src/validate-binding-behavior.ts
packages/validation-html/src/validation-controller.ts
packages/validation-i18n/src/configuration.ts
packages/validation/src/ast-serialization.ts
packages/validation/src/configuration.ts
packages/validation/src/errors.ts
packages/validation/src/rule-provider.ts
packages/validation/src/rules.ts
packages/validation/src/serialization.ts
packages/validation/src/validator.ts

Cleaning up error code of i18n, validation & validation html packages.
@Sayan751 with this I've removed all the logger todos, so pinging you for awareness.

refactor(i18n-validation): replace errors with error codes

---

docs/user-docs/templates/binding-behaviors.md

Based on this: https://discourse.aurelia.io/t/signaler-signal-is-not-a-funcion-aurelia-2-esnext/5104
updated `signaler.signal` to `signaler.dispatchSignal`

Updated ISignaler documentation example

---

docs/user-docs/getting-to-know-aurelia/dependency-injection-di/resolvers.md
packages/__tests__/src/1-kernel/di.last.spec.ts
packages/kernel/src/di.resolvers.ts
packages/kernel/src/index.ts

This pull request introduces support for retrieving the last registered value from the Aurelia DI (Dependency Injection) container. In scenarios where multiple values are registered under the same key, the new last resolver ensures that the most recently registered value is always returned.
In the Aurelia DI system, it's possible to register multiple values under the same key. This feature can be useful for various purposes, such as overriding previously registered values without losing them. However, when retrieving these values, the container typically returns all instances associated with the key. There are cases where it's desirable to get only the most recent value, such as when the latest configuration or instance should take precedence.
The implementation of the last resolver …

feat(kernel): add last resolver

---

.vscode/launch.json
packages/__tests__/src/3-runtime-html/attribute-pattern.spec.ts
packages/__tests__/src/3-runtime-html/template-compiler.au-slot.spec.ts
packages/__tests__/src/3-runtime-html/template-compiler.spec.ts
packages/__tests__/src/i18n/t/translation-integration.spec.ts
packages/__tests__/src/i18n/t/translation-renderer.spec.ts
packages/i18n/src/configuration.ts
packages/i18n/src/t/translation-parameters-renderer.ts
packages/i18n/src/t/translation-renderer.ts
packages/kernel/src/di.container.ts
packages/kernel/src/index.ts
packages/runtime-html/src/configuration.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/template-controllers/promise.ts
packages/runtime-html/src/templating/lifecycle-hooks.ts
packages/template-compiler/src/attribute-pattern.ts
packages/template-compiler/src/errors.ts
packages/template-compiler/src/template-compiler.ts

This PR fixes the problem demonstrated in this [SB project](https://stackblitz.com/edit/au2-registrable-issue?file=src%2Fmain.ts). In short, some resources were registered globally, which can cause problem when dealing with multi-app setup. For example, app1 uses the `t` as translation attribute, and app2 uses `i18n` for the same purpose. As the patterns were registered globally, the configuration from one app overwrites the configuration from the another app. This can cause unwanted surprises.
This PR changes that behaviour by lazily registering the formerly globally registered resources (Registrables) to the container.

fix: container specific registrables

---

packages/__tests__/src/router-lite/current-route.spec.ts
packages/__tests__/src/router-lite/smoke-tests.spec.ts
packages/router-lite/src/route.ts

This fixes the issue reported in this [discourse post](https://discourse.aurelia.io/t/transition-plan-for-routes-when-parameters-do-not-change/5431) by @ivanbacher.
Additionally, it add some assertions to some existing tests.

fix(router-lite): replace transition plan for same component with different paths

---

docs/user-docs/components/shadow-dom-and-slots.md
packages/__tests__/src/3-runtime-html/au-slot.slotted.spec.ts
packages/__tests__/src/3-runtime-html/children-observer.spec.ts
packages/kernel/src/functions.ts
packages/runtime-html/src/errors.ts
packages/runtime-html/src/index.ts
packages/runtime-html/src/resources/custom-elements/au-slot.ts
packages/runtime-html/src/templating/children.ts
packages/runtime-html/src/templating/controller.projection.ts

BREAKING CHANGE: currently `@children` and `@slotted` decorators use `*` to express "select all nodes", but this is not what it means as a selector in CSS. Change `*` to `$all` to express select all.
- Cleanup & improve doc for `@children`

refactor(projection): use $all instead of * to include all node types

---

packages-tooling/__tests__/src/plugin-conventions/preprocess-html-template.spec.ts
packages-tooling/__tests__/src/plugin-conventions/preprocess.spec.ts
packages-tooling/plugin-conventions/src/preprocess-html-template.ts
packages-tooling/plugin-conventions/src/preprocess.ts

Related to #1948
This enables foo.module.css file to be processed with CSS module.

feat(plugin-conventions): support foo.module.css CSS module convention

---

docs/user-docs/aurelia-packages/validation/defining-rules.md
packages/__tests__/src/validation-i18n/localization.spec.ts
packages/__tests__/src/validation/rule-provider.spec.ts
packages/validation-i18n/src/localization.ts
packages/validation/src/rule-interfaces.ts
packages/validation/src/rule-provider.ts
packages/validation/src/rules.ts

This PR adds a new feature to the validation packages. So far, it was assumed that a validation rule can have 2 states, valid or invalid. Even though it is generally true that a rule has a single valid state, there are instances where a rule can have several invalid states. A classic example might be [certificate validation errors](https://x509errors.org/). 
The Aurelia validation has not yet supported a validation rule with multiple invalid states and state-specific error messages. This PR introduces the support for that. An example looks like as follows.
```ts
type Error = 'none' | 'fooError' | 'barError';
let state: Error = 'none';
validationRules
.on(obj)
.ensure('name')
.satisfiesState<Error, string>(
/* valid state                 */ 'none',
/* state (validation) function */ …
```

feat(validation): state rule

---

docs/user-docs/developer-guides/migrating-to-aurelia-2/README.md
packages/__tests__/src/3-runtime-html/styles.integration.spec.ts
packages/__tests__/src/3-runtime-html/styles.spec.ts
packages/runtime-html/src/binding/interpolation-binding.ts
packages/runtime-html/src/dom.ts
packages/runtime-html/src/errors.ts
packages/runtime-html/src/observation/class-attribute-accessor.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/custom-attribute.ts
packages/runtime-html/src/resources/resolvers.ts
packages/runtime-html/src/templating/styles.ts
packages/testing/src/index.ts
packages/testing/src/logger-sinks.ts

Currently CSS module registration works by altering how class attribute is compiled: it registers a class custom attribute to map the classes value before setting it on the element. This sometimes causes duplicate registration warning, as reported at https://discord.com/channels/448698263508615178/1244638420274384946
- Additional warn with `ILogger` for duplicate attribute registration, which can be turned off via `CustomAttributeDefinition.warnDuplicate`, we will keep this for now to monitor the duplicate registration issue.

fix(css-modules): avoid duplicate registrations

---

packages/__tests__/src/3-runtime-html/custom-elements.spec.ts
packages/__tests__/src/3-runtime-html/dialog/dialog-service.spec.ts
packages/dialog/src/dialog-event-manager.ts
packages/runtime-html/src/binding/listener-binding.ts

In a previous PR #1891 , event modifier was introduce to help remove boilerplate from mouse & keyboard events. This PR expands the modifier support to all event, for `prevent` and `stop`
- Also automatically call `preventDefault` on form actionless submit event

feat(event): support common event modifier on all events

---

docs/user-docs/router-lite/routing-lifecycle.md
packages/__tests__/src/router-lite/hook-tests.spec.ts
packages/__tests__/src/router-lite/lifecycle-hooks.spec.ts
packages/router-lite/src/component-agent.ts

This PR changes the semantics of `canLoad` and `canUnload` hooks.
If `canLoad` returns no value, `null`, or en explicit `undfined`, the component will be loaded. Returning a routing instruction to perform redirect instead is still supported. To prevent loading altogether, the return of an explicit `boolean` `false` is required.
Similarly, if the `canUnload` returns no value, `null`, or en explicit `undfined`, the component will be unloaded. To prevent unload, the return of an explicit `boolean` `false` is required.

refactor(router-lite): can* hook semantics

---

packages-tooling/vite-plugin/src/index.ts

Solves some vitest+win32 issue identified in aurelia/new#108

fix(vite-plugin): fix vitest Windows issue with html file

---

packages/__tests__/src/2-runtime/scheduler.spec.ts
packages/platform/src/index.ts

Fixes an issue in the task queue when using multiple persistent delayed tasks with different timings.
- close https://github.com/aurelia/aurelia/issues/1542
- resolve https://discourse.aurelia.io/t/platform-taskqueue-does-not-run-concurrent-tasks/5379
- resolve https://discord.com/channels/448698263508615178/448699089513611266
There was a small oversight in the queue processing loop where it assumed the smallest delay task to be in the front of the queue. It now checks all tasks in the delayed task list.
A single test covers this bug properly. Without the fix, it fails with `counter10` and `counter20` being equal. Now it's doubled (though I added some leeway in there to account for flakiness)

fix(task-queue): fix timing issue

---

packages/__tests__/src/2-runtime/scheduler.spec.ts
packages/i18n/src/t/translation-binding.ts
packages/platform/src/index.ts
packages/runtime-html/src/binding/attribute-binding.ts
packages/runtime-html/src/binding/binding-utils.ts
packages/runtime-html/src/binding/content-binding.ts
packages/runtime-html/src/binding/interpolation-binding.ts
packages/runtime-html/src/binding/property-binding.ts
packages/runtime-html/src/resources/template-controllers/promise.ts
packages/state/src/state-binding.ts
packages/testing/src/assert.ts

Removes the `reusable` task queue option. This was originally intended as a performance optimization for animations but the mechanism for animations is going to be optimized separately.

refactor(task-queue): remove 'reusable' param

---

packages/__tests__/src/router-lite/smoke-tests.spec.ts
packages/router-lite/src/route-context.ts

This PR fixes the issue where the host for routed view-model in router-lite was not registered for injection.
Closes #2009.

fix(router-lite): element injection for routed view-model

---

packages/__tests__/src/3-runtime-html/observation-glitches.spec.ts
packages/aurelia/src/index.ts
packages/runtime/src/array-observer.ts
packages/runtime/src/collection-length-observer.ts
packages/runtime/src/computed-observer.ts
packages/runtime/src/interfaces.ts
packages/runtime/src/map-observer.ts
packages/runtime/src/observable.ts
packages/runtime/src/set-observer.ts
packages/runtime/src/setter-observer.ts
packages/runtime/src/subscriber-collection.ts

Currently, as described in #1957 , our binding system needs a way to ensure observer value caching doesn't result in impossible state - or glitch. This is handled through a pre-change notification - or dirty notification, before the actual change notification.
Resolves partially #1957 
cc @Sayan751 @fkleuver

fix(binding): handle glitch

---

packages/__tests__/karma.conf.cjs
packages/__tests__/src/state/state.spec.ts
packages/dialog/src/dialog-interfaces.ts
packages/dialog/src/dialog-service.ts
packages/kernel/src/functions.ts
packages/state/src/interfaces.ts
packages/state/src/state-binding-behavior.ts
packages/state/src/state-binding.ts
packages/state/src/state-getter-binding.ts
packages/state/src/state-templating.ts
packages/state/src/store.ts
packages/testing/src/startup.ts

Fix a bug in the state plugin where it wouldn't call the last action if there's more than 1 action queued, and an action handler returns a promise that resolves after the 2nd action being dispatched.
Resolves #1871 
Thanks @gtroxler @Siddharth1605

fix(state): ensure all actions queued are called

---

packages/__tests__/src/2-runtime/global-context.spec.ts
packages/__tests__/src/3-runtime-html/repeater.unit.spec.ts
packages/__tests__/src/3-runtime-html/template-compiler.au-slot.spec.ts
packages/__tests__/src/3-runtime-html/template-compiler.spec.ts
packages/__tests__/src/i18n/t/translation-parameters-renderer.spec.ts
packages/__tests__/src/i18n/t/translation-renderer.spec.ts
packages/__tests__/src/validation/expression-serialization.spec.ts
packages/__tests__/src/validation/rule-provider.spec.ts
packages/__tests__/src/validation/serialization.spec.ts
packages/__tests__/src/validation/validator.spec.ts
packages/expression-parser/src/expression-parser.ts
packages/runtime-html/src/configuration.ts

One possible optimization of build time template compilation is that template expression can be precompiled into AST. The fully benefit from the potential tree shaking that comes with this optimisation, the parser interface shouldn't be tied to the parser implementation. This PR removes that connection.
This shouldn't affect any application that uses standard `StandardConfiguration`, but if for some reason a minimal setup was used, then the container of that setup needs to register `ExpressionParser` from `@aurelia/expression-parser` to make `container.get(IExpressionParser)` work.
cc @fkleuver @Sayan751

refactor(parser): no longer provide default to exp parser interface

---

packages/__tests__/src/3-runtime-html/input.spec.ts
packages/runtime-html/src/observation/checked-observer.ts
packages/runtime-html/src/resources/template-controllers/if.ts
packages/testing/src/startup.ts

Currently, as per described in #2030, when a radio is repeated started/stopped i.e in an if template, its subsequence activation may have invalid `:checked` state. This is due to the fact that upon stopped, the observer of the radio does not cleanup its internal cache value causing the next activation to be a noop. This PR fixes this.
Close #2030

fix(radio): handle repeated start/stop correctly

---

packages/router-lite/src/index.ts
packages/router-lite/src/route-tree.ts

The inheritance was relatively superfluous. The `IRouteNode` is also not a significant part of the public API. This commit corrects that by renaming the said interface to `IRouteNodeInitializationOptions` as the interface is merely used for creating a `RouteNode`. However, the interface is exported from the package as `RouteNode#create` is a part of the public API.
Thanks @ekzobrain for [reporting this](https://discord.com/channels/448698263508615178/1243519563283435520/1273318182798622936).

chore(router-lite): removed IRouteNode implementation in RouteNode

---

docs/user-docs/components/bindable-properties.md
packages/__tests__/src/3-runtime-html/custom-attributes.spec.ts
packages/__tests__/src/3-runtime-html/custom-elements.spec.ts
packages/runtime-html/src/templating/controller.ts

Currently, as per noted in #2021 by @ekzobrain:
> There is no way to set a single change callback for multiple properties. In Angular there's an ngOnChanges() callback (https://angular.io/api/core/OnChanges) which fires once for all changed bindables. I would like to have something similar in Aurelia, for example "propertiesChanged()". There are cases when component update strategy heavily depends on wheather one or several related properties changed at once.
This is a missing feature of v1 where it was quite difficult to aggregate the changes during 1 flush cycle of a component. Thanks @ekzobrain for bringing this up.
This PR adds support for the ability to declare a aggregated callback on the component instances (attributes/elements) to receive all the changes at once, with the …

feat(bindable): support aggregate callback

---

packages/__tests__/src/3-runtime-html/custom-elements.spec.ts
packages/__tests__/src/3-runtime-html/decorator-observable.spec.ts
packages/runtime/src/observable.ts
packages/runtime/src/setter-observer.ts

This PR changes the timing of the `[name]Changed` callback to after notify, so that it will feel like "after all have settled" handler, rather than the current timing, which is "whenever the prop is changed".
Resolves #2022 
Added a recursive change test for `@bindable` and tweak the existing one for `@observable`, also added tests for the scenario mentioned in #2022
cc @fkleuver @Sayan751 @ekzobrain

refactor(observers): change callback timing to after notify

---

packages/kernel/src/di.container.ts
packages/kernel/src/index.ts
packages/kernel/src/utilities.ts
packages/metadata/src/index.ts
packages/router-lite/src/configuration.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/router.ts
packages/runtime-html/src/templating/controller.ts
packages/template-compiler/src/attribute-mapper.ts
packages/template-compiler/src/attribute-pattern.ts
packages/template-compiler/src/binding-command.ts
packages/template-compiler/src/binding-mode.ts
packages/template-compiler/src/instructions.ts
packages/template-compiler/src/interfaces-template-compiler.ts
packages/template-compiler/src/template-compiler.ts
packages/template-compiler/src/template-element-factory.ts
packages/template-compiler/src/utilities.ts
packages/testing/src/assert.ts
packages/testing/src/util.ts

There's a `isObject` that is left over from the old metadata implementation, that now looks like a stray export, move it to kernel and rename so that it better reflects what it does.
We may add a new internal package to host all of our utilities, instead of leaving them on kernel.

chore: move utilities from metadata to kernel package

---

packages/__tests__/src/3-runtime-html/controller.smoke-test.spec.ts
packages/runtime-html/src/app-root.ts
packages/runtime-html/src/templating/controller.ts

This enables reusing the given host and hostController without trying to resolve the hostController again in the Controller. This fix is likely a predecessor for the fix for #2042.

feat(runtime-html): reuse host and hostController

---

packages/__tests__/src/3-runtime-html/decorator-watch.computed.spec.ts
packages/runtime-html/src/watch.ts

In our previous work related to decorator, addInitialiser was used to add watch metadata for Aurelia to instantiate watcher, but we missed that method decorator is called for every instance so watch metadata is applied multiple times if a component is used more than once.
Thanks to Tordmulen for reporting this on discord: https://discord.com/channels/448698263508615178/448699158052864001/threads/1288414475137060936

fix(watch): initialise only once

---

packages/__tests__/src/router-lite/ast.spec.ts
packages/__tests__/src/router-lite/smoke-tests.spec.ts
packages/router-lite/src/route-expression.ts

The dot character was reserved, presumably to support action component syntax. However, we currently don't have a roadmap to support that feature, the dot character is allowed in the path in this commit.
Closes #2049.

chore(router-lite): allowed dot in parameter value

---

packages/__tests__/src/3-runtime-html/repeat.duplicates.spec.ts
packages/runtime-html/src/resources/template-controllers/repeat.ts

Fixes an issue in the repeater where the scope cache can get misaligned in indexed mode with duplicate objects
https://github.com/aurelia/aurelia/issues/2078
The `getScope` method and the way it was storing scopes associated with duplicate items in the scopeMap is not reliable when existing items are moved around. In that case the indexMap is now used to restore existing scopes from the correct source location instead of a naive FIFO item-based identity lookup.

Fix repeater scope reuse issue

---

docs/user-docs/developer-guides/building-plugins.md

The existing docs were focusing too heavily on Monorepo and not on how to create plugins are their basic core. This makes the docs minimal first and then adds advanced later on.

docs(building-plugins): rewrite building plugin docs

---

docs/user-docs/developer-guides/building-plugins.md

Use Gitbook tabs syntax to break files up into file tabs, fixed issue with inject being used on constructor (the old way).

docs(developer-guides): fix building plugins docs

---

docs/user-docs/tutorials/synthetic-view.md

The synthetic docs were outdated, referencing imports that no longer exist, like lifecycle flags, and some of the definitions of the functions changed. The existing docs were also not overly clear, so this makes them more clear.

docs(synthetic-view): modernize docs

---

packages/__tests__/src/3-runtime-html/custom-elements.spec.ts
packages/runtime-html/src/templating/rendering.ts

Currently the bindings defined on the `<template>` element are rendered after the bindings inside it, causing weird order reported in #2093, also this is inconsistent since v1 has surrogate bindings rendered first. This PR fixes this issue.
Close #2093

fix(rendering): render surrogate bindings before content bindings

---

packages/__tests__/src/3-runtime-html/au-slot.slotted.spec.ts
packages/runtime-html/src/resources/custom-elements/au-slot.ts

Currently `<au-slot>` only observes dom mutation when there's a `@slotted` decorator, which means the following template will never have the callback `slotUpdated` called:
```html
<my-element slotchange.bind="(name, nodes) => slotUpdated(name, nodes)">
<div repeat.for="i of items">...</div>
</my-element>
```
This PR fixes this issue. Thanks @euglv
Closes #2071

fix(au-slot): slotchange callback does not rely on deco

---

packages/__tests__/src/2-runtime/ast.spec.ts
packages/__tests__/src/3-runtime-html/custom-elements.spec.ts
packages/runtime-html/src/binding/property-binding.ts
packages/runtime-html/src/binding/ref-binding.ts
packages/runtime-html/src/renderer.ts
packages/runtime-html/src/resources/template-controllers/repeat.ts
packages/runtime/src/ast.eval.ts

Currently the ref binding works like a one time binding: it only updates the property specified by the template expression once. For the following template as an example:
```html
<div ref="elements[key]">
```
```ts
class MyElementList {
elements: Record<string, HTMLElement>
key = 'div';
}
```
When the element above first renders, we have a div element at `elements.div`, but if we updated `key` to `div2`, for example, `elements.div2` will not have the reference to our `<div />` element.
This PR fixes this by allowing ast assignment evaluation to also have the ability to track on read, in case the evaluator, like Ref binding, need to update the value when the expression changes.
Thanks @euglv for reporting the issues at #2106 
Closes #2106

fix(ref-binding): update value when key expression changes

---

packages/runtime/src/dirty-checker.ts
packages/runtime/src/proxy-observation.ts
packages/runtime/src/setter-observer.ts

Even though property deletion makes Aurelia observation system likely to fail, but we shouldn't be blocking it, and log a warning about potential issue instead.
Also clean up some leftover code for setter observer & dirty checker out of bound. 
Close #2107 
Close #2112
Close #2098

fix(observation): allow property deletion with proxy

---

docs/user-docs/components/class-and-style-binding.md

In "Example: Using CSS Modules in Components", my-component.css should be my-component.module.css.

docs(components) my-component.css -> my-component.module.css

---

docs/user-docs/router-lite/configuring-routes.md
packages/__tests__/src/router-lite/smoke-tests.spec.ts
packages/router-lite/src/instructions.ts
packages/router-lite/src/route-context.ts
packages/router-lite/src/route.ts

This PR adds support for routing to conventional HTML-only components.
The issue is reported in [discourse](https://discourse.aurelia.io/t/router-questions/6360/3). Thanks @elmt1 for reporting this issue!

fix(router-lite): support for conventional HTML-only component

---

packages/__tests__/src/router-lite/lifecycle-hooks.spec.ts
packages/router-lite/src/events.ts
packages/router-lite/src/router.ts
packages/router-lite/src/viewport-agent.ts

This is reported in https://discord.com/channels/448698263508615178/1349513768077627403/1349885887378620456 by @simonfox. When returning a navigation instruction from a `canLoad` hook from a child route caused issue similar to the following.
```
Uncaught (in promise) Error: AUR3352:endTransition 3:VPA(state:currIsEmpty|nextCanLoadDone,plan:'replace',n:RN(ctx:'app-shell/feature-shell/feature-workspace',c:'FeatureWorkspace',path:'workspace'),c:null,viewport:VP(ctx:'app-shell/feature-shell',name:'default'))
at ViewportAgent.jt (viewport-agent.ts:855:11)
at ViewportAgent.ee (viewport-agent.ts:831:16)
at viewport-agent.ts:784:26
at Array.forEach (<anonymous>)
at ViewportAgent.ee (viewport-agent.ts:783:31)
at router.ts:653:28
at Array.forEach (<anonymous>)
at router.ts:652:13
at Batch._ …
```

fix(router-lite): cancelling navigation with redirection from canLoad hook from child route

---

packages/__tests__/src/validation-html/validate-binding-behavior.spec.ts
packages/validation-html/src/validate-binding-behavior.ts
packages/validation-html/src/validation-controller.ts

this supercedes aurelia#2136
see [Discord discusson](https://discord.com/channels/448698263508615178/605165596233170944/1354621721361252533) for details.
When using a binding source which is a projection object, syncing validation errors to the view does not work because the binding target element search uses cached property info and a reference equality check between the binding source and the cached source. In the context of redux/reselect, the entire projection object is replaced and so the binding source is different to that which was cached so the target element is skipped.
This change adds an observer to the binding that is used to invalidate the cached property info when the binding source changes.

fix(validation): invalidate property info cache when source changes

---

packages/validation-html/src/validate-binding-behavior.ts

Drop reference to the binding source reference added as part of #2138 when the binding behavior is cleaning up.
cc @Sayan751

fix(validation): release reference to binding behavior source

---

docs/user-docs/TOC.md
docs/user-docs/router-lite/current-route.md
docs/user-docs/router-lite/router-events.md
docs/user-docs/router-lite/routing-lifecycle.md

Adds documentation for `ICurrentRoute`, a dependency injection token that exposes details of the active route.
Also adds a section about accessing parent route parameters using `IRouteContext`.

docs(router-lite): adds current route documentation

---

packages/__tests__/src/i18n/t/translation-integration.spec.ts
packages/i18n/src/t/translation-binding.ts

Fixes #2170 by adding an `isBound` check to `TranslationBinding.handleChange()` in `@aurelia/i18n`. This prevents an `AUR0203` error when the binding is unbound, such as in scenarios with `if.bind` and `t.bind`.
#2170
- Ran `npm run dev -- --dev i18n --test i18n` to ensure no regressions.

fix(i18n): Add isBound check in TranslationBinding.handleChange to prevent AUR0203

---

packages/__tests__/src/2-runtime/proxy-observable.spec.ts
packages/runtime/src/array-observer.ts
packages/runtime/src/observer-locator.ts
packages/runtime/src/proxy-observation.ts
packages/runtime/src/utilities.ts

Currently proxy observer violates Proxy spec (see Notes section): https://262.ecma-international.org/8.0/#sec-proxy-object-internal-methods-and-internal-slots-get-p-receiver and browsers throw an exception "TypeError: proxy must report the same value for the non-writable, non-configurable property 'xxx'"
This PR is intended to fix it so that a proxy observer does not wrap such properties.

fix(runtime): don't wrap non-configurable and non-writable object properties

---

packages-tooling/__tests__/src/plugin-conventions/type-checking/with-convention.let.spec.ts
packages-tooling/__tests__/src/plugin-conventions/type-checking/without-convention.let.spec.ts
packages-tooling/plugin-conventions/src/template-typechecking.ts

Adds **`<let>` support** to the experimental template type-checker in `plugin-conventions`.
- Introduces a container-lifetime overlay scope so `<let>` declarations are visible to subsequent siblings and their descendants, and stop at the container boundary.
- Handles `.bind`, `.one-time`, `.to-view`, `.two-way`
- Handles `to-binding-context`
- Infers variable types from RHS (literal type / path type, otherwise `any`)
- Uses `Omit<…,'k'> & { k: T }` overlays so last write wins (prevents `never` intersections)
- Skips wrapping primitive RHS in `access(...)` to avoid invalid lambdas; wraps non-primitives so TS still checks the expression
- The `Omit` pattern is avoid intersecting conflicting property types when the same `<let>` name is redeclared
- Container scope is pushed once per sibling …

feat(plugin-conventions): add <let> support to template type-checker

---

packages/__tests__/src/3-runtime-html/styles.integration.spec.ts
packages/runtime-html/src/templating/styles.ts

This fixes the issue reported here: https://github.com/aurelia/aurelia/issues/2225
- Fix CSS Modules processing so static class="…" attributes are transformed even when they appear within nested <template> elements generated by structural directives (repeat.for, if/else, switch/case).
- Replace shallow [class] selection with a recursive DOM traversal that:
- visits every element
- explicitly descends into <template>.content childNodes
- descends normal childNodes for other nodes
- Keep the original token mapping behavioir (split by whitespace, replace tokens using ICssClassMapping, preserve unknown tokens).

fix(runtime-html): map static classes inside nested <template

---

packages/__tests__/src/3-runtime-html/custom-elements.syntax.spec.ts
packages/runtime-html/src/bindable.ts

Currently we treat underscores (`_`) in custom element/custom attribute props as a valid character to be replaced by `-` when transforming to kebab case, this leads to the following transformation:
```
_my_prop_    -> my-prop
my_prop    -> my-prop
```
This isn't how v1 works, and it also dismisses a valid usage of `_`. This PR changes the way attribute is parsed and converting element property names to attribute names will correctly leave `_` alone.

fix(bindable): dont transform underscore in attribute names
